### ISSUE TITLE
Consigne Tri (nouvelle qui ne mentionne plus le clic de souris)

### ISSUE THREAD

**Issue by etienneCharignon** [betagouv/eva#439]

**Comment by GaelleOttan** [comment]
Reprendre la consigne du tri qui parle de "maintenir la pression sur la souris" (les autres consignes ne parlent que de clic, ce qui me semble ok pour les tablettes?)

**Comment by GaelleOttan** [comment]
**Consigne texte conforme à l'audio envoyé sur slack le 30/01**

Vous devez trier les friandises présentes sur le plateau en bas de l'écran en les déposant dans les casiers selon les modèles. Cliquez sur la friandise et maintenez la pression pour déposer le bonbon dans le bon casier.
Pour information nous vous chronométrons. Le chronomètre s'arrête automatiquement lorsqu'il ne reste plus de bonbon sur le plateau.
