### ISSUE TITLE
MES prévention : détail des métriques, sous compétences et compétences

### ISSUE THREAD

**Issue by Alexis-Akinyemi** [betagouv/eva#588]

**Comment by telohtrab** [comment]
Quel est l'état de cette issue maintenant que Prévention est terminé ? 

Je propose la fermeture et l'archivage si ce n'est plus d'actualité @Alexis-Akinyemi !

**Comment by Laurenmichel21** [comment]
@Alexis-Akinyemi cette carte date du mois de novembre tu es ok pour l'archiver ?

**Comment by Alexis-Akinyemi** [comment]
Oui bien sur !
