### ISSUE TITLE
Maquette Situation Prévention

### ISSUE THREAD

**Issue by telohtrab** [betagouv/eva#598]
Proposition V3

Après discussion avec Gaëlle, passage des smileys aux panneaux plus compréhensibles et test d'une interface de "choix" composée d'un grand rectangle scindé en 2 par une sorte de slash. L'idée étant qu'à terme, quand on survole une partie ou l'autre du rectangle, le slash se décale pour montrer qu'on choisit une solution "au-dessus" de l'autre.

![1_Prévention Pastilles](https://user-images.githubusercontent.com/7781917/69646838-c9698380-1068-11ea-84fc-392edb027aa3.png)
![2_Prévention Smiley](https://user-images.githubusercontent.com/7781917/69646839-ca021a00-1068-11ea-9b6c-7cc5b8655e2a.png)
![3_Prévention Dessins](https://user-images.githubusercontent.com/7781917/69646840-ca021a00-1068-11ea-85ca-5d02d78cd9b2.png)
![4_Prévention Dessins_hover](https://user-images.githubusercontent.com/7781917/69646841-ca021a00-1068-11ea-8099-7db61b568878.png)

**Comment by etienneCharignon** [comment]
comment ça s'affiche dans le cas du peintre ?

**Comment by telohtrab** [comment]
Très TRES bonne question. J'ai fait l'hypothèse qu'on aura besoin de "grands" dessins pour le moment, mais ils pourront sûrement être revus à la baisse en terme de dimensions

**Comment by GaelleOttan** [comment]
@etienneCharignon ta question concerne l'emplacement et la taille de la fenêtre ou de comment on gère les choix pour un non danger? @Alexis-Akinyemi @laurenehoutin je crois qu'on a pas pensé à ce qu'on affiche dans l'image des choix pour l'image ok (donc le peintre)

**Comment by laurenehoutin** [comment]
Qu'est ce que vous pensez :
- d'un téléphone qui indique un appel à la police
- d'un pouce pour dire qu'il ne faut rien faire 
?

**Comment by GaelleOttan** [comment]
ça me semble bien

**Comment by telohtrab** [comment]
![1_Prévention Pastilles](https://user-images.githubusercontent.com/7781917/70907605-9b44e700-2009-11ea-9a6e-293df31f1510.png)
![2_Prévention Smiley](https://user-images.githubusercontent.com/7781917/70907606-9b44e700-2009-11ea-82da-24d2e3a9194c.png)
![2_Prévention Smiley-1](https://user-images.githubusercontent.com/7781917/70907607-9b44e700-2009-11ea-9a9b-f404b2a9f0c5.png)
![3_Prévention Dessins](https://user-images.githubusercontent.com/7781917/70907608-9b44e700-2009-11ea-94c5-aa190e21821b.png)


Voici la dernière proposition

**Comment by telohtrab** [comment]
![image](https://user-images.githubusercontent.com/7781917/70907634-a7c93f80-2009-11ea-99c9-e366d2622fb2.png)

Sur retour de @shanser pour rendre plus évident la notion de choix à la fin. 

Il faut imaginer également qu'au hover, le slash se décalerait un peu et mettrait en retrait l'autre proposition.

**Comment by GaelleOttan** [comment]
Il faut garder en tête qu'on aura aussi un message audio pour accompagner l'exercice. Sans les écrans d'interactions, c'est pas simple de comprendre qu'il faut choisir, mais c'est vrai que je trouve ça un peu plus clair avec le ?
@telohtrab tu peux faire les écrans quand la souris passe sur l'une et l'autre des propositions?
Par ailleurs, pourquoi est ce que les propositions sont espacées de la vignette pour le niveau de danger et pas pour le choix de l'action? 
Enfin, est ce que l'on peut fermer cette fenêtre si on souhaite revoir l'image en entier (ce design obstrue la vision globale, c'est peut être pas simple pour les évalués de contextualiser avec juste la vignette ronde du danger... qu'est ce que vous en pensez @Alexis-Akinyemi ?)

**Comment by telohtrab** [comment]
Oui, je suis sur les versions intermédiaires. 

Je peux réfléchir à un bouton pour fermer, ou réduire la taille du dessin dans le cercle pour qu'on en voit "plus".

Les propositions sont espacées pour le niveau de danger et pas l'action, tout simplement parce que l'un n'a pas la même taille que l'autre. Et sachant que je veux conserver la vignette de la même taille et au même endroit dans les deux cas, je n'avais pas trop le choix. 

Si je colle les niveaux de danger, pour le coup ça fait vide en bas.

**Comment by telohtrab** [comment]
Voici quand on survole l'une des propositions :
![image](https://user-images.githubusercontent.com/7781917/70916517-1adbb180-201c-11ea-882b-438f43396753.png)

**Comment by MatthieuMARTIN** [comment]
bonjour

**Comment by laurenehoutin** [comment]
De notre côté, ça parait plutôt bien. Même si on pense aussi que ca peut ne pas être évident qu'il faut choisir entre les deux vignettes, on ne voit pas de meilleure solution pour rendre cela plus clair. On verra au test...
Par ailleurs, en ce qui concerne le fait de pouvoir fermer, le problème est encore une fois que ca ne met pas les gens sur un pied d'égalité en termes de stratégie : certains vont le faire et d'autres noms, et donc ca peut constituer une variable qui viendra parasiter les résultats (la question des résultats et la question du temps)... Ou alors il faut le mesurer, et ça va compliquer l'algo.

**Comment by telohtrab** [comment]
![1_Prévention Pastilles](https://user-images.githubusercontent.com/7781917/71814910-27cd4d00-307e-11ea-9260-a15b7d280eeb.png)
![2_Prévention Pastilles_hover](https://user-images.githubusercontent.com/7781917/71814919-2c920100-307e-11ea-8e17-e3adc533e47a.png)
![3_Prévention_Panneaux](https://user-images.githubusercontent.com/7781917/71814920-2c920100-307e-11ea-8b8a-2fd5c8cbc14f.png)
![4_Prévention_Panneaux_Hover](https://user-images.githubusercontent.com/7781917/71814921-2d2a9780-307e-11ea-9de3-3f0284227b2b.png)
![5_Prévention_Panneaux_Clic](https://user-images.githubusercontent.com/7781917/71814922-2d2a9780-307e-11ea-90b3-eb99ab8919a0.png)
![6_Prévention_Vignettes](https://user-images.githubusercontent.com/7781917/71814923-2d2a9780-307e-11ea-85ef-a07ee77b988c.png)
![7_Prévention_Vignettes_Hover](https://user-images.githubusercontent.com/7781917/71814925-2dc32e00-307e-11ea-853b-2b7e18b3e8fc.png)
![8_Prévention_Vignettes_Selection](https://user-images.githubusercontent.com/7781917/71814926-2dc32e00-307e-11ea-9992-026fdf42d63b.png)
![9_Prévention_Pastille traitée hover 1](https://user-images.githubusercontent.com/7781917/71814927-2dc32e00-307e-11ea-8fec-242c04274328.png)
![9_Prévention_Pastille traitée hover 2](https://user-images.githubusercontent.com/7781917/71814928-2e5bc480-307e-11ea-888c-febd7479caa6.png)
![9_Prévention_Pastille traitée hover 3](https://user-images.githubusercontent.com/7781917/71814929-2e5bc480-307e-11ea-9d74-d69d48a7f2b4.png)
![9_Prévention_Pastille traitée](https://user-images.githubusercontent.com/7781917/71814930-2e5bc480-307e-11ea-91a3-31a9d116f667.png)

Voici quelques précisions pour les écrans de Prévention avec notamment les différentes situations de hover/sélection. A dispo pour en parler
