### ISSUE TITLE
Maquetter Drone

### ISSUE THREAD

**Issue by telohtrab** [betagouv/eva#599]
Voici un premier jet pour la Maquette de la MES Drone

On aurait donc cette vue 3D qui prend l'entièreté de l'écran avec un "petit" écran de surveillance dans un coin de la gameview.

J'ai ajouté une mention "Live" qui pourrait clignoter dans l'idéal pour renforcer le coté caméra de surveillance. Il est également possible comme vu sur le second écran, d'agrandir cette vue caméra notamment pour les plus petits écrans. 

![1_Drone_Vue3D](https://user-images.githubusercontent.com/7781917/69649686-b3aa8d00-106d-11ea-9e57-bcbb52905b28.png)
![1_Drone_Vue3D_2DAGRANDIE](https://user-images.githubusercontent.com/7781917/69649687-b3aa8d00-106d-11ea-8c8d-f188aeb970f9.png)

**Comment by telohtrab** [comment]
Et voici un design alternatif des "points de vue" 
![1_Drone_Vue3D_Pointsalternatifs](https://user-images.githubusercontent.com/7781917/69649908-0dab5280-106e-11ea-92a7-a69c84a669f4.png)

**Comment by laurenehoutin** [comment]
Nous préférons la dernière image car elle rend plus clair le fait qu'il s'agit d'un angle de vue, et donc ca peut aider ceux qui n'auraient pas compris la consigne.

**Comment by GaelleOttan** [comment]
Je préfère aussi les deuxièmes points car le faisseau aide à la compréhension. Par contre, je trouve que ce truc de live ça embrouille complètement l'exercice et le fait que le bouton pour élargir l'image soit de la même couleur que les boutons de choix d'emplacement aussi, ça complique la compréhension

**Comment by GaelleOttan** [comment]
et je me demande si ce n'est pas mieux que matthieu pousse le dessin un peu plus vers la gauche et qu'on puisse poser l'image à positionner en bas à droite

**Comment by telohtrab** [comment]
Ok pour les points de vue, je suis assez d'accord.
J'ai souhaité par ailleurs faire ce que tu dis Gaëlle au départ pour poser la caméra sur la droite, mais je manquais de place, pas de problème pour le déplacer. 

Enfin, peux-tu développer pourquoi l'icône "Live" embrouille l'exercice ? J'en ai compris que c'était une mise en situation de surveillance d'installation, ça me paraissait logique de mettre ça là. Sinon, on a pas vraiment d'élément signifiant qui indique que l'un est une surveillance de l'autre. 

Le bouton pour agrandir et les points de vue sont trop proches je suis d'accord. Je vais réfléchir à quelque chose pour les différencier.

**Comment by telohtrab** [comment]
Est-ce que vous êtes OK pour fermer cette issue, n'étant plus d'actualité ?
