### ISSUE TITLE
Lisser la communication du produit en eva

### ISSUE THREAD

**Issue by GaelleOttan** [betagouv/eva#613]
- [x] Reprendre les contenus du site vitrine
- [x] reprendre la fiche sur beta.gouv
- [x] Intégrer des signatures de mail

**Comment by etienneCharignon** [comment]
Question : Est-ce qu'on change aussi le nom de la start-up ?

**Comment by etienneCharignon** [comment]
@GaelleOttan Si cette issue est terminée, peux-tu la fermer (le bouton [close and comment] ci-dessous) et l'archiver. Du point de vue du dev, on peut fermer cette issue car on en a une autre pour suivre ce sujet : #653

**Comment by GaelleOttan** [comment]
@etienneCharignon il manque encore la partie signature de mail, je dois voir ça avec @telohtrab

**Comment by etienneCharignon** [comment]
_message de l'agent de surveillance de la conformité des tickets 😁 _ :

Du coup, si c'est pas fini, est-ce que tu peux garder cette issue dans "en cours" ou "backlog métier" ou alors fermer cette issue et en créer une nouvelle juste pour ce dernier point dans backlog métier.

**Comment by GaelleOttan** [comment]
@telohtrab est ce que tu pourrais nous faire une signature de mail stp avec eva?

**Comment by telohtrab** [comment]
Done !
