### ISSUE TITLE
Suivi/ relation DGEFP Décembre

### ISSUE THREAD

**Issue by GaelleOttan** [betagouv/eva#616]
contribue à #661

Suivi de la relation DGEFP sur le mois de décembre, en vu de présenter un point d'étape et de programmer une rencontre physique en janvier

**Comment by etienneCharignon** [comment]
@GaelleOttan quand je lis ton commentaire, je me dis que les issues github ne sont pas super adaptée pour suivre ce genre de choses ("relancer le 28", "se fixer un rendez-vous à la rentrée en janvier", "produire une note pour le 6"). Moi, j'utilise gmail pour ça. Je me fais un mail à moi même par truc à ne pas oublier puis j'utilise la fonction "mettre en attente" et je choisi une date à laquelle je veux que le mail me rappelle un truc que je dois faire. Pour que ça marche, je lis mes mails tous les jours et je n'en ai jamais plus de 20 à lires (j'archive tout ce qui est traité).

**Comment by GaelleOttan** [comment]
Point d'étape envoyé à la DGEFP Lundi 17: 
https://docs.google.com/document/d/1gvTqn5rG01wKsi5HKI3kO3TB92I64ypFw6-UO42hUww/edit?usp=sharing

Proposition de date de rencontre proposée: Mardi 7, mercredi 8, mardi 14, mercredi 15 ou mercredi 22 janvier

**Comment by etienneCharignon** [comment]
@GaelleOttan J'ai lu le document. c'était plaisant à lire. C'est fout tout ce qu'on a fait !
Petit remarque : je ne sais pas si c'est un problème ou au contraire une exigence, mais le document est accessible à tous. A partir du moment ou tu publie cette url dans une issue github, elle deviens publique et le document est autorisé en lecture à toutes les personnes connaissants cette url.
