### ISSUE TITLE
mturk : gestion des tokens

### ISSUE THREAD

**Issue by Alexis-Akinyemi** [betagouv/eva#628]
Créer 1000 tâches pour générer 1 token par personne, etc ?

Contrôler le temps de passation pour 1h pile ?

Décomposer les tâches pour avoir un prix par tâche ?

**Comment by francois2metz** [comment]
1. On génére un token en javascript dans la page mturk
1. On crée l'url vers typeform avec le token (qui est un champ caché dans typeform)
1. Dans l'écran de fin (thank you screen) du typeform, on crée l'url vers eva avec le token qui préremplit le champs nom/prénom

**Comment by francois2metz** [comment]
Une tache avec la génération de token https://workersandbox.mturk.com/requesters/A1DOE2HRJW6GZN/projects?ref=w_pl_prvw

**Comment by francois2metz** [comment]
Le code a mettre dans le projet mturk

```
<a id="lien">Le lien devrait être remplacé ici</a>
<script src="https://wzrd.in/standalone/uuid%2Fv4@latest"></script>
<script>
  var url = 'https://evabetagouv.typeform.com/to/t8PciW?nom='+ uuidv4();
  var lien = document.getElementById('lien');
  lien.textContent = url;
  lien.setAttribute('href', url);
</script>
```
