### ISSUE TITLE
Arbitrer sur la notion d'efficience

### ISSUE THREAD

**Issue by Alexis-Akinyemi** [betagouv/eva#629]
Piste : trouver un moyen de synthétiser les informations pour qu'elles soient activables par les accompagnants. 
-> augmenter le nombres de pistes (formations, annonces labonneboite, etc)

**Comment by Alexis-Akinyemi** [comment]
Idée creusée aujourd'hui :

1- **titre** : Bilan global eva 

2- **continuum qui remplace efficience globale** : de “Gros besoin compétences de base”   à  “polyvalence sur les formation métier élevée” (wording à remanier)

3- **contextualisation** : Evaluation réalisée sur les compétences comprises dans eva “et seulement. 

4- Radar des compétences 
5- Restitution détaillée

**Comment by Alexis-Akinyemi** [comment]
@GaelleOttan  @telohtrab Notre proposition liée à cela avec @laurenehoutin pour le point 2 (continuum visant à remplacer efficience globale) : 
https://docs.google.com/document/d/1FFsXSqqKjqHqba0ghAvCfkwKcrr0-Ee2Niuzqubm4gQ/edit?usp=sharing

**Comment by telohtrab** [comment]
Quel est l'état de cet issue avec l'avancée actuelle des travaux ? Si ce n'est plus d'actualité, je propose la fermeture et l'archivage @Alexis-Akinyemi  :)

**Comment by laurenehoutin** [comment]
Oui parfait !
