### ISSUE TITLE
Illustrer le site vitrine

### ISSUE THREAD

**Issue by etienneCharignon** [betagouv/eva#639]
Il faut remplacer les illustrations factices (avec une femme en rouge qui fait de la tablette) par des illustrations reflétant ce qu'est eva.

Il y a deux illustration à remplacer : 
- sur la page d'accueil
- sur la page compétences évaluées

**Comment by MatthieuMARTIN** [comment]
Le croquis que je propose pour la futur illustration à venir pour le site,
@Benjamin m'a dit qu'il faut le format soit en 1x1 et en 2x1, d'ou le repère carré gris au milieu.

![illustration-site-eva1](https://user-images.githubusercontent.com/58987553/80082590-dd9ca880-8554-11ea-81b4-e14b41eaffe4.jpg)

**Comment by telohtrab** [comment]
C'est vraiment super Matthieu, bravo !

Tu peux caler le petit "pin" du logo Éva à l'arrière de l'ordinateur a la
place d'un éventuel logo Apple peut être ? :-)

Quant aux couleurs, si tu pouvais essayer de te servir au maximum de la
palette avec quelques variantes, recherchons le plus cohérent possible, pas
forcément le réalisme sur ce coup-là :-)

Le jeu. 23 avr. 2020 à 11:23, MatthieuMARTIN <notifications@github.com> a
écrit :

**Comment by MatthieuMARTIN** [comment]
Coucou ! Ravis que ça te plaise,
Ok pour tout ça, Tu peux me transmettre le petit "pin" du logo eva, et la palette de couleur stp ? :3
Merci ! 
Bonne soirée,

**Comment by MatthieuMARTIN** [comment]
@telohtrab , Coucou ! Ravis que ça te plaise,
Ok pour tout ça, Tu peux me transmettre le petit "pin" du logo eva, et la palette de couleur stp ? :3 Je ne sais pas ou trouver ça ...
Merci !
Bonne soirée,

**Comment by telohtrab** [comment]
Tu peux le trouver ici ! 
![image](https://user-images.githubusercontent.com/7781917/80366592-cf6ac700-8889-11ea-836e-04b033f8fd1f.png)

**Comment by telohtrab** [comment]
Pour la palette : 
![image](https://user-images.githubusercontent.com/7781917/80367467-73a13d80-888b-11ea-8423-f8476bf5d122.png)

**Comment by MatthieuMARTIN** [comment]
@telohtrab merci beaucoup :)

**Comment by MatthieuMARTIN** [comment]
Et voila l'illustration finalisée ! @telohtrab 

![illustration-site-eva](https://user-images.githubusercontent.com/58987553/80479653-a3197e00-894f-11ea-96a3-45cc09a15bdc.jpg)

**Comment by telohtrab** [comment]
Merci Matthieu, c'est top !

Voici ce que ça donne en situation, j'ai un simple doute sur la présence peut-être trop importante du bleu eva... Peut-être les murs pourraient-t'ils être clairs et seulement le sol en bleu ? Qu'en penses-tu ?

![image](https://user-images.githubusercontent.com/7781917/80503626-6dd25780-8972-11ea-9a6d-685ef8d013a2.png)

**Comment by MatthieuMARTIN** [comment]
@telohtrab en effet, comme ça alors ? 
![illustration-site-eva](https://user-images.githubusercontent.com/58987553/80510939-b5a9ac80-897b-11ea-856f-5619ed9d4a41.jpg)

**Comment by telohtrab** [comment]
Yes merci !

Et peut être une couleur de contraste pour les chaises, qui ne soient pas
dans la même couleur que le pull... (Le jaune ou le rouge peut être ?)
Sinon l'image est peut être un peu froide

Le mar. 28 avr. 2020 à 18:12, MatthieuMARTIN <notifications@github.com> a
écrit :

**Comment by MatthieuMARTIN** [comment]
@telohtrab  ah oui bien vu je n'avais pas utilisé le rouge en plus, 
![illustration-site-eva](https://user-images.githubusercontent.com/58987553/80512733-3e294c80-897e-11ea-964c-53b34992928b.jpg)

**Comment by telohtrab** [comment]
C'est top ! 

Je veux bien un export ici > 
![image](https://user-images.githubusercontent.com/7781917/80582472-10d8af00-8a0f-11ea-989c-26f7da1331cd.png)

**Comment by MatthieuMARTIN** [comment]
@telohtrab c'est fait ;)
