### ISSUE TITLE
Permettre aux gens de mturk de facilement trouver leur token a la fin pour le copier dans l'interface de mturk.

### ISSUE THREAD

**Issue by francois2metz** [betagouv/eva#658]
Ajouter le nom / prénom de l'évalué·e sur l'écran de fin

> Merci et bravo {{prenom / nom}}

![Screenshot_2019-12-16 eva](https://user-images.githubusercontent.com/86659/70894292-07652200-1fed-11ea-8970-8fcfb2036b2b.png)

**Comment by shanser** [comment]
Si j'ai bien compris, l'objectif est d'afficher le token pour le mettre dans mturk à la fin de leur passage. Dans ce cas, je trouve que l'implémentation n'est pas satisfaisante puisque 

1. c'est très long
2. on ne peut pas copier/coller

je mets également le message dans #628

**Comment by shanser** [comment]
<img width="1552" alt="Capture d’écran 2019-12-16 à 12 12 22" src="https://user-images.githubusercontent.com/28393/70902822-e0fbb280-1ffd-11ea-975e-50503fd6a743.png">

**Comment by etienneCharignon** [comment]
J'ajoute aussi ici une discussion faite sur slack : 
> @telohtrab : nous avons ajouté le nom de l’utilisateur sur l’écran de fin comme tu peux le voir sur l'image ci-dessous. J’ai l’impression qu’on à un problème estétique à cause du nom qui revient à la ligne. Sur figma tu avais mis juste le prénom de la personne, mais pour faire ça, il faudrait ajouter un champ sur l’écran d’accueil pour saisir séparément le nom et le prénom. C’est peut-être possible, c’est à discuter. Mais peut-être as-tu d’autres idées. Est-ce que je crée une issue pour ce problème d’estétisme ou on laisse tomber ?

<img width="1017" alt="Capture d’écran 2019-12-16 à 11 20 17" src="https://user-images.githubusercontent.com/298214/70976210-d8fa4c00-20ab-11ea-9354-cd968acb31f6.png">

ce à quoi Benjamin à répondu : 
> Effectivement ce serait moins "formel" d'avoir uniquement le prénom je pense. Une solution intermédiaire serait de passer à la ligne tout le nom prénom pour avoir
> ```
> Merci et bravo
> Étienne Charignon !
> ```
> Ce sera toujours plus équilibré

**Comment by Alexis-Akinyemi** [comment]
Je réouvre cette issue car on un problème de parcours si les gens cliquent sur suivant  :
![image](https://user-images.githubusercontent.com/20936092/71262908-17f4ff80-2341-11ea-92fa-0b05cbd1ee4b.png)

On peut palier à ce problème en leur disant de récupérer le code en haut à droite mais cela revient à leur dire que le code y est disponible dès le début ...
Est-il possible de "supprimer" le bouton "suivant" pour la campagne mturk uniquement ?

**Comment by francois2metz** [comment]
La configuration de la campagne mturk n'affichera plus les compétences fortes a la fin.
