### ISSUE TITLE
Situation Prévention : les illustrations

### ISSUE THREAD

**Issue by etienneCharignon** [betagouv/eva#662]

**Comment by MatthieuMARTIN** [comment]
![Risques-1--Une-personne-monte-dans-un-camion-NON-2](https://user-images.githubusercontent.com/58987553/71021710-366bb880-20ff-11ea-8308-aacf935755bd.jpg)
![risques-2--Liquide-dangereux-BALAIS-2](https://user-images.githubusercontent.com/58987553/71021720-3a97d600-20ff-11ea-94e4-48ac99cc3a96.jpg)

Les 2 vignettes qui n'allaient pas corrigées.
Pour la première, je n'ai pas fini la couleur mais vous pouvez déjà me dire si ça vous va ou pas !

**Comment by MatthieuMARTIN** [comment]
![Risque-4-peinture-du-mur-OK](https://user-images.githubusercontent.com/58987553/71023135-67012180-2102-11ea-93e0-e30d4bf30ba6.jpg)
![Risque-4-peinture-du-mur-ALARME-INCENDIE](https://user-images.githubusercontent.com/58987553/71023136-6799b800-2102-11ea-892f-6be5b2ca2cb6.jpg)
Pareil, au trait, en attendant validation pour faire la couleur !

**Comment by MatthieuMARTIN** [comment]
![Risque-5-tuyau-de-gaz-qui-fuit-rustine](https://user-images.githubusercontent.com/58987553/71024251-c5c79a80-2104-11ea-990f-17813d4e1c09.jpg)
Et voila pour la fuite de gaz. 
Par contre, quoi illustrer pour le 2e choix : "Tuyau de gaz qui fuit
Choix Action1 : Déclenche  l’alarme" ? 
ça existe les alarmes de gaz ? comme l'appareil alarme incendie ?

**Comment by GaelleOttan** [comment]
> Pour le mec qui passe le balais, c'est un peu mieux mais je trouve qu'il ne ressemble toujours pas à un mec du chantier. Il faudrait probablement remplacer le balais par un balais brosse (moins jardin), changer la couleur de ses habits (peut être gris tachés de peinture ou de platre?) et que ses gants soient plus batiment (là on dirait des gants de jardin), des chaussures de chantier/ sécurité et un casque jaune
> Le mec qui remet les clés je trouve ça bien mieux
> Le pouce ça me semble suffisant
> l'alarme incendie, je grossirais l'icone de l'incendie car pas très lisible si on ne connait pas ce boitier
> La fuite de gaz, on comprends pas que c'est une rustine. Il faudrait plutôt mettre du scotch marron (ou voir quelqu'un mettre du scotch pour que ce soit compréhensible) je pense

**Comment by MatthieuMARTIN** [comment]
![écran-9-v6](https://user-images.githubusercontent.com/58987553/71085109-066ff400-2197-11ea-9e24-161c3427a7ee.jpg)
L'écran principale est comme ça maintenant, iln'y a plus de bière, sauf pour le conducteur.

**Comment by GaelleOttan** [comment]
Message de Matthieu: J'aimerais jsute de l'aide sur "quoi illustrer" pour la fuite de gaz : "Déclenche l’alarme" ?

**Comment by MatthieuMARTIN** [comment]
> t un peu mieux mais je trouve qu'il ne ressemble toujours pas à un mec du chantier. Il faudrait probablement remplacer le balais par un balais brosse (moins jardin), changer la couleur de ses habits (peut être gris tachés de peinture ou de platre?) et que ses gants soient plus batiment (là on dirait des gants de jardin), des chaussures de chantier/ sécurité et un casque jaune

**Comment by MatthieuMARTIN** [comment]
![Risques-1--Une-personne-monte-dans-un-camion-NON-2](https://user-images.githubusercontent.com/58987553/71098181-9753c900-21b1-11ea-890d-064742f0d4a2.jpg)
![risques-2--Liquide-dangereux-BALAIS-2](https://user-images.githubusercontent.com/58987553/71098182-97ec5f80-21b1-11ea-8f89-0ab7b665dc16.jpg)
![Risque-4-peinture-du-mur-ALARME-INCENDIE](https://user-images.githubusercontent.com/58987553/71098183-97ec5f80-21b1-11ea-83bf-cbcabffc3bdd.jpg)
![Risque-4-peinture-du-mur-OK](https://user-images.githubusercontent.com/58987553/71098184-97ec5f80-21b1-11ea-93e8-9ab09823c3b8.jpg)

Avec les modifs et la couleur !

**Comment by laurenehoutin** [comment]
Pour la fuite de gaz, on pensait à un bouton d'alerte gaz (comme les alertes incendie dans les batiments) avec une illustration de ce style (sauf qu'à la place du feu on met une machine avec du gaz qui s'échappe)

![verification-reglementaire-incendie-desenfumage-apic-consult-300x300](https://user-images.githubusercontent.com/56107558/71098611-498b9080-21b2-11ea-98af-4c7ed2f113e4.jpg)

**Comment by MatthieuMARTIN** [comment]
Et voila ce que je propose pour  le choix fuite de gaz : déclencher l'alarme. 
![Risque-5-tuyau-de-gaz-qui-fuit-ALARME](https://user-images.githubusercontent.com/58987553/71103619-b6a32400-21ba-11ea-9714-7fb5c3f1936d.jpg)
j'ai suivi ce croquis que quelqu'un dont je ne connais pas l'identité m'a fait ici ^^ 
![alarme](https://user-images.githubusercontent.com/58987553/71103688-d0dd0200-21ba-11ea-817d-cce1a3b146bd.png)

**Comment by GaelleOttan** [comment]
C'est bien là on voit pas le lien avec le gaz et il manque le fait que c'est une alarme pour faire en sorte que les gens s'évacuent. Il faudrait rajouter dessus ou dessous le bouton qqc du genre
![image](https://user-images.githubusercontent.com/48095868/71103928-45b03c00-21bb-11ea-9ddf-bac7a41f57af.png)

**Comment by GaelleOttan** [comment]
Et une autre remarque sur la remise des clés: sur l'image où le mec est derrière le volant il est en manche longue et sur la remise des clés à manche courte, il faudrait mettre les deux à manche longue puisque c'est sensé être le même type. Et je serais pour enlever le chignon, je trouve que ça rend l'image plus complexe à comprendre @MatthieuMARTIN

**Comment by MatthieuMARTIN** [comment]
J'ai mis à jour les images ci dessus avec les modifs demandées @GaelleOttan  ! Si on est tout bon ainsi je met tout ça dans le drive !!

**Comment by GaelleOttan** [comment]
@MatthieuMARTIN Top! Je mettrais juste un peu plus gros la maison qui prend feu sur la vignette de l'alarme incendie pour que les gens qui ne connaisse pas le boitier puisse bien voir de quoi il s'agit (la même taille que pour le sos gaz). Et je différencierais bien le feu du gaz
CF: icone gaz https://www.google.com/search?q=gas+icon&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiZmYeI58HmAhUGohQKHXcRD2EQ_AUoAXoECA0QAw&biw=1440&bih=789#imgrc=N6V29j_zozbclM:
VS icone feu: https://www.google.com/search?q=fire+icon&source=lnms&tbm=isch&sa=X&ved=2ahUKEwie8MSQ58HmAhUxA2MBHaU3Am4Q_AUoAXoECBAQAw&biw=1440&bih=789#imgrc=ELRZsT-i4CCXhM:
Après on est tout bon!

**Comment by MatthieuMARTIN** [comment]
Ok @GaelleOttan j'ai fait les modifs et mis à jour mon post plus haut ! Je met les fichiers sur le drive pour les autres !

**Comment by MatthieuMARTIN** [comment]
Bonjour et bonne année à tous ! 
Voici l'image pour le tuto de la situation dangers. 

Les choix seront :
Choix action 1 : téléphone aux pompiers
Choix action 2 : prend une photo

![écran-10---DEMO-securité-v1](https://user-images.githubusercontent.com/58987553/71821856-881ab980-3093-11ea-8ae0-299b6dc8003a.jpg)

**Comment by GaelleOttan** [comment]
là c'est l'illustration pour le tuto/ entrainement avec un personne qui travaille près d’un Incendie? (et dont les deux choix seront 1. Je téléphone aux pompiers/ 2 : je prend une photo)
Si c'est le cas je trouve que c'est pas clair, on dirait qu'il y a deux images côte à côte qui n'ont pas de liens entre elles

**Comment by MatthieuMARTIN** [comment]
@GaelleOttan oui c'est bien cette illustration, le feu est sur le coté du bâtiment. le travailleur peint la face avant du bâtiment. 
Car je trouvais ça bizarre qu'il travaille vraiment à coté du feu en le voyant. La il ne s'est pas être pas encore rendu compte du feu.

**Comment by GaelleOttan** [comment]
C'est pas du tout clair là je trouve que ça donne vraiment l'impression que c'est deux images. Je pense qu'il faut plus de recul où on le voit peindre un batiment (plutôt que d'avoir un focus sur juste le mur) et le bâtiment de derrière prend feu. 
Je pense que le fait que les deux images ne soient pas dessinées avec la même finesse (la flamme on dirait que c'est plus un emoticone alors que le mec est hyper fini), ça brouille aussi la compréhension je pense

**Comment by etienneCharignon** [comment]
Si on voyais la scène depuis l'angle de la maison, comme si on était sur un carrefour par exemple. Depuis un point de vue où l'on vois le peintre et le feu et où l'on voit que le peintre ne vois pas le feu.

**Comment by MatthieuMARTIN** [comment]
oui merci @GaelleOttan et @etienneCharignon je refais une proposition dans la journée !

**Comment by MatthieuMARTIN** [comment]
La 2ème tentative ! 
Est ce que ça vous plait mieux ? 
Bonne fin de journée ;) 

![écran-10---DEMO-securité-v2](https://user-images.githubusercontent.com/58987553/71903853-49edca80-3165-11ea-9b82-342e4272c84f.jpg)

**Comment by MatthieuMARTIN** [comment]
Les 2 choix du tuto !!

![risques-Tuto-Appeler-pompier](https://user-images.githubusercontent.com/58987553/71999044-01a3da80-3241-11ea-876b-915ca47c1489.jpg)
![risques-Tuto-Prendre-une-photo](https://user-images.githubusercontent.com/58987553/71999046-01a3da80-3241-11ea-8178-2713a5ccdc24.jpg)
