### ISSUE TITLE
Consigne prévention

### ISSUE THREAD

**Issue by GaelleOttan** [betagouv/eva#667]
Réaliser la consigne de la situation prévention

**Comment by GaelleOttan** [comment]
@Alexis-Akinyemi @laurenehoutin il faudrait qu'on réflechisse à la consigne écrite et audio de prévention (probablement en deux temps comme sécurité avant et après l'entrainement)

**Comment by laurenehoutin** [comment]
**Avant entraînement :**

_Consigne identique situation sécurité :_

Commencez par écouter la consigne

Veuillez mettre vos écouteurs et suivre les consignes audio. 

Lancer la consigne.

_Consigne spécifique prévention :_

Dans cet exercice, vous allez de voir observer une scène sur laquelle des situations sont entourées. Il vous faudra dire si ces situations présentent un risque ou non. Pour cela, il vous suffira de cliquer sur les situations entourées et de choisir parmi un niveau de risque : situation pas du tout risquée (tout va bien), situation assez risquée, situation très risquée.

Commençons tout d’abord par un entraînement : cliquez sur la situation entourée sur cette image.

**Après entraînement :** 

Vous venez de réussir l’entraînement, bravo ! Vous allez maintenant pouvoir commencer l’exercice. Il vous faudra déterminer si des situations sont risquées ou non, et ce qu’il faut faire si les situations sont risquées.

A vous de jouer

**Comment by etienneCharignon** [comment]
Je ré-ouvre cette issue pour qu'elle serve aussi au suivi de la réalisation (ici l'intégration dans l'application de cette consigne).

**Comment by francois2metz** [comment]
Il nous faudrait également les version audio des consignes.

**Comment by GaelleOttan** [comment]
yes merci françois pour le rappel. @telohtrab il faut qu'on trouve un moment ensemble pour configurer mes micros pour que je puisse faire des enregistrements de meilleure qualité comme évoqué ensemble

**Comment by GaelleOttan** [comment]
**Consigne prévention texte conforme à l'audio envoyé sur slack le 30/01**

Dans cet exercice, vous allez devoir observer une scène sur laquelle des situations sont entourées. Il vous faudra cliquer sur chaque situation entourée et choisir un niveau de risque correspondant : situation pas du tout risquée (dans laquelle tout va bien), situation assez risquée, situation très risquée (dans laquelle une ou plusieurs personnes sont en danger). Vous devrez ensuite choisir parmi deux propositions comment agir face à chaque situation.
Commençons tout d’abord par un entraînement : cliquez sur la situation entourée sur cette image.

Consigne intermédiaire
Vous venez de réussir l’entraînement, bravo ! Vous allez maintenant pouvoir commencer l’exercice. Il vous faudra déterminer si les cinq situations entourées sont risquées ou non, et comment agir parmi les deux choix qui vous sont proposés.
