### ISSUE TITLE
Export Événements : On doit pouvoir calculer les intervals de temps à la seconde près

### ISSUE THREAD

**Issue by Alexis-Akinyemi** [betagouv/eva#674]
Lors de l'évolution récente pour ajouter la colonne "situation" dans l'export des événements d'une situation, on s'est retrouvé avec un format du type : 26/12/2019 12h27. Mais pour pouvoir calculer les intervals de temps à la seconde près, il faut revenir à un format avec les secondes comme par exemple : 2019-12-18 16:20:34 (comme c'était avant).

**Comment by etienneCharignon** [comment]
Salut @Alexis-Akinyemi,

J'ai reformulé l'issue pour mettre en évidence le besoin dans le titre et la proposition de solution dans la description. Dans ce que tu avais écrit, tu proposais de séparer les éléments de la date "année:mois:jours" par des ':' ce qui est très inhabituel. Est-ce que tu y tiens vraiment ? Et dans ce cas, pour quelle raison ?
