### ISSUE TITLE
Export Événements: pouvoir exporter tous les événements de la campagne de pannelling

### ISSUE THREAD

**Issue by Alexis-Akinyemi** [betagouv/eva#675]
Pour l'analyse il faut pouvoir grouper les événements par campagne, par évalué et par situation.

Aujourd'hui, on peut seulement extraire tous les événements pour période temps et on ne sais plus regrouper par utilisateur. Donc c'est insuffisant (c'est Étienne qui le dit).

Dans la pages des événements :
- [x] ajouter une colonne "Nom évalué"
- [x] ajouter une colonne "Campagne" 
- [ ] ajoute filtre sur le code campagne

**Comment by etienneCharignon** [comment]
Avec le déplacement des événements dans les campagne, le filtre est devenu inutile.   Par ailleurs, un refactoring est en cour sur le sujet qui est suivi par l'issue betagouv/eva-serveur#291


Je ferme cette issue.
