### ISSUE TITLE
[Admin] Page événements : dans les filtres, le datepicker de la date de fin ne devrait pas modifier le champ de la date de début

### ISSUE THREAD

**Issue by etienneCharignon** [betagouv/eva#676]
Le problème vient du fait que les deux champs on le même id html

**Comment by morissetcl** [comment]
Je n'ai pas réussi à reproduire le bug, à l'occasion si tu peux me le montrer.

**Comment by etienneCharignon** [comment]
Le problème est présent en prod mais pas en préprod

**Comment by shanser** [comment]
je ne constate plus le problème en prod de mon côté. Il y a eu un déploiement depuis. 

Le commit https://github.com/betagouv/eva-serveur/commit/9b1c3e0dd3c3bde6cd4254fefd359bb9b51dac03 a résolu le souci
