### ISSUE TITLE
Psycho: MES illettrisme partie 2 : complétion de phrases

### ISSUE THREAD

**Issue by Alexis-Akinyemi** [betagouv/eva#696]
**Principe : phrases à trous**
On doit livrer des cartons dans le parc 
- Un mot est maqué sur les cartons que l'on doit livrer ou les panneaux qui servent à nous guider 
- l'utilisateur doit cliquer sur le mot approprié parmi 4 propositions 

![Image d’iOS (1)](https://user-images.githubusercontent.com/20936092/72446198-5ef4da00-37b3-11ea-83bc-a99efbe5b6d7.jpg)

Note : "papa" est ici un "mauvais" exemple, une seule des propositions permettra, pour chaque essai, de former une phrase cohérente.

**Comment by Alexis-Akinyemi** [comment]
**Principe : phrases à trou**
On doit livrer des cartons dans le parc 
- Un mot est maqué sur les cartons que l'on doit livrer ou les panneaux qui servent à nous guider 
- l'utilisateur doit cliquer sur le mot approprié parmi 4 propositions 

![Image d’iOS (1)](https://user-images.githubusercontent.com/20936092/72446198-5ef4da00-37b3-11ea-83bc-a99efbe5b6d7.jpg)

**Comment by laurenehoutin** [comment]
**Modifications suite à la gamification**

*   Les propositions ci-après font suite aux décisions prises collectivement hier concernant la gamification.Problème : la proposition initiale (cartons et panneaux) rend la situation très scolaire et le but (identifier l'illettrisme) totalement transparent au fil des questions.
*   Solutions : Raconter une histoire permettant de masquer les questions ou les modalités de réponses dans des mises en contexte qui permettent de penser que l’on souhaite évaluer la bonne réaction dans le contexte donné, et non pas la pratique du français. L’histoire a donc un fil conducteur : le parcours du livreur dans le parc. Pour les essais les plus faciles, il est très difficile de ne pas rendre l’exercice scolaire sans parasiter la mesure, on a donc pris le parti de dispatcher au maximum pour qu’ils n’attirent pas trop l’attention. On fera un manipulation-check dans le test papier (Avez-vous découvert l’objectif de cet exercice ? Quel est il ? A quel moment avez-vous découvert l’objectif ?).
*   Layout : Dessin comportant 1 phrase à trou (PARTIE A) + propositions dont 1 à sélectionner sur la droite (PARTIE B).
*   … = signifie qu’un mot manque
*   Pour ajouter de la gamification, on conseille de mettre une carte du parc avec le bonhomme qui avance au fur et à mesure de la complétion de la MES.
*   Nous pensons que 16 images suffisent finalement, car c’est assez long.
*   nConnaissance&comprehension (CO&COM) = 9
*   nSynthaxe&Orthographe (S&O) = 7

Consigne de départ : 

_Vous êtes chargé.e des livraisons dans le parc. Vous devez effectuer les livraisons, mais vous rencontrez certaines contraintes : des mots sont par exemple effacés sur les colis, sur les pancartes qui vous indiquent le chemin, ou vous entendez mal vos interlocuteurs. Vous devez donc retrouver les mots manquants._


<table>
  <tr>
   <td>n° Essai
   </td>
   <td>Partie A
   </td>
   <td>Partie B
   </td>
   <td>Catégorie
   </td>
  </tr>
  <tr>
   <td colspan="3" ><strong><em>Début de la tournée</em></strong>
   </td>
   <td>
   </td>
  </tr>
  <tr>
   <td>1
   </td>
   <td><em>Pour commencer votre tournée, vous devez lire les instructions qui vous ont été laissées. </em>
<p>
<em>[Feuille tachée de café avec écrit : commencez votre tournée en livrant les colis de la pile de gauche. ... , il faut tous les livrer avant 12h !]</em>
   </td>
   <td><em>Quel texte est effacé ?</em>
<ul>

<li><em>Faites vite</em>

<li><em>Stop</em>

<li><em>Reculez</em>

<li><em>Eloignez-vous des bordures</em>
</li>
</ul>
   </td>
   <td>CO&COM
   </td>
  </tr>
  <tr>
   <td>2
   </td>
   <td><em>Après avoir chargé les colis dans votre camion, vous commencer à rouler pour effectuer votre livraison.</em>
<p>
<em>[Panneau de circulation avec : </em>
<p>
Vitesse ... à 30 km/h]
   </td>
   <td><em>Quel est le mot effacé ?</em>
<ul>

<li><em>Limité</em>

<li><em>Limitée</em>

<li><em>Limmitté</em>

<li><em>Limmittée</em>
</li>
</ul>
   </td>
   <td>S&O
   </td>
  </tr>
  <tr>
   <td colspan="3" ><strong><em>Le joueur arrive dans le parc et effectue la première livraison</em></strong>
   </td>
   <td>
   </td>
  </tr>
  <tr>
   <td>3
   </td>
   <td><em>Vous allez livrer votre premier colis. Voici les instructions.</em>
<p>
[Instructions sur le colis avec une partie mal imprimée : Déposer le colis au *** de poste]
   </td>
   <td><em>Quel est le mot effacé ?</em>
<ul>

<li><em>Bureau</em>

<li><em>Buro</em>

<li><em>Burreau</em>

<li><em>Burro</em>
</li>
</ul>
   </td>
   <td>S&O
   </td>
  </tr>
  <tr>
   <td>4
   </td>
   <td><em>Vous arrivez bureau de poste, et il y a un mot sur la porte.</em>
<p>
[Post-it sur la porte avec bout déchiré : Ne pas frapper à la porte, ou le chien va ....]
   </td>
   <td><em>Quel est le mot manquant ?</em>
<ul>

<li><em>Aboyer</em>

<li><em>Aboyé</em>

<li><em>Haboyer</em>

<li><em>Haboyé</em>

<li><em>Aboiyé</em>

<li><em>Aboiyer</em>
</li>
</ul>
   </td>
   <td>S&O
   </td>
  </tr>
  <tr>
   <td>5
   </td>
   <td><em>Vous remettez le carton à la postière du parc.</em>
<p>
[Sur un carton, étiquette rouge avec :
<p>
…, fragile]
   </td>
   <td><em>Quel est le mot qui a disparu ?</em>
<ul>

<li><em>Attention</em>

<li><em>Livré</em>

<li><em>Repère</em>
</li>
</ul>
   </td>
   <td>CO&COM
   </td>
  </tr>
  <tr>
   <td>6
   </td>
   <td><em>La postière vous invite à rester prendre le café.</em>
<p>
[Bulle : Vous voulez rester pour café ? On allait le boire en équipe]
<p>
<em>Vous répondez : Non, merci ***</em>
   </td>
   <td><em>Vous répondez :</em>
<ul>

<li><em>Monsieur</em>

<li><em>Madame</em>

<li><em>Vous</em>
</li>
</ul>
   </td>
   <td>CO&COM
   </td>
  </tr>
  <tr>
   <td colspan="3" ><strong><em>Le joueur va vers sa seconde livraison</em></strong>
   </td>
   <td>
   </td>
  </tr>
  <tr>
   <td>7
   </td>
   <td><em>Alors que vous sortez de la poste du parc, un visiteur du parc qui s’est perdu vous interpelle :</em>
<p>
[Bulle avec : Excusez-moi ... vous déranger.]
   </td>
   <td><em>Quel est le mot que vous n’avez pas bien entendu ?</em>
<ul>

<li><em>de</em>

<li><em>par</em>

<li><em>le</em>

<li><em>à</em>

<li><em>pour</em>
</li>
</ul>
   </td>
   <td>S&O
   </td>
  </tr>
  <tr>
   <td>8
   </td>
   <td><em>[Le même personnage, même image, dans la bulle : </em>... est le zoo, s’il vous plaît ? Je voudrais aller voir le repas des lions, il parait que c’est super !<em>]</em>
   </td>
   <td><em>Quel est le mot que vous n’avez pas bien entendu ?</em>
<ul>

<li><em>Où</em>

<li><em>Quand</em>

<li><em>Si</em>

<li><em>Quoi</em>

<li><em>Comment</em>
</li>
</ul>
   </td>
   <td>CO&COM
   </td>
  </tr>
  <tr>
   <td>9
   </td>
   <td><em>Vous regardez l’adresse sur le prochain colis.</em>
<p>
[Bureaux administratifs - Bureau 48
<p>
Consigne spéciale : Même si la livraison concerne le bureau 48, déposer le colis au bureau 49 à ***<em>]</em>
   </td>
   <td><em>Quel est le mot manquant ?</em>
<ul>

<li><em>Droite</em>

<li><em>Devant</em>

<li><em>Dehors</em>
</li>
</ul>
   </td>
   <td>CO&COM
   </td>
  </tr>
  <tr>
   <td>10
   </td>
   <td><em>Vous reprenez la route vers les bureaux administratifs. </em>
<p>
[ Vue depuis l’intérieur de la voiture, la voiture fait face à une barrière avec un panneau - mot caché par un pull laissé sur le panneau - : Entrée .... au public]
   </td>
   <td><em>Quel est le mot caché ?</em>
<ul>

<li><em>Indisponible</em>

<li><em>Interdite</em>

<li><em>Insoluble </em>
</li>
</ul>
   </td>
   <td>CO&COM
   </td>
  </tr>
  <tr>
   <td>11
   </td>
   <td><em>Vous déposez le colis au bureau 49. </em>
<p>
[Une personne avec une bulle : 
<p>
Bonjour ! Merci beaucoup, le colis est pour ma collègue mais elle est ..., alors je vais le garder jusqu’à son ...”
   </td>
   <td><em>Quels sont les mots qui manquent ?</em>
<ul>

<li><em>malade ; retour</em>

<li><em>absente ; malade</em>

<li><em>malade ; vacances </em>
</li>
</ul>
   </td>
   <td>CO&COM
   </td>
  </tr>
  <tr>
   <td colspan="3" ><strong><em>Le joueur arrive à la troisième livraison</em></strong>
   </td>
   <td>
   </td>
  </tr>
  <tr>
   <td>12
   </td>
   <td><em>Pour votre livraison au zoo, vous devez livrer plusieurs colis, ce qui pèse très lourd. Un employé vous propose son aide.</em>
<p>
[Bonjour ! Vous avez besoin d’aide ? Je peux vous aider à ... les cartons.]
   </td>
   <td><em>Quel est le mot que vous n’avez pas bien entendu ?</em>
<ul>

<li><em>Porter</em>

<li><em>Porté</em>

<li><em>Portez</em>

<li><em>Portais</em>

<li><em>Portait</em>
</li>
</ul>
   </td>
   <td>S&O
   </td>
  </tr>
  <tr>
   <td>13
   </td>
   <td><em>Après avoir ouvert la porte du zoo, l’employé qui vous accompagne fait une chute car un panneau  était en partie effacé.</em>
<p>
[Panneau en question : Attention … la marche.]
   </td>
   <td><em>Quel est le mot manquant sur ce panneau ?</em>
<ul>

<li><em>à</em>

<li><em>de</em>

<li><em>le</em>
</li>
</ul>
   </td>
   <td>S&O
   </td>
  </tr>
  <tr>
   <td>14
   </td>
   <td><em>Vous lisez la consigne sur un des colis.</em>
<p>
[ Consigne spéciale : Ces colis ***** de la viande pour les tigres, ne pas les déposer devant la cage.]
   </td>
   <td><em>Quel est le mot effacé ?</em>
<ul>

<li><em>Contiennent</em>

<li><em>Apprennent</em>

<li><em>Tiennent</em>

<li><em>Gère</em>
</li>
</ul>
   </td>
   <td>CO&COM
   </td>
  </tr>
  <tr>
   <td>15
   </td>
   <td>[Devant la cage des éléphants, à gauche une porte pour entrer dans la cage, à droite un chemin avec un message écrit au marqueur sur une feuille :
<p>
Pour contourner la cage, … par ici.]
   </td>
   <td><em>Quel est le mot effacé ?</em>
<ul>

<li><em>passez,</em>

<li><em>poussez,</em>

<li><em>palliez,</em>

<li><em>pacez.</em>
</li>
</ul>
   </td>
   <td>CO&COM
   </td>
  </tr>
  <tr>
   <td>16
   </td>
   <td><em>Vous remettez le colis à la personne au destinataire.</em>
<p>
[Bulle : Merci ! Puisque vous êtes là, pouvez-vous déposer ce colis au Grand ****, s’il vous plaît ? Je n’ai pas une minute à moi aujourd’hui !”
   </td>
   <td><em>Quel est le mot que vous n’avez pas entendu ?</em>
<ul>

<li><em>chateau</em>

<li><em>chapeau </em>

<li><em>chapiteau</em>

<li><em>chapitot</em>

<li><em>chariot </em>
</li>
</ul>
   </td>
   <td>S&O
   </td>
  </tr>
  <tr>
   <td colspan="3" ><strong><em>Fin</em></strong>
   </td>
   <td>
   </td>
  </tr>
</table>




*   **Métriques** : temps passé sur chaque écran + bonne / mauvaise réponse pour chaque écran = calcul à définir
*   **Entraînement** : Utilisation de deux écrans pour la partie entraînement : mesure du temps passé dans l’entraînement et du nombre d’écoutes de la consigne.

<table>
  <tr>
   <td>
Entraînement 1
   </td>
   <td>[Image du colis avec une tâche : 
<p>
Madame Dubois
<p>
Bureaux administratifs
<p>
7 ****** du zoo
<p>
0349183 Le Parc d’attraction]
   </td>
   <td><em>Quel est le mot manquant ?</em>
<ul>

<li><em>Boulevard</em>

<li><em>Rampe</em>

<li><em>Fort </em>

<li><em>Colis</em>
</li>
</ul>
   </td>
   <td>CO&COM
   </td>
  </tr>
  <tr>
   <td>Entraînement 2
   </td>
   <td>[Image du colis avec une tâche : 
<p>
Consigne de livraison
<p>
Pensez à ... la lumière en sortant de bâtiment]
   </td>
   <td><em>Quel mot mettre pour compléter la consigne de livraison ?</em>
<ul>

<li><em>Eteindre</em>

<li><em>Etaindre</em>

<li><em>Aitindre</em>
</li>
</ul>
   </td>
   <td>S&O
   </td>
  </tr>
</table>

**Comment by laurenehoutin** [comment]
Récap dessins : 
Feuille : 1
Panneaux : 2 - 10 - 13
Cartons : 3 - 5 - 9 - 14
Portes : 4 - 15
Personnages : 6 - 7 - 8 - 11 - 12 - 16 - 17

**Comment by GaelleOttan** [comment]
@laurenehoutin vous deviez pas changer le n°13 pour que l'on puisse réutiliser le panneau dessiné par matthieu (CAD vue depuis la voiture)?

**Comment by Alexis-Akinyemi** [comment]
Si elle a changé le 13 pour pourvoir réutiliser un autre dessin mais la porte, pas le panneau :)
![image](https://user-images.githubusercontent.com/20936092/73072604-b0891d00-3eb5-11ea-9acc-55d40c9709ac.png)

**Comment by MatthieuMARTIN** [comment]
![04-porte 1](https://user-images.githubusercontent.com/58987553/74428617-a70e2780-4e59-11ea-987b-09fcb4a00a20.jpg)
Le visuel a déjà été corrigé la dessus ! 
C'est MAJ sur le drive

**Comment by GaelleOttan** [comment]
ah ah @MatthieuMARTIN c'était un vieux commentaire d'alexis (du 20 janvier) ;)On attendait pas de modifs, à priori on est au clair sur ces dessins (jusqu'aux tests au moins)

**Comment by MatthieuMARTIN** [comment]
oups ^^

**Comment by GaelleOttan** [comment]
@MatthieuMARTIN je viens de m'apercevoir qu'il manque deux variantes de dessins pour l'entrainement: 

1. [Image du colis avec une tâche):

Madame Dubois
Bureaux administratifs du Parc d'attraction
7 ****** du zoo
97140 Parkville

2. [Image du colis avec une tâche et étiquette Consigne de livraison:
Pensez à ... la lumière en sortant de bâtiment

**Comment by GaelleOttan** [comment]
@MatthieuMARTIN tu as pu faire ces deux variantes de dessins vendredi?

**Comment by MatthieuMARTIN** [comment]
@GaelleOttan c'est fait ! 
Je met dans le drive ! 
![17-colis-5](https://user-images.githubusercontent.com/58987553/74645282-e5685700-5177-11ea-968e-635beb0ae6b9.jpg)
![18-colis-6](https://user-images.githubusercontent.com/58987553/74645284-e6998400-5177-11ea-8fc7-124b3cc7bcc6.jpg)

**Comment by GaelleOttan** [comment]
top @MatthieuMARTIN il y avait aussi cette erreur dans le texte, tu peux faire la modifs aussi? 
![Capture d’écran 2020-02-17 à 10 54 40](https://user-images.githubusercontent.com/48095868/74646387-0cc02380-517a-11ea-8995-66242e849281.png)

**Comment by MatthieuMARTIN** [comment]
Ok, c'est fait et c'est dans le drive !
![03-colis-1-2](https://user-images.githubusercontent.com/58987553/74647053-43e30480-517b-11ea-91c2-57d299d8b81a.jpg)

**Comment by GaelleOttan** [comment]
super merci beaucoup! J'ai tout retrouvé ;)
