### ISSUE TITLE
Design: MES illettrisme partie 2 : complétion de phrases

### ISSUE THREAD

**Issue by GaelleOttan** [betagouv/eva#702]
Produire les dessins pour pouvoir tester dans un premier temps en version papier (début février) avant de commencer à intégrer

en lien avec l'issue #696 qui reprend le contenu pédagogique affilié à cette MES

**Comment by GaelleOttan** [comment]
@MatthieuMARTIN  pour les dessins, il y a des ajustements pour la mise en situation livraison de colis. Côté robot à éduquer avec les mots en français, rien n'a évolué depuis mercredi, on reste sur le même dessin que celui discuté ensemble.
Pour le colis/ texte à trou, nous avons complexifié le scénario car c'était trop simpliste avec seulement deux contextes (un panneau et un colis), et nous en sommes arrivés à 5 dessins à dessiner pour cette MES:
Un dessin avec une feuille où un mot est caché par une tache de café (pour la tache 1)
Un panneau dessiné où un mot est effacé avec une vue depuis le volant d'une voiture (tache 2, 10 et 13)
Un dessin de carton/ colis avec une étiquette que l'on fera légèrement varier (une normale, une avec un contour rouge, une avec la mention 'Consigne spéciale' (tache 3, 5, 9 et 14)
Une porte sur laquelle un post-il est collé avec une variante où le contexte de fond est une maison, et une autre où le contexte de fond est des barreaux d'une cage (tache 4 et 15)
Une scène de discussion avec le livreur qui parle avec une personne de face (avec quelques variantes où l'on changerait le tee-shirt la coiffure et le fond)

**Comment by MatthieuMARTIN** [comment]
ça marche ! je travaillerai sur tout ça toute la journée de demain, et je mettrai les première images ici ! 
A très vite,

**Comment by MatthieuMARTIN** [comment]
Mes 2 premières propositions ! 

![écran-12-panneaux-1](https://user-images.githubusercontent.com/58987553/72826571-60be1200-3c79-11ea-83e8-8c1f9821beb0.jpg)
![écran-14-colis-1](https://user-images.githubusercontent.com/58987553/72826572-60be1200-3c79-11ea-8ca4-bd1d49b199bc.jpg)

**Comment by GaelleOttan** [comment]
ça me semble bien @MatthieuMARTIN! juste deux remarques: 
> Sur le panneau, je rajouterais "à" pour avoir une phrase totalement française (même si c'est pas exactement conforme au panneau): Pour votre sécurité, vitesse xxx à 30"
> Sur le carton je grossirais l'étiquette (ou je ferais un zoom plus sur le carton) car ça me semble petit à lire...  
Tu continues aujourd'hui pour les autres dessins (ou pour les différentes variantes de ceux là)?

**Comment by laurenehoutin** [comment]
Panneau : 

RAS, nickel 

Colis : 

- Le mot colis est un peu trop visible je trouve. D'ailleurs, on peut deviner le mot manquant avec la longueur donc ça serait cool de mettre ce qui vient après le mot colis à la ligne avec une zone beaucoup plus effacée (dont on distingue moins où ça commence et où ça se termine).

- Alexis préfèrerait que ce soit plus zoomé avec une étiquette qui fasse plus colis, j'en mets une juste après

**Comment by laurenehoutin** [comment]
![image](https://user-images.githubusercontent.com/56107558/72881629-67906780-3d01-11ea-9631-92155ef4c925.png)

**Comment by GaelleOttan** [comment]
hum il me semble que ça complique l'exercice (et crée des biais) d'avoir autant d'info texte sur l'étiquette, non? et ça rend difficile de voir à quel endroit est le texte que l'on doit compléter

**Comment by Alexis-Akinyemi** [comment]
Effectivement, l'idée est simplement d'avoir la notion de "commentaire" ou "consigne" de livraison pour rendre le contexte compréhensible, pas de mettre toute le contenu de cette étiquette. Ca n'introduira pas de biais particulier si c'est standard. Mais si ça complique trop on peut simplement mettre cet élément de contexte dans la consigne orale.

**Comment by GaelleOttan** [comment]
du coup @Alexis-Akinyemi  concrètement, je ne vois pas ce que tu veux visuellement. Tu peux reprendre l'étiquette que lauren a mise en exemple et enlever les parties qui ne doivent pas être sur l'étiquette?

**Comment by telohtrab** [comment]
Hello, 

Pour info, cette MES illetrisme va reprendre la même maquette que Bureau. Donc si possible, pense bien à prévoir cette zone à droite pour la carte blanche :)

![image](https://user-images.githubusercontent.com/7781917/72889349-cceb5500-3d0f-11ea-9c1d-f2c530da9156.png)

**Comment by MatthieuMARTIN** [comment]
J'ai passé le panneau à gauche suite à ta remarque @telohtrab  ! On décalera aussi le carton et tout le reste. 
Et le "à" a été rajouté pour @GaelleOttan  ;)

![écran-12-panneaux-1-v2](https://user-images.githubusercontent.com/58987553/72905974-b2c26e80-3d31-11ea-9f99-c4b0a15eebed.jpg)

**Comment by MatthieuMARTIN** [comment]
2 de plus vous sont proposés ! 

![écran-15-porte-1](https://user-images.githubusercontent.com/58987553/72916099-ab0ac600-3d41-11ea-8a97-6873773f619f.jpg)
![écran-16-personne-1](https://user-images.githubusercontent.com/58987553/72916100-ab0ac600-3d41-11ea-8a64-922c27f488be.jpg)

**Comment by laurenehoutin** [comment]
Hey, super !
Par contre, je ne suis pas sure qu'on puisse utiliser l'identité de laposte. Du coup je mettrais plus un truc genre "bureau de poste du parc"
+ le bras de la femme est coupé par la forme

**Comment by MatthieuMARTIN** [comment]
ça marche ! la forme qui coupe le bras c est l'écran de son ordi mais oui autant l'enlever !

**Comment by laurenehoutin** [comment]
Ah excuse moi !

**Comment by Alexis-Akinyemi** [comment]
Pour le carton, je précise un peu mon retour, l'idée est simplement d'avoir du contexte : expéditeur / destinataire / des adresses bateau  ("zoo", etc) et "commentaire pour la livraison" comme ici. 
![etiquette](https://user-images.githubusercontent.com/20936092/72917901-f8d4fd80-3d44-11ea-839f-01bd3ca15c2e.png)

**Comment by GaelleOttan** [comment]
@Alexis-Akinyemi c'est pas clair de comment on met en avant la phrase à trou là dedans, comme ça? Et qu'est ce qui cache le mot? Le bout de l'étiquette arrachée? 
![20200122_185145](https://user-images.githubusercontent.com/48095868/72919764-59196e80-3d48-11ea-8650-bf22634b90cb.jpg)

**Comment by Alexis-Akinyemi** [comment]
Le mot masqué est dans "commentaire pour la livraison" (ce qui remplace "consigne spéciale de livraison" dans le tableau du contenu). Pour la taille effectivement il faut que le commentaire soit mis en évidence. Peut-être d'ailleurs que le reste de l'étiquette peut-être fait en tout petit pour donner l'impression d'un zoom.
Si tout ceci est irréalisable, on donnera les infos en contexte à l'oral, ça ira. 
Pour le mot masqué, l'aspect rayé ou déchiré est très bien. Si c'est faisable on peut aussi  partir sur l'effet "tâche d'encre causée par la pluie"

**Comment by GaelleOttan** [comment]
@MatthieuMARTIN je viens de faire le point pour la suite: 
1/ Il ne reste qu'un dessin complet à faire: la feuille où un mot est caché par une tache de café 
2/ des petites modifs sur les images existantes (supprimer la marque la poste, enlever l'écran d'ordinateur qui coupe le bras, et faire l'étiquette changer l'étiquette sur le carton)
3/ les ajouts pour les variantes: 
- Panneau de circulation: faire une image de plus où c'est un pull qui cache le texte sur le panneau de circulation (n10)
- Carton/ colis: si tu peux rajouter sur la version de base une étiquette comme proposé ci dessus dans mon dessin et prenant en compte les commentaires d'alexis (CAD mettre en plus petit les cases expéditeur et adresse de livraison pour que la case commentaire sur la livraison ressorte mieux) + faire une image de plus avec une variante "Consigne spéciale" à la place de "commentaire sur la livraison + faire une variante avec une étiquette supplémentaire "attention colis fragile" (n5)
- La porte: faire la variante avec le fond qui est celui d'une cage à la place du mur (n15)
- scène de discussion: un personnage avec une autre coiffure et teeshirt avec pour fond le parc  (faire en deux version pour n8, n12), une personne avec une chemise et une autre couleur de cheveux (faire en deux version pour n11 et 16)

Tu penses pouvoir rebosser dessus quand? Merci!

**Comment by MatthieuMARTIN** [comment]
@GaelleOttan ça marche merci pour ce point, je rebosse dessus lundi ! :)

**Comment by GaelleOttan** [comment]
Merci beaucoup @MatthieuMARTIN. Je suis dispo toute la journée par slack ou tel si tu as des interrogations sur certains ajustements/ variantes

**Comment by MatthieuMARTIN** [comment]
@GaelleOttan ça marche ! :)

**Comment by MatthieuMARTIN** [comment]
MAJ des images avec les modifs : 

![écran-14-colis-2](https://user-images.githubusercontent.com/58987553/73176516-ed028600-410c-11ea-8e3c-b82eac0cdd3a.jpg)
![écran-15-porte-2](https://user-images.githubusercontent.com/58987553/73176518-ed028600-410c-11ea-906a-6c35bcad309c.jpg)
![écran-16-personne-2](https://user-images.githubusercontent.com/58987553/73176519-ed028600-410c-11ea-8285-3e88b9aa5fa5.jpg)
![écran-12-panneaux-1-v2](https://user-images.githubusercontent.com/58987553/73176520-ed9b1c80-410c-11ea-8c23-ebc484f213b8.jpg)

**Comment by MatthieuMARTIN** [comment]
Les 4 cartons : 
![écran-14-colis-1 2](https://user-images.githubusercontent.com/58987553/73179070-dfe89580-4112-11ea-8423-a73ef90453fa.jpg)
![écran-14-colis-2-1](https://user-images.githubusercontent.com/58987553/73179071-dfe89580-4112-11ea-8d7e-be431d5936d7.jpg)
![écran-14-colis-3-1](https://user-images.githubusercontent.com/58987553/73179073-dfe89580-4112-11ea-8d5c-d93f770c1e34.jpg)
![écran-14-colis-4-1](https://user-images.githubusercontent.com/58987553/73179074-e0812c00-4112-11ea-9350-bc622ff9048c.jpg)

**Comment by MatthieuMARTIN** [comment]
et 2 nouveaux écran : 

![écran-17-feuille-taché-1](https://user-images.githubusercontent.com/58987553/73181396-6b642580-4117-11ea-96ba-df621731dfb1.jpg)
![Uploading panneaux-2-1.jpg…]()

**Comment by telohtrab** [comment]
Merci Matthieu ! J'aurais besoin que tu mettes ça sur le Drive, numéroté dans le sens des questions, sinon je ne vais pas m'y retrouver ^^

**Comment by MatthieuMARTIN** [comment]
@telohtrab c est fait ! Et numéroté dans le sens des questions , 
ici : 
![image](https://user-images.githubusercontent.com/58987553/73189413-a28d0380-4124-11ea-8477-840b88b195f2.png)

**Comment by telohtrab** [comment]
Merci beaucoup
*Benjamin Bartholet*
*designer & technologist*
http://benjaminbartholet.fr - @telohtrab <http://twitter.com/telohtrab>


Le lun. 27 janv. 2020 à 16:47, MatthieuMARTIN <notifications@github.com> a
écrit :

**Comment by GaelleOttan** [comment]
@telohtrab je ne suis pas certaine que ce soit très évident pour matthieu  les numéros de chaque image puisqu'il a surtout fait les dessins que je lui ai décris. La meilleure manière de reconstituer  le scénario est avec l'issue psycho qui est ici: 
https://github.com/betagouv/eva/issues/696
Si matthieu identifie chaque image dans le drive par un numéro, je pourrais te les remettre dans l'ordre et faire les correspondance avec le scénario des questions si c'est trop chronophage pour toi

**Comment by MatthieuMARTIN** [comment]
@GaelleOttan si ça me va bien par ordre des questions pour la nomenclature ! pas de soucis :)

**Comment by telohtrab** [comment]
Non mais après je peux me débrouiller, mais juste en remettant les numéros
de questions ça ira un peu plus vite que si je cherche pour chaque import
d'image dans le design et pour retrouver les phrases correspondantes.

Je suis sur mon laptop donc j'ai pas Toshop, possible de me faire des
exports JPG ?

*Benjamin Bartholet*
*designer & technologist*
http://benjaminbartholet.fr - @telohtrab <http://twitter.com/telohtrab>


Le lun. 27 janv. 2020 à 16:48, GaelleOttan <notifications@github.com> a
écrit :

**Comment by MatthieuMARTIN** [comment]
@telohtrab  je t'ai mis les jpeg !

**Comment by telohtrab** [comment]
Je ne trouve pas l'image correspondant à cette question, le tableau ici est toujours à jour ? 

https://github.com/betagouv/eva/issues/696
 
![image](https://user-images.githubusercontent.com/7781917/73193559-0ca8a700-412b-11ea-811f-b46b83d0dc23.png)

**Comment by Alexis-Akinyemi** [comment]
En ce qui nous concerne avec Laurène c'est top pour la "cover story". 
J'aurais simplement tendance à dire qu'on ne comprend pas bien l'étiquette effacée par la pluie. Tu peux peut-être augmenter la surface de carton mouillé ou mettre des gouttes sur le scotch comme ici : 
![image](https://user-images.githubusercontent.com/20936092/73193771-61e4b880-412b-11ea-985b-88f24936e0ce.png) ?
Vraiment top sinon !

**Comment by telohtrab** [comment]
Je rebondis sur ma question précédente, mon souci est que sur l'image ce n'est pas "Bureau" qui est effacé, mais "Colis"

**Comment by telohtrab** [comment]
![image](https://user-images.githubusercontent.com/7781917/73194247-2eeef480-412c-11ea-9a3e-1f1e55f71d7c.png)

**Comment by GaelleOttan** [comment]
@Alexis-Akinyemi @laurenehoutin c'est important que ce soit précisément le mot bureau ou est ce que l'on peut faire avec colis? Matthieu s'est trompé dans le mot à effacer

**Comment by laurenehoutin** [comment]
Hello,
Non non pas de problème :)

**Comment by telohtrab** [comment]
J'aurais donc besoin des variantes de colis pour la réponse ;)

**Comment by telohtrab** [comment]
![image](https://user-images.githubusercontent.com/7781917/73194837-17fcd200-412d-11ea-981d-a5dd082591ba.png)
@MatthieuMARTIN J'ai un souci pour la bulle sur cette image comme tu peux voir. Je pense que tu peux faire une bulle plus petite, avec des coins arrondis et est-ce que tu peux utiliser la Work Sans ou la Quicksand en utilisant le bleu très foncé des typos habituelles pour être plus raccord ? (Code du bleu : 1E416A)

**Comment by telohtrab** [comment]
Je ne trouve pas l'image pour cette question également :

![image](https://user-images.githubusercontent.com/7781917/73195360-049e3680-412e-11ea-9db2-4cb510e4b5c5.png)

**Comment by GaelleOttan** [comment]
@telohtrab matthieu n'a pas encore terminé toutes les variantes de dessin!

**Comment by telohtrab** [comment]
Haha désolé, j'avais pourtant bien reparcouru le fil, je n'avais pas compris ça. Mea Culpa !

**Comment by telohtrab** [comment]
J'intègre ce qui est prêt alors.

**Comment by telohtrab** [comment]
Voici l'intégration en l'état ! :)

![LivraisonConsigne](https://user-images.githubusercontent.com/7781917/73197375-7035d300-4131-11ea-8703-b2c57aa30ae7.png)
![Livraison1](https://user-images.githubusercontent.com/7781917/73197376-7035d300-4131-11ea-91ff-123b7d38fd22.png)
![Livraison2](https://user-images.githubusercontent.com/7781917/73197377-70ce6980-4131-11ea-848b-8f6dbeeddc5f.png)
![Livraison3](https://user-images.githubusercontent.com/7781917/73197378-70ce6980-4131-11ea-9e41-d2eaf3d30c87.png)
![Livraison4](https://user-images.githubusercontent.com/7781917/73197350-6c09b580-4131-11ea-818a-dc4df0d942ef.png)
![Livraison5](https://user-images.githubusercontent.com/7781917/73197352-6ca24c00-4131-11ea-8b24-a4ffdf204179.png)
![Livraison6](https://user-images.githubusercontent.com/7781917/73197355-6ca24c00-4131-11ea-9ce4-a06df41338b0.png)
![Livraison7](https://user-images.githubusercontent.com/7781917/73197357-6d3ae280-4131-11ea-8809-2b975ed66aa1.png)
![Livraison8](https://user-images.githubusercontent.com/7781917/73197358-6d3ae280-4131-11ea-8424-222d376d02ab.png)
![Livraison9](https://user-images.githubusercontent.com/7781917/73197360-6dd37900-4131-11ea-9ba6-44a8af445ae9.png)
![Livraison10](https://user-images.githubusercontent.com/7781917/73197361-6e6c0f80-4131-11ea-8b4c-376fef9b9839.png)
![Livraison11](https://user-images.githubusercontent.com/7781917/73197363-6e6c0f80-4131-11ea-9dae-3caff149dd43.png)
![Livraison12](https://user-images.githubusercontent.com/7781917/73197365-6f04a600-4131-11ea-85d5-43909ceb45ba.png)
![Livraison13](https://user-images.githubusercontent.com/7781917/73197367-6f04a600-4131-11ea-9e71-a9b401a062e9.png)
![Livraison14](https://user-images.githubusercontent.com/7781917/73197369-6f9d3c80-4131-11ea-882f-a3b35d0f88ec.png)
![Livraison15](https://user-images.githubusercontent.com/7781917/73197372-6f9d3c80-4131-11ea-90a5-c385d444b7fb.png)
![Livraison16](https://user-images.githubusercontent.com/7781917/73197374-7035d300-4131-11ea-99bc-4f70bc7eab01.png)

**Comment by MatthieuMARTIN** [comment]
Coucou, 
3 nouvelles images + modifs sur la bulle de "06 - personne".
J'ajoute et je MAJ aussi sur le drive tout ça  @telohtrab 

![15-porte-2](https://user-images.githubusercontent.com/58987553/73366089-a5ffc680-42ad-11ea-9fc8-b384237e8613.jpg)
![06-personne-1](https://user-images.githubusercontent.com/58987553/73366090-a5ffc680-42ad-11ea-8c9e-240a682b569e.jpg)
![07-personne-2](https://user-images.githubusercontent.com/58987553/73366092-a5ffc680-42ad-11ea-9951-13258f2042e9.jpg)
![13-panneaux-3](https://user-images.githubusercontent.com/58987553/73366093-a6985d00-42ad-11ea-8eee-7d024b22d4e9.jpg)

**Comment by etienneCharignon** [comment]
"vous voulez rester pour un café ?" Il me semble qu'il faut retirer un mot, sinon c'est trop facile 😆.

**Comment by etienneCharignon** [comment]
Vous êtes sûr pour le panneau de la circulation qui indique de faire attention à une marche après une porte ? C'est quand même rare comme message pour une voiture.

**Comment by GaelleOttan** [comment]
@laurenehoutin @Alexis-Akinyemi il n'y avait pas que pour moi que la question 13 n'était pas claire dans sa réécriture (en référence avec ma question posée dans #696 ;)
Du coup A&L, est ce que l'on peut imaginer changer le texte de la 13 pour coller au dessin fait par matthieu?

**Comment by Alexis-Akinyemi** [comment]
Effectivement l'idée était de réutiliser le dessin de la poste plutôt que celui de la route,
On peut changer le texte pour un "attention à la barrière après le portail" mais ça élève un peu la difficulté (barrière / portail moins courants que marche/porte). Ca n'est pas gênant jusqu'à preuve du contraire, les tests nous diront ce changement déséquilibre la tâche.

**Comment by GaelleOttan** [comment]
et sinon attention au piétons après le portail?

**Comment by Alexis-Akinyemi** [comment]
Le problème c'est que ça change la question du coup. L'idéal serait de garder cette question sur le a/à

**Comment by GaelleOttan** [comment]
Ok alors on part sur "attention à la barrière après le portail" et on ajustera en fonction des tests. 
pour le café proposé par la postière, c'est pas évident d'intégrer une bulle de réponse si on ne voit pas le personnage. est ce que c'est ok si on garde l'image comme dessiné et que dans l'interface à droite on mette: 

La postière vous invite à rester prendre le café.
Vous répondez : Non, merci ***
- Madame
- Monsieur
- Vous

**Comment by laurenehoutin** [comment]
Oui très bien !

**Comment by GaelleOttan** [comment]
@MatthieuMARTIN du coup un récap, on voit le bout ;)
- Pour l'image en voiture avec le panneau attention, il faudrait changer le texte dans le panneau pour: "Attention à la barrière après le portail"<

Ensuite il reste
- Vignette 8: même image que la vignette 7 avec le perso avec le bonnet mais nouveau texte "... est le zoo, s’il vous plaît ? Je voudrais aller voir le repas des lions, il parait que c’est super ! 
- Vignette 11: Une variante de ton dessin avec le perso derrière un bureau mais avec un nouveau style de perso autre couleur de fond du bureau (plus environnement bureau avec ordinateur et chaise... que desk de service). La bulle de texte: "Bonjour ! Merci beaucoup, le colis est pour ma collègue mais elle est ..., alors je vais le garder jusqu’à son ...”
- Vignette 12: Une scène avec un perso plutôt en habit de travail (un employé du zoo, et si possible un homme) avec une bulle "Bonjour ! Vous avez besoin d’aide ? Je peux vous aider à ... les cartons."
- Vignette 16: Une variante de la vignette 12 où le perso tend les bras car il a récupéré un paquet 
et bit dans la bulle : "Merci ! Puisque vous êtes là, pouvez-vous déposer ce colis au Grand ..., s’il vous plaît ? Je n’ai pas une minute à moi aujourd’hui !”

**Comment by telohtrab** [comment]
![Livraison1](https://user-images.githubusercontent.com/7781917/73762606-afd36f00-4770-11ea-967d-3400924c17dd.png)
![Livraison2](https://user-images.githubusercontent.com/7781917/73762608-afd36f00-4770-11ea-8b24-c1aa43f566e1.png)
![Livraison3](https://user-images.githubusercontent.com/7781917/73762609-b06c0580-4770-11ea-8034-0449beeccc2d.png)
![Livraison4](https://user-images.githubusercontent.com/7781917/73762610-b06c0580-4770-11ea-9782-e60f6b341a78.png)
![Livraison5](https://user-images.githubusercontent.com/7781917/73762612-b06c0580-4770-11ea-8404-95deb2025261.png)
![Livraison6](https://user-images.githubusercontent.com/7781917/73762652-b82baa00-4770-11ea-81ae-16b7ea04d2d7.png)
![Livraison7](https://user-images.githubusercontent.com/7781917/73762653-b82baa00-4770-11ea-9d24-d79a3acedc96.png)
![Livraison8](https://user-images.githubusercontent.com/7781917/73762655-b82baa00-4770-11ea-9798-606c3f84026b.png)
![Livraison9](https://user-images.githubusercontent.com/7781917/73762656-b82baa00-4770-11ea-9f1e-17f099c02bd3.png)
![Livraison10](https://user-images.githubusercontent.com/7781917/73762658-b82baa00-4770-11ea-990b-fc8df187e520.png)
![Livraison11](https://user-images.githubusercontent.com/7781917/73762678-bc57c780-4770-11ea-9ab6-3bf6e023eeec.png)
![Livraison12](https://user-images.githubusercontent.com/7781917/73762679-bc57c780-4770-11ea-85fc-941e9ebd5358.png)
![Livraison13](https://user-images.githubusercontent.com/7781917/73762680-bc57c780-4770-11ea-8250-361be8522568.png)
![Livraison14](https://user-images.githubusercontent.com/7781917/73762681-bc57c780-4770-11ea-83d6-27fcba9e73e7.png)
![Livraison15](https://user-images.githubusercontent.com/7781917/73762682-bcf05e00-4770-11ea-901d-8df7c43a8b58.png)
![Livraison16](https://user-images.githubusercontent.com/7781917/73762683-bcf05e00-4770-11ea-844b-495b9de08895.png)
![LivraisonConsigne](https://user-images.githubusercontent.com/7781917/73762684-bcf05e00-4770-11ea-847a-c6360679d790.png)


Hello, 

Voici les images mises à jour dans les maquettes. 
Je relève la 12 et la 16, mais je pense qu'elle ne sont pas encore faites.

Par ailleurs, le panneau sur la cage passe sous la carte blanche sur la question 15. 

Je ne relève pas de souci particuliers sur toutes les autres images :)

**Comment by MatthieuMARTIN** [comment]
Voici les nouvelles images du jour / c'est sur le drive !  
![08-personne-3](https://user-images.githubusercontent.com/58987553/73763784-36d51700-4772-11ea-8a28-bab1bbe58227.jpg)
![11-personne-4](https://user-images.githubusercontent.com/58987553/73763785-36d51700-4772-11ea-9ff6-c576c712d287.jpg)
![12-personne-4](https://user-images.githubusercontent.com/58987553/73763787-36d51700-4772-11ea-9cdd-8d34aea3efa6.jpg)
![13-panneaux-3](https://user-images.githubusercontent.com/58987553/73763812-42284280-4772-11ea-9a59-c13d40b8348f.jpg)

**Comment by telohtrab** [comment]
Quelle synchro !
Voici donc la 12 qu'il me manquait, tu as la 16 en route ?

![image](https://user-images.githubusercontent.com/7781917/73764845-e9f24000-4773-11ea-9231-e6818e2f404b.png)

**Comment by MatthieuMARTIN** [comment]
@telohtrab ouép la 16 ce sera pour demain !

**Comment by telohtrab** [comment]
Le texte de la 12 a changé ? ça ne correspond pas à l'image

**Comment by MatthieuMARTIN** [comment]
La dernière image est faite et sur le drive !

**Comment by GaelleOttan** [comment]
@MatthieuMARTIN je ne sais pas si tu as aussi pu modifier suite à la demande de Benjamin -> Par ailleurs, le panneau sur la cage passe sous la carte blanche sur la question 15.

**Comment by MatthieuMARTIN** [comment]
En effet merci, pour la 15 c'est corrigé à l'instant ! je met sur le drive.
![15-porte-2](https://user-images.githubusercontent.com/58987553/73850778-a4de1480-482c-11ea-8d1b-9a4d39a74101.jpg)

**Comment by telohtrab** [comment]
@MatthieuMARTIN J'ai toujours un souci de texte sur l'image du 12 :)

**Comment by MatthieuMARTIN** [comment]
@telohtrab Ah oui ! Voila ! c'est bon comme ça ? Je met sur le drive. 
![12-personne-4](https://user-images.githubusercontent.com/58987553/74327310-3b11bd80-4d8c-11ea-930e-4c13ea851f4a.jpg)
