### ISSUE TITLE
Design: MES illettrisme partie 1 : compréhension des mots français

### ISSUE THREAD

**Issue by GaelleOttan** [betagouv/eva#703]
Comme convenu mercredi 15 janvier à UT7, faire le dessin du robot qui affiche les mots à classer
![image](https://user-images.githubusercontent.com/48095868/72743248-94cb0180-3bab-11ea-910a-8e21bdb85ea3.png)

**Comment by MatthieuMARTIN** [comment]
Et ma proposition pour le robot ! 

![écran-11-illettrisme-classement-des-mots-2](https://user-images.githubusercontent.com/58987553/72826659-8b0fcf80-3c79-11ea-8d56-ef4cff75de10.jpg)
![écran-11-illettrisme-classement-des-mots-1](https://user-images.githubusercontent.com/58987553/72826660-8b0fcf80-3c79-11ea-9a42-b710e622b356.jpg)

**Comment by telohtrab** [comment]
Merci ! Voici comment j'envisageais l'intégration du coup : **
![image](https://user-images.githubusercontent.com/7781917/72830632-67508780-3c81-11ea-895b-65e0c396dffe.png)
**

**Comment by GaelleOttan** [comment]
Je trouve que visuellement c'est moins clair dessiné par matthieu rouge pas bon/ vert bon. Si on ne sait pas lire (ce que l'on mesure) le orange et le bleu avec le texte c'est difficile.

**Comment by telohtrab** [comment]
On ne peut pas vraiment faire sans "mot français" "mot pas français" à mon avis. Qu'est ce qui te gêne dans les couleurs sur ma version ? J'ai volontairement utilisé autre chose que du bleu et du vert justement.

**Comment by GaelleOttan** [comment]
je trouve que justement c'est pas intuitif avec ces couleurs, et pas adapté d'avoir du texte sur les bouton alors que précisément on ne sait pas si les gens seront capable de les lire
@Alexis-Akinyemi @laurenehoutin votre avis?

**Comment by laurenehoutin** [comment]
Pour nous : Rouge / Vert + Pas français / français. 
En fait il faut permettre que ce soit intuitif car on mesure du temps de réaction, et si les gens doutent (si ils oublient à quoi correspondent les flèches), il faut qu'ils puissent trouver l'information très vite.

**Comment by GaelleOttan** [comment]
Autre interrogation: est-ce que le fait que ce soit des formats de boutons (comme les autres interaction où les utilisateurs doivent cliquer) ça ne gène pas trop dans ce cas où, précisément, on ne veut pas que les gens cliquent mais qu'ils utilisent les touches de flèche du clavier?

**Comment by Alexis-Akinyemi** [comment]
C'est un peu problématique mais on avait fait ce choix là pour la compatibilité avec les tablettes.
J'ai l'impression que ça ouvre plein de questions qui peuvent largement attendre les premiers test pour un impact minime sur le design.
Vu que les boutons sont plus rapprochés que dans les tâches classiques, on est pas non plus certains que cette précaution de "ne pas cliquer mais utiliser les touches pour une réponse plus automatique" soit toujours pertinente. A voir pendant les tests donc
Se posera aussi la question des différences de scores en fonction du support : si les scores sont, au final, plus harmonieux entre tablette et PC lorsque les gens cliquent, on pourra revenir sur un système de clic.
Et quoiqu'il arrive le design sur lequel on part restera la meilleure solutions quelque soit le système car il est clair, proche des versions scientifiques de la tâche et permet une action rapide ...

Si rien ne change, on devra peut-être effectivement trouver un format qui fasse moins bouton, mais qui permettre de comprendre tout de même facilement où on doit cliquer sur tablette.

**Comment by GaelleOttan** [comment]
Donc en conclusion, la meilleure solution pour vous est: le design de benjamin avec la couleur rouge et verte?

**Comment by GaelleOttan** [comment]
du coup @MatthieuMARTIN tu peux enlever les flèches (désolée pour la mauvaise info donnée hier) et pour éviter que ça fasse vide tu peux finir le buste avec une forme moins carré du type 
![image](https://user-images.githubusercontent.com/48095868/72885002-5ea29480-3d07-11ea-8cdb-bad60ffcae87.png)

**Comment by MatthieuMARTIN** [comment]
ça roule !

**Comment by telohtrab** [comment]
![image](https://user-images.githubusercontent.com/7781917/72887542-36696480-3d0c-11ea-9ecc-01c67e6ebe46.png)

**Comment by MatthieuMARTIN** [comment]
Merci pour vos retours, 
Voila du coup ce que je propose :) 
![écran-11-illettrisme-classement-des-mots-3](https://user-images.githubusercontent.com/58987553/72903396-6bd27a00-3d2d-11ea-8635-71fd6c49f8f9.jpg)

**Comment by GaelleOttan** [comment]
ça me semble super bien @MatthieuMARTIN :)

**Comment by MatthieuMARTIN** [comment]
Super je le met sur le drive pour les dev !

**Comment by etienneCharignon** [comment]
@MatthieuMARTIN merci de nous indiquer le nom de la police que tu as utilisé

**Comment by MatthieuMARTIN** [comment]
@etienneCharignon ah oui si vous voulez gardez cette typo c'est : 
"SquareFont"

je l'ai téléchargé ici : 
https://www.dafont.com/fr/squarefont.font

**Comment by GaelleOttan** [comment]
@telohtrab le dessin de matthieu est terminé, tu peux finaliser le design d'interface dessus?

**Comment by telohtrab** [comment]
C'est prévu pour cet Apres'm oui !

Le lun. 27 janv. 2020 à 11:04, GaelleOttan <notifications@github.com> a
écrit :

**Comment by telohtrab** [comment]
![MES_Master-1](https://user-images.githubusercontent.com/7781917/73187643-019d4900-4122-11ea-8afd-f420020e29b8.png)
![MES_Master-2](https://user-images.githubusercontent.com/7781917/73187644-019d4900-4122-11ea-8460-be0416a60cf5.png)
![MES_Master](https://user-images.githubusercontent.com/7781917/73187645-0235df80-4122-11ea-97d5-480cd1b1c8cc.png)

Voici l'équivalent avec l'interface intégrée. On a pas beaucoup discuté du parcours "autour" mais j'imagine qu'on aura un tuto et peut-être un écran de fin. à dispo

**Comment by telohtrab** [comment]
Tout se trouve sur le Drive, et sur le Figma dans l'onglet Détection de l'illetrisme

**Comment by GaelleOttan** [comment]
Les écrans avec le contours de couleur c'est quand on a la souris/ lorsqu'on clique dessus? 
Il faudrait en effet qu'on cale l'ensemble du parcours avec A&L

**Comment by telohtrab** [comment]
Oui, pour moi c'est un comportement (furtif surement) qui n'apparaît que
quand on appuie sur la touche.

*Benjamin Bartholet*
*designer & technologist*
http://benjaminbartholet.fr - @telohtrab <http://twitter.com/telohtrab>


Le lun. 27 janv. 2020 à 16:47, GaelleOttan <notifications@github.com> a
écrit :

**Comment by etienneCharignon** [comment]
J'ai une question : Est-ce que les boutons sont vraiment des boutons (sont-ils cliquables) ? J'imagine que non car il me semble important que tous le monde joue de la même manière, c'est à dire avec le clavier. 

@telohtrab J'ai l'impression que ton design incite les utilisateurs à cliquer, non ? (Et ce n'est peut-être pas un problème…)

**Comment by telohtrab** [comment]
Bien vu Étienne ! On en a justement discuté lors du call la semaine
dernière.

La difficulté réside en un design de bouton qui soit suffisamment générique
pour être compréhensible sur ordi (présence du dessin de la touche de
clavier) et sur tablette (bouton suffisamment large pour être touchable
sans erreur du doigt. Il me semble qu'il a été décidé de conserver ce
design pour l'instant, à ajuster si souci d'UX.

**Comment by GaelleOttan** [comment]
@telohtrab on se demandait justement avec Lauren hier de comment on pourrait tester ça dans les premiers tests avec les maquettes. Est ce qu'il existe des outils qui permettent de tester des design sans dev (sur tablette ou ordi) et de tracer les actions des users?

**Comment by telohtrab** [comment]
Une solution possible est d'utiliser Figma qui peut être utilisable pour
faire des prototypes interactifs.

Seulement je crois que ça ne marche qu'au clic, faudrait que je creuse pour
voir si je peux associer des comportements de boutons aux touches du
clavier.

Pour le robot en tout cas, c'est relativement facile à faire sur Figma je
pense


Le mar. 28 janv. 2020 à 11:10, GaelleOttan <notifications@github.com> a
écrit :

**Comment by Alexis-Akinyemi** [comment]
Le détail du calcul des scores. C'est un premier essai de la méthode de description proposée par Etienne, on pourra améliorer si ça n'est pas clair.

**Données nécessaires pour le scoring**

Nombre de bonnes réponses mots français

Nombre de bonnes réponses mots pas français 

Temps MOYEN bonnes réponses pour les mots français (hors valeurs extrêmes)

Temps MOYEN bonnes réponses pour les mots pas français (hors valeurs extrêmes)

**Donnée nécessaires uniquement pour identifier les failles potentielles de la tâche au moment des tests.**

Nombre de non réponses

**Données non-nécessaires**

Nombre de mauvaises réponses

Temps moyen mauvaises réponses 

Temps moyen non réponses (donnée inutile puisque non réponse = temps max)

**Suppression des valeurs extrêmes**

Nécessite un calcul de la moyenne glissante et de l’écart type glissant des temps de réaction pour les bonnes réponses (et chaque type de mot) pour chaque session. 

→ Pas de valeurs aberrantes si une personne est seule dans une session. 

→ A appliquer aux données de temps uniquement.

Valeur extrême si supérieure à 2 ecarts types au dessus de la moyenne ou inférieure à 2 ecarts types sous la moyenne

Exemple 1 

**Données :**

Personne 1 :

MOT FRANCAIS 1 : succès, temps : 1 sec 

MOT FRANCAIS 2 : succès, temps : 1 sec 

MOT FRANCAIS 3 : succès, temps : 1 sec 

MOT PAS FRANCAIS 1 : succès, temps : 2 sec 

MOT PAS FRANCAIS 2 : succès, temps : 2 sec 

MOT PAS FRANCAIS 3 : succès, temps : 2 sec 

Personne 2 :

MOT FRANCAIS 1 : succès, temps : 1 sec 

MOT FRANCAIS 2 : succès, temps : 12 sec 

MOT FRANCAIS 3 : succès, temps : 1 sec 

MOT PAS FRANCAIS 1 : succès, temps : 2 sec 

MOT PAS FRANCAIS 2 : succès, temps : 12 sec 

MOT PAS FRANCAIS 3 : succès, temps : 2 sec 

**Calcul des seuils (exemple pour les mots français) :**

Moyenne glissante de la session (personnes 1 et 2)  mots français = (1+1+1+1+12+1) /6 =  2,7

Ecart type associé à la moyenne glissante mots français = 0,5 (ce n’est pas le vrai ecart type, on a eu la flemme de le calculer :D)

Seuil BAS de valeur extrême mots français : 2,7 - (2x0,5) = 1,7

Seuil HAUT de valeur extrême : 2,7 + (2x0,5) = 3,7

**Vérification pour chaque valeur temporelle (exemple pour les mots français)**

Personne 1 :

MOT FRANCAIS 1 : succès, temps : 1 sec 

MOT FRANCAIS 2 : succès, temps : 1 sec 

MOT FRANCAIS 3 : succès, temps : 1 sec 

Personne 2 :

MOT FRANCAIS 1 : succès, temps : 1 sec 

MOT FRANCAIS 2 : succès, temps : 12 sec **VALEUR EXTRÊME**

MOT FRANCAIS 3 : succès, temps : 1 sec 

→ **Suppression des valeurs extrêmes avant calcul du temps moyen de réponses (pour les bonnes réponses)**

Calcul du score de reconnaissance de la langue française : 

(Nb bonnes réponses mots français x Temps moyen bonnes réponses français) + (nombre de bonnes réponses pas français x Temps moyen bonnes réponses pas français)

**Exemples **(après suppression des valeurs extrêmes)

Exemple 1 :

MOT FRANCAIS 1 : succès, temps : 1 sec 

MOT FRANCAIS 2 : succès, temps : 1 sec 

MOT FRANCAIS 3 : succès, temps : 1 sec 

MOT PAS FRANCAIS 1 : succès, temps : 2 sec 

MOT PAS FRANCAIS 2 : succès, temps : 2 sec 

MOT PAS FRANCAIS 3 : succès, temps : 2 sec 

Score :  (3 x 1) + (3x2) = 9

Exemple 2 :

MOT FRANCAIS 1 : echec, temps : 1 sec 

MOT FRANCAIS 2 : echec, temps : 1 sec 

MOT FRANCAIS 3 : non réponse, temps : 1 sec 

MOT PAS FRANCAIS 1 : succès, temps : 2 sec 

MOT PAS FRANCAIS 2 : succès, temps : 2 sec 

MOT PAS FRANCAIS 3 : succès, temps : 2 sec 

Score :   (3x2) = 6

Exemple 3 :

MOT FRANCAIS 1 : echec, temps : 1 sec 

MOT FRANCAIS 2 : echec, temps : 1 sec 

MOT FRANCAIS 3 : non réponse, temps : 1 sec 

MOT PAS FRANCAIS 1 : non réponse, temps : 2 sec 

MOT PAS FRANCAIS 2 : echec, temps : 2 sec 

MOT PAS FRANCAIS 3 : echec, temps : 2 sec 

Score :  indéterminé
