### ISSUE TITLE
Intégration du bouton de mesure de satisfaction "je donne mon avis"

### ISSUE THREAD

**Issue by GaelleOttan** [betagouv/eva#707]
Nous avons pour consigne obligatoire de la DINUM d'intégrer  "je donne mon avis" qui est le standard service public de mesure de la satisfaction utilisateurs. 
L'administration de la DINUM (nadi) commence à bloquer les devis quand ce n'est pas intégré... 

Voir figma pour le design de la solution à implémenter

**Comment by GaelleOttan** [comment]
Contexte du service "je donne mon avis" à implémenter
https://observatoire.numerique.gouv.fr/

Pas à pas de mise en place du bouton
[Fiche de récupération du bouton sur MonAvis3 (1).docx](https://github.com/betagouv/eva/files/4096291/Fiche.de.recuperation.du.bouton.sur.MonAvis3.1.docx)

**Comment by GaelleOttan** [comment]
Code bouton bleu à intégrer en fin de parcours ou dans un email

<a href="https://voxusagers.numerique.gouv.fr/Demarches/2381?&view-mode=formulaire-avis&nd_mode=en-ligne-enti%C3%A8rement&nd_source=button&key=e556745a003dc51aac047d6818d4e1d6">
  <img src="https://voxusagers.numerique.gouv.fr/static/bouton-bleu.svg" alt="Je donne mon avis" title="Je donne mon avis sur cette démarche" />
</a>


Code bouton blanc: 
<a href="https://voxusagers.numerique.gouv.fr/Demarches/2381?&view-mode=formulaire-avis&nd_mode=en-ligne-enti%C3%A8rement&nd_source=button&key=e556745a003dc51aac047d6818d4e1d6">
  <img src="https://voxusagers.numerique.gouv.fr/static/bouton-blanc.svg" alt="Je donne mon avis" title="Je donne mon avis sur cette démarche" />
</a>

**Comment by GaelleOttan** [comment]
Intrégrer le bouton après l'écran merci avec le pouce levée, avant la restit candidat

**Comment by francois2metz** [comment]
Abandonné pour le moment.
