### ISSUE TITLE
Récupérer les données admin sur fichier un sheet pour créer les rapports de pilotage sur Datastudio

### ISSUE THREAD

**Issue by Laurenmichel21** [betagouv/eva#710]
**1ere requête**
- nbr de passation depuis le lancement du service soit 1 ligne avec une colonne "log" et une colonne "date"
**2ème requête** 
- nbr de compte crée depuis le lancement soit 1 colonne log et une colonne date 
Doc google sheet : https://docs.google.com/spreadsheets/d/1OVROJeOym34_qiYfectwXzr2UM-BTatusN-lhWpqmbA/edit#gid=212555684

contribue à #692

**Comment by etienneCharignon** [comment]
Peux tu ajouter une référence au "gros sujet concerné" ? Il faut juste ajouter dans la description une chaine de caractères sous la forme "#710" avec 710 qui serait le numéro de l'issue "Gros sujet" correspondante. (ici 710 c'est le numéro de cette issue ci donc ça n'a aucun sens de l'utiliser, c'est juste pour l'exemple).

**Comment by francois2metz** [comment]
On a déployé metabase pour répondre au besoin. A voir si cela correspond.

**Comment by Laurenmichel21** [comment]
@francois2metz @etienneCharignon  pour compléter ce que vous avez développé serait-il possible d'avoir : 
- un graphe pour le volume par semaine (sur 8 semaines de recul, vu que nous n'avons pas les stats depuis le début d'eva) 
- Un chiffre pour le cumul de passation  (en ajoutant un volume fixe pré-admin de 500, données cumulés sur 2019) à une variable dynamique pour l’afficher en chiffre ?
Si trop compliqué, on ajouterai une ligne de texte sous le graphe pour préciser que la vision n’inclut pas 500 premières passations ?

**Comment by etienneCharignon** [comment]
J'ai fermé car ce sujet est couvert par #794 qui a été fermé hier.
