### ISSUE TITLE
Consigne maintenance (MES illettrisme 1)

### ISSUE THREAD

**Issue by GaelleOttan** [betagouv/eva#727]

**Comment by GaelleOttan** [comment]
Pour la consigne, je propose @Alexis-Akinyemi @laurenehoutin: 

Le parc d'attraction dans lequel vous travaillez a reçu un robot qui accueillera les visiteurs. 
Ce robot n'a pas encore été réglé pour parler français, et vous devez lui apprendre à distinguer les mots français de ceux qui ne le sont pas. 
Lorsqu'un mot s'affiche, vous devrez le classer en utilisant les flèches de votre clavier ou en utilisant vos doigts si vous utilisez une tablette. 
Cliquez à droite si le mot est français, à gauche si il n'est pas français. 
Commençons d'abord par un entrainement avant de commencer l'exercice. 

Consigne intermédiaire: 

L'entrainement est terminé. Vous allez avoir une série de mots que vous devez classer, à droite si ils sont français, à gauche si ils ne le sont pas. Choisissez le plus rapidement possible, vous êtes chronométré.

**Comment by laurenehoutin** [comment]
Je trouve ca très bien ! J'ai modifié de façon minime la consigne intermédiaire.
J'ai peur que le mot distinguer soit trop complexe donc modifié cette phrase aussi.

Le parc d'attraction dans lequel vous travaillez a reçu un robot qui accueillera les visiteurs.
Ce robot n'a pas encore été réglé pour parler français, **et vous devez lui dire quels mots sont français ou non.**
Lorsqu'un mot s'affiche, vous **devez** le classer en utilisant les flèches de votre clavier ou en utilisant vos doigts si vous utilisez une tablette.
Cliquez à droite si le mot est français, à gauche si il n'est pas français.
Commençons d'abord par un entrainement avant de commencer l'exercice.

Consigne intermédiaire:
L'entrainement est terminé. **Lorsqu'un mot s'affiche, vous devez le classer, à droite si il est français, à gauche si il ne l'est pas.** Choisissez le plus rapidement possible, vous êtes chronométré.

**Comment by GaelleOttan** [comment]
Nouvelle proposition: 

Le parc d'attraction dans lequel vous travaillez a reçu un robot qui accueillera les visiteurs.
Ce robot n'a pas encore été réglé pour parler français, et vous devez lui apprendre à distinguer les mots français de ceux qui ne le sont pas.
Des mots vont apparaître un par un au centre de l’écran. Veuillez appuyer sur la flêche gauche du clavier si vous pensez que le mot apparaissant à l’écran existe en langue française, et sur la flêche droite si vous pensez qu’il n’existe pas en langue française.
Si vous êtes sur tablette, utilisez vos doigts (index et majeur) pour appuyer sur les flèches de l'écran en vert et rouge. 
Commençons d'abord par un entrainement avant de commencer l'exercice.
Cliquez à droite si le mot est français, à gauche si il n'est pas français.

Consigne intermédiaire:

L'entrainement est terminé. Vous allez avoir une série de mots, classez à droite si le mot est français, à gauche si il n'est pas français.. Choisissez le plus rapidement possible, vous êtes chronométré.

**Comment by GaelleOttan** [comment]
Le parc d'attraction dans lequel vous travaillez a reçu un robot qui accueillera les visiteurs.
Ce robot n'a pas encore été réglé pour parler français, **et vous devez lui dire quels mots sont français ou non.**
Lorsqu'un mot s'affiche, vous **devez** le classer en utilisant les flèches de votre clavier.  Si vous êtes sur tablette, utilisez vos doigts (index et majeur) pour appuyer sur les flèches de l'écran, en vert et rouge.
Cliquez à droite si le mot est français, à gauche si il n'est pas français.
Commençons d'abord par un entrainement avant de commencer l'exercice.

Consigne intermédiaire:
L'entrainement est terminé. **Lorsqu'un mot s'affiche, vous devez le classer, à droite si il est français, à gauche si il ne l'est pas.** Choisissez le plus rapidement possible, vous êtes chronométré.
Commençons d'abord par un entrainement avant de commencer l'exercice.
Cliquez à droite si le mot est français, à gauche si il n'est pas français.

Consigne intermédiaire:
L'entrainement est terminé. **Lorsqu'un mot s'affiche, vous devez le classer, à droite si il est français, à gauche si il ne l'est pas.** Choisissez le plus rapidement possible, vous êtes chronométré.

**Comment by laurenehoutin** [comment]
Pour index et majeur, ce sont juste les deux indexs (un de chaque main).
De plus, je pense qu'il va falloir faire un dessin pendant la lecture de la consigne.
(J'imagine que la première consigne intermédiaire est une erreur)

**Comment by GaelleOttan** [comment]
**Consigne robot (maintenance) finalisée et conforme à l'audio**

Le parc d'attraction dans lequel vous travaillez a reçu un robot qui accueillera les visiteurs.
Ce robot n'a pas encore été réglé pour parler français, et vous devez lui apprendre quels mots sont français ou non.
Lorsqu'un mot s'affiche, vous devez le classer en utilisant les flèches de votre clavier. Si vous êtes sur tablette, utilisez les deux index de vos mains pour appuyer sur les flèches de l’écran en vert et rouge. Cliquez à gauche si le mot est français, à droite si il n'est pas français.
Commençons d'abord par un entrainement avant de débuter l’exercice.

Consigne intermédiaire:
Vous venez de réussir l’entraînement, bravo ! Vous allez maintenant pouvoir commencer l’exercice. Lorsqu'un mot s'affiche, vous devez le classer, à gauche si il est français, à droite si il ne l'est pas. Choisissez le plus rapidement possible, vous êtes chronométré.

**Comment by GaelleOttan** [comment]
Dans la mesure où je ne peux pas télécharger de mp4 dans github, je vous l'envoie dans slack avec l'issue associée

**Comment by etienneCharignon** [comment]
Sur les maquettes de @telohtrab (et sur le dev qui est en cours de relecture), les mot français sont à gauche et les mot pas français à droite. On peut changer l'ordre des boutons, ou changer le texte de cette consigne. Qu'est-ce qu'on fait ?

**Comment by GaelleOttan** [comment]
@etienneCharignon dans la consigne finalisée à intégrer (mon dernier message ci dessus) c'est bien conforme à la maquette, les bon à gauche et les faux à droite
