### ISSUE TITLE
Le jeu "Bureau" ne se lance pas. 

### ISSUE THREAD

**Issue by IshanB** [betagouv/eva#735]
Sur mon MacBook, Google Chrome, après avoir cliqué sur "A vous de jouer" dans la mise en situation "Bureau", le jeu ne se lance pas.

![image](https://user-images.githubusercontent.com/28890473/73590352-c31cdb00-44e1-11ea-96bf-772270fbd236.png)

**Comment by francois2metz** [comment]
@IshanB Merci d'avoir reporté ce problème. Peux tu nous indiquer le code campagne que tu a utilisé ?

**Comment by IshanB** [comment]
J’ai teste avec un code « test » (j’ai mis ca au pif, les deux premiers
jeux se sont lancés sans problème)

Le lun. 3 févr. 2020 à 11:42, François de Metz <notifications@github.com> a
écrit :

**Comment by francois2metz** [comment]
Ok. il ne devait pas avoir de campagne **test**, mais une structure l'a créée récemment :/ et n'a pas configuré correctement le bureau. J'ai nettoyé les données pour éviter de polluer sa campagne. 

Je te propose d'utilise le code campagne **demo** et le bureau devrait fonctionner.

**Comment by IshanB** [comment]
Ah, c'était donc un coup de chance ;)
OK j'essaierai avec demo !
Merci

Le lun. 3 févr. 2020 à 12:11, François de Metz <notifications@github.com> a
écrit :

**Comment by francois2metz** [comment]
Je clôt. A réouvrir si la solution n'était celle la.
