### ISSUE TITLE
Propositions d'améliorations du bandeau sur la page d'accueil.

### ISSUE THREAD

**Issue by IshanB** [betagouv/eva#736]
![image](https://user-images.githubusercontent.com/28890473/73590368-ecd60200-44e1-11ea-986e-11259d0a9a0d.png)
Propositions pour éviter le terme "startup" qui prête à confusion : 
"eva est un service développé dans le cadre du programme beta.gouv.fr"
"eva est un service beta.gouv.fr"

**Comment by etienneCharignon** [comment]
A changer aussi dans le texte qui se trouve un peut plus bas dans la page.
> eva est une startup d’état portée par la Direction Interministérielle…
