### ISSUE TITLE
(prévention) Intégrer le symbole du danger sur le cul du camion

### ISSUE THREAD

**Issue by GaelleOttan** [betagouv/eva#737]
Dans le module prévention, lorsque l'on clique sur le danger du camion liquide dangereux, le zoom ne permet pas de bien voir le dessin de danger. Il faut rajouter sur le cul du camion le symbole pour qu'on puisse le voir facilement lorsque l'on identifie le niveau de danger

**Comment by GaelleOttan** [comment]
![Capture d’écran 2020-02-03 à 10 02 36](https://user-images.githubusercontent.com/48095868/73639289-5bdf6200-466c-11ea-9b92-73fd78c46980.png)

**Comment by MatthieuMARTIN** [comment]
@GaelleOttan  très bien, est ce ça vous va ainsi ? si oui je MAJ sur le drive :) 

![écran-9-v7](https://user-images.githubusercontent.com/58987553/73851335-95130000-482d-11ea-93f2-438a790b6eab.jpg)

**Comment by GaelleOttan** [comment]
oui c'est top @MatthieuMARTIN

**Comment by MatthieuMARTIN** [comment]
Ok c'est MAJ sur le drive !
