### ISSUE TITLE
Restitution de la situation Maintenance

### ISSUE THREAD

**Issue by francois2metz** [betagouv/eva#740]
- [x] Elimination des valeurs aberrantes
- [x] Calcul d’un score individuel de nombre d’erreurs https://github.com/betagouv/eva-serveur/pull/324  **[A SUPPRIMER CF COMMENTAIRE ALEXIS CI-DESSOUS)**
  - nombre de mots identifiés comme non mots + nombre de non-mots identifiés comme mots
- [x] Calcul d’un score individuel de nombre de bonnes réponses mots français https://github.com/betagouv/eva/issues/762
- [x] Calcul d’un score individuel de nombre de bonnes réponses non-mots https://github.com/betagouv/eva-serveur/pull/343
- [x] Calcul du nombre de non-réponse https://github.com/betagouv/eva-serveur/pull/325
- [x] Calcul de la moyenne des scores pour les mots français et non-mots pour chaque candidat (temps moyen pour chaque catégorie)
    - [x] non-mots https://github.com/betagouv/eva-serveur/pull/339
    - [x] mots français https://github.com/betagouv/eva-serveur/pull/351
- [ ]~~Calcul d’un score individuel d’identification des mots émotionnels :~~
  - ~~Temps moyen d’identification des mots émotionnels - temps moyen d’identification des non mots~~
- [x] ~~Calcul d’un score individuel d’identification des mots neutres~~
  - ~~Temps moyen d’identification des mots neutres - temps moyen d’identification des non mots~~ 
- [x] Calcul des indicateurs moyenne et écart type pour chaque score. https://github.com/betagouv/eva-serveur/pull/340
- [x] Calcul du score “z” pour chaque score : (score - moyenne) / Ecart-type https://github.com/betagouv/eva-serveur/pull/340

Voir #587

**Comment by Alexis-Akinyemi** [comment]
Le détail du calcul des scores. C'est un premier essai de la méthode de description proposée par Etienne, on pourra améliorer si ça n'est pas clair.

**Données nécessaires pour le scoring**

Nombre de bonnes réponses mots français

Nombre de bonnes réponses mots pas français 

Temps MOYEN bonnes réponses pour les mots français (hors valeurs extrêmes)

Temps MOYEN bonnes réponses pour les mots pas français (hors valeurs extrêmes)

**Donnée nécessaires uniquement pour identifier les failles potentielles de la tâche au moment des tests.**

Nombre de non réponses

**Données non-nécessaires**

Nombre de mauvaises réponses

Temps moyen mauvaises réponses 

Temps moyen non réponses (donnée inutile puisque non réponse = temps max)

**Suppression des valeurs extrêmes**

Nécessite un calcul de la moyenne glissante et de l’écart type glissant des temps de réaction pour les bonnes réponses (et chaque type de mot) pour chaque session. 

→ Pas de valeurs aberrantes si une personne est seule dans une session. 

→ A appliquer aux données de temps uniquement.

Valeur extrême si supérieure à 2 ecarts types au dessus de la moyenne ou inférieure à 2 ecarts types sous la moyenne

Exemple 1 

**Données :**

Personne 1 :

MOT FRANCAIS 1 : succès, temps : 1 sec 

MOT FRANCAIS 2 : succès, temps : 1 sec 

MOT FRANCAIS 3 : succès, temps : 1 sec 

MOT PAS FRANCAIS 1 : succès, temps : 2 sec 

MOT PAS FRANCAIS 2 : succès, temps : 2 sec 

MOT PAS FRANCAIS 3 : succès, temps : 2 sec 

Personne 2 :

MOT FRANCAIS 1 : succès, temps : 1 sec 

MOT FRANCAIS 2 : succès, temps : 12 sec 

MOT FRANCAIS 3 : succès, temps : 1 sec 

MOT PAS FRANCAIS 1 : succès, temps : 2 sec 

MOT PAS FRANCAIS 2 : succès, temps : 12 sec 

MOT PAS FRANCAIS 3 : succès, temps : 2 sec 

**Calcul des seuils (exemple pour les mots français) :**

Moyenne glissante de la session (personnes 1 et 2)  mots français = (1+1+1+1+12+1) /6 =  2,7

Ecart type associé à la moyenne glissante mots français = 0,5 (ce n’est pas le vrai ecart type, on a eu la flemme de le calculer :D)

Seuil BAS de valeur extrême mots français : 2,7 - (2x0,5) = 1,7

Seuil HAUT de valeur extrême : 2,7 + (2x0,5) = 3,7

**Vérification pour chaque valeur temporelle (exemple pour les mots français)**

Personne 1 :

MOT FRANCAIS 1 : succès, temps : 1 sec 

MOT FRANCAIS 2 : succès, temps : 1 sec 

MOT FRANCAIS 3 : succès, temps : 1 sec 

Personne 2 :

MOT FRANCAIS 1 : succès, temps : 1 sec 

MOT FRANCAIS 2 : succès, temps : 12 sec **VALEUR EXTRÊME**

MOT FRANCAIS 3 : succès, temps : 1 sec 

→ **Suppression des valeurs extrêmes avant calcul du temps moyen de réponses (pour les bonnes réponses)**

Calcul du score de reconnaissance de la langue française : 

(Nb bonnes réponses mots français x Temps moyen bonnes réponses français) + (nombre de bonnes réponses pas français x Temps moyen bonnes réponses pas français)

**Exemples **(après suppression des valeurs extrêmes)

Exemple 1 :

MOT FRANCAIS 1 : succès, temps : 1 sec 

MOT FRANCAIS 2 : succès, temps : 1 sec 

MOT FRANCAIS 3 : succès, temps : 1 sec 

MOT PAS FRANCAIS 1 : succès, temps : 2 sec 

MOT PAS FRANCAIS 2 : succès, temps : 2 sec 

MOT PAS FRANCAIS 3 : succès, temps : 2 sec 

Score :  (3 x 1) + (3x2) = 9

Exemple 2 :

MOT FRANCAIS 1 : echec, temps : 1 sec 

MOT FRANCAIS 2 : echec, temps : 1 sec 

MOT FRANCAIS 3 : non réponse, temps : 1 sec 

MOT PAS FRANCAIS 1 : succès, temps : 2 sec 

MOT PAS FRANCAIS 2 : succès, temps : 2 sec 

MOT PAS FRANCAIS 3 : succès, temps : 2 sec 

Score :   (3x2) = 6

Exemple 3 :

MOT FRANCAIS 1 : echec, temps : 1 sec 

MOT FRANCAIS 2 : echec, temps : 1 sec 

MOT FRANCAIS 3 : non réponse, temps : 1 sec 

MOT PAS FRANCAIS 1 : non réponse, temps : 2 sec 

MOT PAS FRANCAIS 2 : echec, temps : 2 sec 

MOT PAS FRANCAIS 3 : echec, temps : 2 sec 

Score :  indéterminé

**Comment by etienneCharignon** [comment]
@Alexis-Akinyemi  quand tu dis 
> **Exemples **(après suppression des valeurs extrêmes)

Est-ce que tu veux dire qu'on retire de la liste la mesure (comme si la personnes avait répondu faut) ou est-ce qu'on remplace le temps extrême par la moyenne comme tu as l'aire de l'avoir fait ?

**Comment by Alexis-Akinyemi** [comment]
On retire les valeurs pour qu'elles ne soient pas prises en compte. 
Pour reprendre l'exemple : 
Personne 2 :

MOT FRANCAIS 1 : succès, temps : 1 sec

MOT FRANCAIS 2 : succès, temps : 12 sec VALEUR EXTRÊME

MOT FRANCAIS 3 : succès, temps : 1 sec

Pour calculer le temps moyen de la personne on prend : 
MOT FRANCAIS 1 : succès, temps : 1 sec

MOT FRANCAIS 3 : succès, temps : 1 sec

**Comment by etienneCharignon** [comment]
est-ce que tu as pu réfléchir au problème qu'on te signalais hier avec Stéphane ? (Le coté, "plus on avance moins vite, moins on ralenti plus vite") : 
> le truc bizarre c'est que le nombre de bonnes réponses, + il est élevé mieux c'est
> alors qu'un temps moyen : + il est petit mieux c'est

**Comment by Alexis-Akinyemi** [comment]
J'ai tendance à pencher pour la solution la plus simple.
Si on remplace la multiplication par une division le problème est réglé et on obtient le score que l'on souhaite avoir (et surtout le niveau de granularité que l'on recherche).
On aurait donc :
(Nb bonnes réponses mots français / Temps moyen bonnes réponses français) + (nombre de bonnes réponses pas français / Temps moyen bonnes réponses pas français)

Je vais quand même croiser l'info avec Laurène dès que possible pour être sûr.

**Comment by Alexis-Akinyemi** [comment]
Suite au constat de perfectibilité de l'algo, on propose d'apporter une petite modification pour qu'il fonctionne davantage comme on le souhaite : en remplaçant la somme par une multiplication.
On aurait donc (Nb bonnes réponses mots français / Temps moyen bonnes réponses français) *(nombre de bonnes réponses pas français / Temps moyen bonnes réponses pas français)

**Cependant** on ne sait pas s'il s'agit d'un vrai problème d'algo puisque les personnes qui répondent au hasard devraient voir la plupart de leurs réponses considérées comme valeurs extrêmes et donc supprimées.
Notre correction ne couvre donc pour l'instant pas le cas de la réponse au hasard total "la personne mitraille ses touches directionnelles durant tout l'exercice". Cela pourrait être corrigé par l'intégration de pénalités en cas de mauvaises réponses, mais on sort complètement du cadre méthodologique de cette tâche. En tout cas cela nécessite de voir des données en situation réelle.

**Pour ce qui est de la correction** :

**Dans le cas d'une triche de type "je réponds le plus vite possible sur une seule catégorie pour avoir 50% de bonnes réponses et une rapidité incroyable"** soit : 
nombre de bonnes réponses mots français : 28
temps moyen de réponse mots français : 0.15 

nombre de bonnes réponses mots pas français : 0 
temps moyen de réponses mot pas français : vide
ancien score : 199 
score après correction : 0 

**En revanche pour une performance "faible" sans triche, soit** : 
nombre de bonnes réponses mots français : 6
temps moyen de réponse mots français : 1.1

nombre de bonnes réponses mots pas français : 10 
temps moyen de réponses mot pas français : 1.2
ancien score : 105.45 
score après correction : 41.67

**Enfin pour le score de clementWR2 soit** : 
nombre de bonnes réponses mots français : 8
temps moyen de réponse mots français : 0.72

nombre de bonnes réponses mots pas français : 12
temps moyen de réponses mot pas français : 0.63
ancien score : 30.16
score après correction : 211.64

**Problème toujours présent** : on continue de favoriser les réponses au hasard : 
nombre de bonnes réponses mots français : 14
temps moyen de réponse mots français : 0.14 

nombre de bonnes réponses mots pas français : 14 
temps moyen de réponses mot pas français : 0.14
ancien score : 200 
score après correction : 10 000 

Mais avec un temps de réponse pareil, on devrait voir beaucoup de valeurs extrêmes dans l'usage. Le cas de figure ou une personne répond totalement au hasard en attendant "un délai raisonnable" entre chaque réponse est plus difficile à prédire, mais aussi un peu moins probable.

Pour la suite on aimerait transformer ce score en le transformant en score z pour que tous les participants obtiennent un score allant de -3 à 3. 
Il faudrait donc, comme pour tous les autres calculs de score z 
- calculer le moyenne glissante et l'ecart-type glissant du score
- soustraire la moyenne de l'utilisateur à la moyenne glissante et diviser le résultat par l'écart-type glissant 
Si au début les score s'étendent au delà de -3 et 3 c'est parce que la moyenne n'est pas stable, ce qui devrait arriver avec l'usage.

**Comment by etienneCharignon** [comment]
@Alexis-Akinyemi pourrais-tu déplacer cette dernière remarque dans une nouvelle issue qui porterait un titre permettant de caractériser la demande (que j'identifie comme nouvelle) ? Dans la nouvelle issue, tu pourras faire un lien vers celle ci, pour référence.
