### ISSUE TITLE
Reprendre consigne accueil 

### ISSUE THREAD

**Issue by GaelleOttan** [betagouv/eva#766]
enlever 'bienvenue dans le parc compétences pro'

**Comment by etienneCharignon** [comment]
J'ai fais une correction pour supprimer la référence à compétence pro en coupant la bande son. C'est une correction temporaire qui n'est pas très satisfaisante mais cette consigne sera de toute façon reprise dans le cadre de la simplification des consignes. (Cf #784)

Je clos cette issue
