### ISSUE TITLE
Design: MES illettrisme partie 3 : Compréhension des conversations textes/images/son

### ISSUE THREAD

**Issue by telohtrab** [betagouv/eva#768]
Issue concernant les illustrations et les maquettes de la partie 3 d'illettrisme.

Complémente #697

**Comment by telohtrab** [comment]
Wireframes Lost Phone

![1-LostPhoneHome1](https://user-images.githubusercontent.com/7781917/74742506-03f54d80-525f-11ea-9799-ef7a7d1fbd24.png)
![2-LostPhone1](https://user-images.githubusercontent.com/7781917/74742509-048de400-525f-11ea-899d-29b2429e5e75.png)
![3-LostPhoneHome2](https://user-images.githubusercontent.com/7781917/74742510-05267a80-525f-11ea-934f-a8a0335b0e7c.png)
![4-LostPhone2](https://user-images.githubusercontent.com/7781917/74742511-05267a80-525f-11ea-9c02-a54472e32e8c.png)
![5-LostPhoneHome3](https://user-images.githubusercontent.com/7781917/74742513-05bf1100-525f-11ea-844d-ac9b7622c751.png)
![6-LostPhone3](https://user-images.githubusercontent.com/7781917/74742514-05bf1100-525f-11ea-9bfc-23293ef3ae6d.png)
![7-LostPhoneHome4](https://user-images.githubusercontent.com/7781917/74742516-0657a780-525f-11ea-99cc-de06f3fa0798.png)
![8-LostPhone4](https://user-images.githubusercontent.com/7781917/74742517-0657a780-525f-11ea-910a-b176dcaa08b6.png)
![9-LostPhoneHome5](https://user-images.githubusercontent.com/7781917/74742518-0657a780-525f-11ea-8293-4daa7b413c27.png)
![10-LostPhone5](https://user-images.githubusercontent.com/7781917/74742519-06f03e00-525f-11ea-9b6f-425517edeea0.png)
![11-LostPhone6](https://user-images.githubusercontent.com/7781917/74742521-06f03e00-525f-11ea-9a82-63f562efcf57.png)
![12-LostPhone7](https://user-images.githubusercontent.com/7781917/74742524-0788d480-525f-11ea-8ebc-110ffad66646.png)
![13-LostPhone8](https://user-images.githubusercontent.com/7781917/74742525-0788d480-525f-11ea-82d3-0fa1da6fccb5.png)

**Comment by GaelleOttan** [comment]
@telohtrab pour récap les dessins à @MatthieuMARTIN , est ce que c'est ok? 

- Un téléphone (dans une main ?) sur un fond plutôt "flou" sans trop de détails
- Un dessin de sophie avec le directeur du zoo (à intégrer dans le téléphone pour l'écran 1)
- Une illustration de fin en vue subjective alors qu'on rend le téléphone à Sophie

**Comment by MatthieuMARTIN** [comment]
yes, j'avais en plus les petits avatars de "Sophie" et "Dounia" lors de leur conversation SMS.

**Comment by telohtrab** [comment]
Avec les avatars mentionnés par Matthieu ça me paraît ok !

**Comment by MatthieuMARTIN** [comment]
Hey ! Voila les images ! 
Si elles vous vont j'met sur le drive ! 
A+

![01-lost-phone](https://user-images.githubusercontent.com/58987553/75367031-f3c51a00-58bf-11ea-8c74-b3612d771b37.jpg)
![02-lost-phone](https://user-images.githubusercontent.com/58987553/75367033-f45db080-58bf-11ea-9905-0c66aa0d651c.jpg)
![03-lost-phone](https://user-images.githubusercontent.com/58987553/75367035-f4f64700-58bf-11ea-833f-b05a6cb4f373.jpg)
![04-lost-phone](https://user-images.githubusercontent.com/58987553/75367037-f58edd80-58bf-11ea-8df2-c01cae4aa8f4.jpg)

**Comment by telohtrab** [comment]
Merci c'est top ! 
J'ai juste un point par rapport au badge "responsable du zoo" manquant sur la photo ? 

J'aurai besoin de cette photo séparément par ailleurs :)

**Comment by MatthieuMARTIN** [comment]
Ah oui j'ai oublié le badge ! Tu peux me redire exactement quoi mettre dessus stp ? 
Et ok je te fournirai la photo séparément aussi !

**Comment by GaelleOttan** [comment]
@MatthieuMARTIN voici les instructions pour les badges
La personne trouve une photo de Sophie (elle porte un badge avec son prénom) en compagnie d'un certain Denis (même chose). Sur le badge de Denis, on trouve écrit son poste "Responsable de Zoo". L'heure est indiquée sur la photo : 12h32.

**Comment by MatthieuMARTIN** [comment]
Très bien merci ! 
Voici le visuel corrigé avec les badges et l'image seule de la photo pour @telohtrab 
Si on est totu bon je met tout ça sur le drive ! 
![photo-seule](https://user-images.githubusercontent.com/58987553/75684342-e54c7900-5c98-11ea-8742-968c1b04dfce.jpg)
![02-lost-phone](https://user-images.githubusercontent.com/58987553/75684343-e67da600-5c98-11ea-9b3f-3a217ba23f13.jpg)

**Comment by telohtrab** [comment]
Je veux bien tout ça sur le Drive ! 
Pense bien à me séparer les exports pour que je puisse intégrer ça :) 

Si possible pour le début d'apres-m ?

**Comment by MatthieuMARTIN** [comment]
@telohtrab ce sera fait ! 
Je ne suis pas sûr de comprendre ce que tu veux dire par séparer les exports, tu peux me le préciser stp ?  ^^

**Comment by MatthieuMARTIN** [comment]
C'est tout sur le drive ! j'ai fais un dossier " lost phone" dans le dossier illustration ! 
A+

**Comment by telohtrab** [comment]
Ah pardon j'avais pas vu ton message.

Eh bien la photo, le fond, les icônes bien séparées et pas "applatis" :-)

Le mer. 4 mars 2020 à 13:54, MatthieuMARTIN <notifications@github.com> a
écrit :

**Comment by telohtrab** [comment]
Il me manque par exemple le téléphone avec l'intérieur de l'écran transparent en PNG pour que je puisse intégrer proprement les apps sans trop bricoler :)

**Comment by telohtrab** [comment]
Et les icônes SMS séparées également chacune sur un PNG

**Comment by MatthieuMARTIN** [comment]
Ok j'ai ajouté ce que tu m'as demandé, après t'as les psd si t'as besoin d'un autre petit truc ;)

**Comment by telohtrab** [comment]
Merci. 

Oui je sais mais je préfère que tu exportes tout pour 2 raisons :
- En fonction de l'organisation des PSD, tu t'y retrouveras plus vite que moi ^^
- J'ai une suite crackée sur mon fixe, mais rien sur mon laptop

Et ça me permet surtout d'aller piocher dans tes dossiers directement depuis Figma sans ouvrir une autre app

**Comment by MatthieuMARTIN** [comment]
pas de soucis :)

**Comment by telohtrab** [comment]
Je suis loin d'avoir terminé mais voici un WIP des écrans avec les premières illustrations intégrées

![1-LostPhoneHome1](https://user-images.githubusercontent.com/7781917/75891258-d0561e00-5e2f-11ea-9cd3-09e1ed892911.png)
![1-LostPhoneHome2](https://user-images.githubusercontent.com/7781917/75891260-d0eeb480-5e2f-11ea-86d1-f0d9052436cd.png)
![2-LostPhone1](https://user-images.githubusercontent.com/7781917/75891262-d1874b00-5e2f-11ea-93c3-9bd3661d4932.png)
![2-LostPhoneHome1](https://user-images.githubusercontent.com/7781917/75891264-d1874b00-5e2f-11ea-9c0a-209d8beb89f7.png)
![3-LostPhoneHome2](https://user-images.githubusercontent.com/7781917/75891267-d21fe180-5e2f-11ea-8a5e-a87bd0d5ba38.png)
![4-LostPhone2](https://user-images.githubusercontent.com/7781917/75891269-d2b87800-5e2f-11ea-8f0b-3a333164092b.png)
![5-LostPhoneHome3](https://user-images.githubusercontent.com/7781917/75891271-d2b87800-5e2f-11ea-9516-a789a99fd437.png)
![6-LostPhone3](https://user-images.githubusercontent.com/7781917/75891273-d2b87800-5e2f-11ea-9597-1c1c11b9c5b9.png)
![7-LostPhoneHome4](https://user-images.githubusercontent.com/7781917/75891275-d3510e80-5e2f-11ea-9a1b-021a90ae5257.png)
![8-LostPhone4](https://user-images.githubusercontent.com/7781917/75891276-d3e9a500-5e2f-11ea-8247-14abdfc24fae.png)

**Comment by GaelleOttan** [comment]
après l'énigme, il me semble qu'on devrait avoir l'écran du tel pour cliquer sur l'application photo avant d'ouvrir la photo non? 
Sur l'écran SMS dounia, ça me semble un peu confus dans le storytelling d'inviter quelqu'un à boire un café sur un banc. Peut être plutôt dire "Non on se rejoindra après le repas vers 13h15", ce serait ok pour toi lauren ? 

Dernier écran, j'ai un peu de mal à voir le lien entre le parc d'attraction et le jardin des plantes, est ce que l'on peut plutôt indiquer "Aire de pique nique" ou un truc dans le genre @laurenehoutin ?

**Comment by telohtrab** [comment]
Pour répondre à ton premier point, je crois que c'est juste une erreur dans l'ordre des écrans lors de l'upload ici. Mais oui c'est bien comme tu le décris ^^

**Comment by laurenehoutin** [comment]
Si la question est pour moi, oui pas de problème pour dire "Non on se rejoindra après le repas vers 13h15". 
Pour le dernier écran, si tu préfères oui pas de problème :)

**Comment by telohtrab** [comment]
Toutes mes excuses avec tout ça, j'me rends compte que ce ne sont pas les dernières versions des écrans qui se trouvent ici.

@MatthieuMARTIN Ce qui est en rose fluo sont les toutes dernières images manquantes du coup :)

Tout est dans le commentaire de cette autre issue : https://github.com/betagouv/eva/issues/697#issuecomment-597799385

**Comment by telohtrab** [comment]
@etienneCharignon @laurenehoutin @Alexis-Akinyemi 

Voici ma proposition concernant le passage aujourd'hui un peu trop brutal entre la dernière app et les écrans avec questions de mémorisation. 

Un simple écran intermédiaire qui signale qu'on en a fini avec les applications et qu'on rejoint Sophie. Je suis preneur de retours sur le wording :)

![image](https://user-images.githubusercontent.com/7781917/77532946-344f8d80-6e96-11ea-9c2a-197bcb8f3af3.png)

**Comment by laurenehoutin** [comment]
Je plussoie à nouveau ! Je pense que des gens pourraient ne pas aimer le mot enquête, mais moi ca me va.

**Comment by MatthieuMARTIN** [comment]
@telohtrab Voila les 2 "photos de profil" de Lindsay et Mickael qu'il manquait :)  Je les met sur le drive aussi. 
![lost phone lindsay](https://user-images.githubusercontent.com/58987553/77928365-9a7a4d00-72a8-11ea-9ead-7529e11a8894.png)
![lost phone mickael](https://user-images.githubusercontent.com/58987553/77928369-9b12e380-72a8-11ea-834a-b01ce3806eb6.png)

**Comment by MatthieuMARTIN** [comment]
Voila la photo avec l'info de l'étiquette en plus grosse ! 
Pareil je met sur le drive. 
@telohtrab Tu intègres toi même l'image dans le téléphone c'est ça ? 

![photo-seule2](https://user-images.githubusercontent.com/58987553/77928863-40c65280-72a9-11ea-8af1-3555cfdf2b9f.jpg)

**Comment by telohtrab** [comment]
Merci Matthieu ! Yes je vais intégrer ça.

Benjamin Bartholet

*TRΔB design & inks*
website : trab.design
tw : @trab_ink
ig : @trab_ink <https://twitter.com/trab_ink>


Le lun. 30 mars 2020 à 17:11, MatthieuMARTIN <notifications@github.com> a
écrit :

**Comment by telohtrab** [comment]
On est normalement ok sur la partie design de cette MES. Je close donc !
