### ISSUE TITLE
Nouvelle Restitution : Design

### ISSUE THREAD

**Issue by telohtrab** [betagouv/eva#777]
référence #691

**Comment by telohtrab** [comment]
Hello ! 
J'ai commencé à travailler sur la nouvelle fiche, voici un WIP. Je termine cet après-m et demain.

![image](https://user-images.githubusercontent.com/7781917/75149251-d6e2e800-5701-11ea-8725-c73a73fa8c26.png)

**Comment by GaelleOttan** [comment]
@telohtrab c'est top. @Alexis-Akinyemi @laurenehoutin ça vous semble conforme à ce que vous aviez en tête? 
J'ai un RDV jeudi aprem aux conseillers des portefeuilles jeunes et RSA d'un pole emploi local (Lunel). Si je peux montrer la future fiche de restit "complète" ça m'aiderait beaucoup à pouvoir les projeter dans ce que la restit deviendra dans les prochains mois

**Comment by Alexis-Akinyemi** [comment]
Hello !
C'est top pour nous pour les compétences de base :)

**Comment by telohtrab** [comment]
Je fais plein de tests pour la visualisation des compétences transversales avec les cercles ou l'escargot, j'avoue ne pas trop savoir vers quoi me tourner. La grande quantité de compétences ainsi que la longueur des labels ne m'aide pas. 

Une autre solution serait de numéroter les sphères avec une légende à coté mais ça complexifie la lecture en un coup d'oeil qu'on souhaite. 

Par ailleurs, j'essaie de pas trouver un truc trop exotique qui serait chiant à développer. 

Voici mes essais, dites moi ! 

![image](https://user-images.githubusercontent.com/7781917/75238589-8df26880-57c1-11ea-88c9-5d61c29b3d47.png)

**Comment by laurenehoutin** [comment]
Moi je trouve la dernière version pas mal même si c'est certain que le fait de lire à l'envers n'est pas top. J'avoue ne pas avoir de meilleure idée et ne pas trouver que ce soit catastrophique. J'ai regardé un peu ce qui se fait dans les solutions d'évaluation des compétences qu'on connait, et c'est présenté soit comme ca soit en radar.

**Comment by laurenehoutin** [comment]
Je viens de comprendre qu'il ne faut pas se relire une fois qu'on a envoyé un message : "Moi je"

**Comment by telohtrab** [comment]
Je peux faire un essai de l'escargot avec les labels orientés autrement, j'avais testé mais ça me paraissait un peu bazar (comme sur la première avec les cercles)

**Comment by telohtrab** [comment]
Je vois un avantage à l'escargot c'est que ça met en haut à droite les compétences fortes, en haut à gauche les points à améliorer

**Comment by laurenehoutin** [comment]
Je suis d'accord (c'est mieux organisé et plus sympa visuellement) mais je ne suis pas sure qu'on soit sur une population bien flexible cognitivement ou en capacité de le faire dans la situation, et j'ai peur que la nouveauté (pas grand monde connait ce genre de graph) nous fasse défaut. Tu vois ce que je veux dire ?

**Comment by GaelleOttan** [comment]
Il faut garder en tête que la restit est en premier lieu pour les professionnels de l'accompagnement (donc normalement cablé cognitivement). Le droit d'accès au document de restit pour les candidats ne nous oblige pas à faire le doc pour eux ;)

**Comment by laurenehoutin** [comment]
Je parle bien des accompagnants. Je pense par exemple aux conseillers PE qui ont une limite de temps importante avec chaque candidat (surcharge = stress ou inconfort = manque de flexibilité = moins d'effort pour la nouveauté ou la difficulté)

**Comment by GaelleOttan** [comment]
Je trouve que seul le second est facilement compréhensible (j'ai beaucoup plus de mal avec le troisième). On est d'accord qu'en vrai les couleurs seront mélangées (et aussi qu'on va joindre  une petite légende pour comprendre les codes couleur? )

**Comment by laurenehoutin** [comment]
Oui je comprends !

J'ai l'impression qu'ici la couleur renvoie au score (vert = très bon score, orange = pas bon score)

**Comment by GaelleOttan** [comment]
Les ronds positionnés du plus grands au plus petits de manière graduelle c'est facile à comprendre. Par contre pour les couleurs, si c'est bien ce que dit lauren, j'avais pas du tout compris (le fait de ne pas utiliser les couleurs classique pour dire ok= vert, pas ok = rouge et de graduer dans cette palette fait qu'on passe à côté de la hierarchisation). Peut être plus utiliser des emoticones pour accompagner cette idée sinon?

**Comment by etienneCharignon** [comment]
Pour le dev, le premier graphique est assez difficile à faire, à moins qu'on trouve une librairie qui face déjà le travaille (ce qui est possible, faudrait chercher).

Pour ce qui est du "moi je", c'est le deuxième graphique qui me parle le plus.

**Comment by telohtrab** [comment]
Bon, on oublie le premier qui me paraît le plus compliqué à lire + compliqué techniquement

En ce qui concerne la palette, j'ai justement utilisé les couleurs de la palette Gaelle, je ne comprends pas ton incompréhension ^^ (Le rouge on m'a dit de le bannir je le mets presque nulle part dorénavant) :
Le vert indique bien les 2 compétences les plus fortes, les deux nuances de bleu pour les entre deux et le jaune "warning" pour dire "attention ce n'est pas bon" exactement comme dans les mises en situation. 

Les émoticônes c'est pas la panacée, on a tenté sur prévention ça marchait pas et l'intégration dans le graphique en plus du fait que j'arrive pas à intégrer les labels proprement, je vais pas m'y retrouver...

**Comment by telohtrab** [comment]
Le 2eme est intéressant, mais il faut que je trouve un moyen de le rendre plus compact, car il ne nous reste pas beaucoup de place sur la page A4 (j'essaie de tout conserver sur un recto)

Le 3eme est plus compact et plus difficile à lire de ce que je comprends de vos retours.

**Comment by Laurenmichel21** [comment]
j'élimine le dernier et je garderai le 2ème ! Avec une suggestion de lecture à droite ?

**Comment by telohtrab** [comment]
Quant au premier @etienneCharignon c'est en grande partie inspiré de cet algorithme : https://www.wikiwand.com/en/Circle_packing

**Comment by telohtrab** [comment]
> j'élimine le dernier et je garderai le 2ème ! Avec une suggestion de lecture à droite ?
Pourquoi élimines-tu le dernier ?

**Comment by Laurenmichel21** [comment]
Je trouve que le texte écris de cette manière n'est pas simple a lire visuellement on a tendance à vouloir tourner notre écrans (en exagérant bien évidement)

**Comment by telohtrab** [comment]
![image](https://user-images.githubusercontent.com/7781917/75242207-ea588680-57c7-11ea-9098-88ef719f5e11.png)

**Comment by telohtrab** [comment]
En prenant en compte vos diverses

**Comment by Laurenmichel21** [comment]
ah le premier est top et finalement le deuxième aussi ! On peut les tester jeudi matin auprès  des conseillers de l'école de la deuxième chance.

**Comment by laurenehoutin** [comment]
Même réaction de mon côté : je trouve ca plus facilement compréhensible. Du coup j'aime bien les deux !

**Comment by telohtrab** [comment]
"gna gna gna j'aime bien les deux" 

Vous êtes les PIRES CLIENTS !

**Comment by telohtrab** [comment]
Mais ok, j'fais 2 variantes de la fiche alors

**Comment by GaelleOttan** [comment]
Pour moi incontestablement la première. Pour les couleurs, c'est qu'on passe du vert au bleu au gris au orange, on ne comprends pas qu'il y a une continuité de bonne maitrise à lacune. Peut être passer juste de différent niveau de vert à différents niveau de orange (mais vraiment le bleu et le gris ça colle pas pour moi)

**Comment by telohtrab** [comment]
Voici my take sur les deux variantes. Ce ne sont que 2 propositions, y'a des trucs à ajuster, mixer etc.. mais le principal est là ! 

Vous verrez que j'ai essayé d'utiliser la dataviz comme point central pour mettre en exergue les potentialités et points d'améliorations avec le lien vers les métiers associés directement intégré dans l'ensemble. 

Version Cercles
![image](https://user-images.githubusercontent.com/7781917/75272653-96b55f80-57fe-11ea-8c2a-5b9234a3abbd.png)

Version escargot
![image](https://user-images.githubusercontent.com/7781917/75272671-a0d75e00-57fe-11ea-9e5f-04f31819ccc2.png)

**Comment by telohtrab** [comment]
Voici my take sur les deux variantes. Ce ne sont que 2 propositions, y'a des trucs à ajuster, mixer etc.. mais le principal est là ! 

Vous verrez que j'ai essayé d'utiliser la dataviz comme point central pour mettre en exergue les potentialités et points d'améliorations avec le lien vers les métiers associés directement intégré dans l'ensemble. 

Version Cercles
![image](https://user-images.githubusercontent.com/7781917/75272653-96b55f80-57fe-11ea-8c2a-5b9234a3abbd.png)

Version escargot
![image](https://user-images.githubusercontent.com/7781917/75272671-a0d75e00-57fe-11ea-9e5f-04f31819ccc2.png)

**Comment by telohtrab** [comment]
> Pour moi incontestablement la première. Pour les couleurs, c'est qu'on passe du vert au bleu au gris au orange, on ne comprends pas qu'il y a une continuité de bonne maitrise à lacune. Peut être passer juste de différent niveau de vert à différents niveau de orange (mais vraiment le bleu et le gris ça colle pas pour moi)



Je viens seulement de voir ton message, je comprends mieux. Je vais essayer de faire un dégradé plus cohérent.

**Comment by telohtrab** [comment]
Version avec le dégradé de vert/gris pour clarifier la lecture :

![image](https://user-images.githubusercontent.com/7781917/75277160-d03e9880-5807-11ea-8a62-ffccd93526ca.png)

![image](https://user-images.githubusercontent.com/7781917/75277170-d46ab600-5807-11ea-90f8-dea277a6d07f.png)

**Comment by GaelleOttan** [comment]
Je trouve que visuellement c'est top. Par contre, il manque les éléments de mise en action:
- Sur les compétences de base: ne dispose pas des compétences de base -> proposition de formation compétences de base/ dispose des compétences de base -> proposition de formation et de métiers associés aux compétences transversales

**Comment by telohtrab** [comment]
C'est volontaire ! J'avais pris note de ces trucs sans avoir les wordings exacts pour les compétences transversales.

Pour les compétences de base, c'est un oubli pur et simple.

**Comment by Laurenmichel21** [comment]
Je trouve la première interessante visuellement. Cependant je trouve que la première partie compétence de base est compliqué à la lecture, avant même de comprendre j'ai deja plusieurs question qui me viennent en tête : y a t-il une logique dans les couleurs ? Les titres, les bulles ont-ils des liens ? Candidat écrit en orange , le titre aussi ? Une légende pour expliquer peut être ? Aussi pour la partie compétence transversale je ne comprend pas pourquoi les compétences comparaison / précision / attention son écris en bleu alors que les camembert sont en vert ?

**Comment by GaelleOttan** [comment]
Oui il faudrait une légende dans tous les cas, et d'ailleurs je trouve que la partie aide n'est pas suffisament démarquée du contenu de restitution. Pour les couleurs, le orange c'est insuffisant et donc à chaque fois que le candidat est en dessous de la moyenne, les points et les typos sont en orange. A mon avis pour l'écriture bleu sur les rond vert pale, c'est un oubli, il faudrait en effet que la couleur de la typo soit la même que les ronds associés

**Comment by Laurenmichel21** [comment]
Hello @telohtrab @laurenehoutin @Alexis-Akinyemi  voici les premiers retour terrain que l'on a eu jeudi sur la restitution (testé auprès de 3 conseillers) : 
**partie compétence de base** : 
- A quoi correspondent les couleurs des points ? (Orange et vert). 3/3
- Pourquoi cet ordre des points  dans le calcule pratique, les points orange sont en tête de liste  1/3
proposition => ajouter une légende 3/3
** Partie communication écrite**
-Pour une personne le pavé explication à droite n'a pas été compris. Pour les deux autres ce pavé est interessant pour mieux comprendre ce qu'il est important d'analyser. 
Proposition d'amélioration => ne pas reprendre la même couleur bleu pour le contour du pavé qui correspond à la moyen .
**Partie Graphique**
- le bouton "métier associé" n'a pas été vu par l'une d'entre elle 
- Le camembert a remporté 2 votes/3 
- Les 3 personnes ont bien compris l'analyse des couleurs en fonction des axes à travailler et des points fort 
propositions : 
1)il serait interessant de pouvoir rendre cliquable les compétences sur le graphique et de renvoyer sur les fiches associés à celle ci 
2) Les 3 personnes on suggéré de pouvoir faire le lien des compétences avec les MES ( ex : persévérance : Tri/contrôle/

**Comment by etienneCharignon** [comment]
A bien y réfléchir, je m'attends pas à ce que nous n'arrivions à produire la partie "compétences de bases" avant le mois de septembre. Aujourd'hui, nous n'avons pas du tout le concept de compétence de base dans l'application, mais mon estimation s'appuie surtout sur le résonnement suivant : il nous faudra refaire une campagne du type de crowdpanel et que celle que nous sommes en train de faire en est déjà à 3 mois. Peut-être que cette campagne se fera dans des conditions différences, en passant par des salons par exemple, mais je suis prêt a parier que cela nous prendra un temps comparable (tests, corrections des bugs, analyse des résultats, codage des règles, retour suite à la publication des résultats…). En fait, 3 mois, c'est même pour moi une projection optimiste.

Dans 3 mois, nous serons au début de l'été et comme dit le proverbe dans le métier : "qui prévois de finir en juin termine en septembre".

Bref, tout ça pour alimenter notre discussion de ce mercredi matin, il me semble qu'on pourrai gagner à diviser le sujet en plus petits morceaux car j'ai bien peur que dans 6 mois cet écran ne soit plus si adapté que ça à notre objectif.

**Comment by telohtrab** [comment]
Je vous propose de clore cette issue, cette restitution n'étant plus d'actualité suite aux nouveaux travaux d' @Alexis-Akinyemi et @laurenehoutin
