### ISSUE TITLE
Donner la possibilité à l'utilisateur de pouvoir passer la consigne

### ISSUE THREAD

**Issue by Laurenmichel21** [betagouv/eva#785]
contribue à #783

**Comment by francois2metz** [comment]
Est ce qu'il s'agit de passer la consigne la première fois ? Ou une fois qu'on la réécoute ? Une fois l’entraînement passé ? Une autre chose ?

**Comment by etienneCharignon** [comment]
De ce que j'ai compris, dans tous les écrans de consigne :
- le bouton doit être actif immédiatement. 
- quand on clique sur le bouton, ça coupe le son.

Écrans concerné : 
- Bonjour et bienvenue
- Consigne
- Bravo ! (la consigne de transition entre l'entrainement et la situation)
