### ISSUE TITLE
Ajouter les stats sur le site vitrine

### ISSUE THREAD

**Issue by Laurenmichel21** [betagouv/eva#793]
Communiquer en toute transparence sur nos statistiques. 

 - intégrer sur notre home dans le footer un lien statistiques vers une page stats.
 - Le contenu de la page de stat à afficher est la page "statistique d'usage" défini dans un autre ticket (#794)

contribue au gros sujet #692

**Comment by etienneCharignon** [comment]
Résolu par #22
