### ISSUE TITLE
Amélioration du raport Metabase existant "statistiques d'usage"

### ISSUE THREAD

**Issue by Laurenmichel21** [betagouv/eva#794]
- [x] le nombre total de structures depuis juillet 2019 en cumulée + total
- [x] histogramme des passations par situation
- [x] nombre de structures en cumulée + total 
- [x] Ajouter un filtre pour retirer les campagnes de test (`libelle` ne contient pas "test" et `code` ne contient pas "test" et la campagne "Démo")

contrinbu à #692

**Comment by etienneCharignon** [comment]
Reste à faire : 
- Ajouter un filtre pour retirer les campagne de test (`libelle` ne contient pas "test" et `code` ne contient pas "test" et la campagne "Démo")
-
