### ISSUE TITLE
Intégration du bouton de mesure de satisfaction en fin de parcours

### ISSUE THREAD

**Issue by GaelleOttan** [betagouv/eva#797]
Est rattaché au gros sujet #692 les indicateurs d'impact

A la place de Je donne mon avis, pour pouvoir avec des retours plus qualitatifs pour le comité, nous renvoyons vers un formulaire Typeform
https://evabetagouv.typeform.com/to/G988nO

**Comment by GaelleOttan** [comment]
@telohtrab tu peux mettre ici ta dernière maquette (j'ai pas retrouvé celle avec l'ampoule)

**Comment by telohtrab** [comment]
Et voici 
![image](https://user-images.githubusercontent.com/7781917/75667214-8e827780-5c77-11ea-80c6-20b175d561f2.png)

**Comment by GaelleOttan** [comment]
L'équipe dev, si vous pouvez essayer d'intégrer ce module de bas d'écran au plus tôt ce serait top, cela permettrait à Lauren de valider sur le terrain (cet aprem ou demain elle est en passation avec Alexis et Lauren) si il est visible et cliqué.

**Comment by telohtrab** [comment]
Mise à jour de l'icône ampoule un peu grossière sur la version précédente : 
![image](https://user-images.githubusercontent.com/7781917/75872686-e7d0df00-5e0e-11ea-9474-7ac0bd3945ec.png)

**Comment by etienneCharignon** [comment]
J’ai les interrogations suivantes : 
- Je me souviens que Benjamin a dit qu'il avait fait ça vit fait (dans l'urgence). Maintenant que l'échéance est passé, est-ce que @telohtrab tu veux revenir dessus ? 
- Que fait le bouton non ?
- Quel est l’impact sur la campagne crowdpanel en cours ?
- Est-ce que ce n’est pas un problème de nommer ce bouton “je donne mon avis” ?
- Qui retire de la valeur de ce bouton (par exemple, dans la forme “en tant que…, j’ai besoins de… pour obtenir quelque chose” qui est le “en tant que”) ? J'ai peur la réponse soit "en tant que projet". Le projet n'est pas sensé avoir de besoins propre. Peut-être "en tant que Dinum". Mais alors, pourquoi ne pas utiliser le bouton prévu par la Dinum ? Et peut-être que la réponse à ce dernier pourquoi permettra de mieux comprendre ce qu'on est en train de faire. (Pour être honnête, je crois que la réponse a été donnée quelque part, mais je ne sais pas où)

J'ai une dernière question pour laquelle j'ai une avis
- Est-ce que c’est seulement sur l’écran des compétences fortes ou aussi sur l’écran d’avant quand il n’y a pas de compétences fortes ? 
Mon avis : mettons le sur cet écran pour commencer, on verra si on le met à d'autres endroits plus tard.

**Comment by morissetcl** [comment]
- Concernant le bouton `non` pour moi ça affiche un bouton de déconnexion.
- Concernant le "qui retire valeur de ce bouton", j'ai l'impression que la description de cette issue y répond partiellement.
```
A la place de Je donne mon avis, pour pouvoir avec des retours plus qualitatifs pour le comité, nous renvoyons vers un formulaire Typeform
```
@GaelleOttan @Laurenmichel21  avez-vous des informations pour nous éclairer sur certaines des interrogation ci-dessus ?

**Comment by telohtrab** [comment]
Hello Etienne, 

Il a effectivement été fait rapidement, mais j'ai tout de même eu le temps d'échanger avec Gaëlle et Lauren pour m'assurer qu'il remplissait le besoin coté métier. 

Le bouton "Je donne mon avis" et le bouton "Non" font essentiellement la même chose coté produit : ils cachent cette petite popup pour laisser apparaître "dessous" le bouton "Deconnexion". 

Le bouton "Je donne mon avis" a de spécifique, qu'en plus de ça, il ouvre le lien vers le typeform dans un nouvel onglet.
