### ISSUE TITLE
Design: nouveau dessin/ intégration pour compléter la MES 2 illettrisme Livraison

### ISSUE THREAD

**Issue by Alexis-Akinyemi** [betagouv/eva#804]
Voici les ajouts que nous proposons, en reprenant le tableau initial
Les ajouts sont indiqués par "AJOUT" dans la colonne de gauche

Consigne de départ :

_Vous êtes chargé.e des livraisons dans le parc. Vous devez effectuer les livraisons, mais vous rencontrez certaines contraintes : des mots sont par exemple effacés sur les colis, sur les pancartes qui vous indiquent le chemin, ou vous entendez mal vos interlocuteurs. Vous devez donc retrouver les mots manquants._

   <tr>
   <td>n° Essai

   </td>
   <td>Partie A

   </td>
   <td>Partie B

   </td>
   <td>Catégorie

   </td>
  </tr>
   <td colspan="3" >_Début de la tournée_

   </td>
   <td>
   </td>
  <tr>
   <td>**AJOUT

   </td>
   <td>Vous recevez un appel de votre supérieur (image d’une personne avec un badge "directeur.trice du parc d'attraction" ou un truc du genre) dit «  Vous avez 5 jours pour livrer 210 colis. Combien allez-vous devoir en livrer en une journée ?"

   </td>
   <td>Que répondez-vous à votre supérieur ?

*   82
*   62
*   22
*   32
*   42
*   102**
   </td>
   <td>
numératie

   </td>
  </tr>
  <tr>
   <td>1

   </td>
   <td>_Pour commencer votre tournée, vous devez lire les instructions qui vous ont été laissées._

_[Feuille tachée de café avec écrit : commencez votre tournée en livrant les colis de la pile de gauche. ... , il faut tous les livrer avant 12h !]_

   </td>
   <td>_Quel texte est effacé ?_

*   _Faites vite_
*   _Stop_
*   _Reculez_
*   _Eloignez-vous des bordures_
   </td>
   <td>
CO&COM

   </td>
  </tr>
  <tr>
   <td>AJOUT

   </td>
   <td>_Vous recevez un appel de votre supérieur.e : _

J’ai l’impression que cette palette est complète ». Chaque carton contient 12 colis. Combien y a t-il de colis au total ?" \
**Reprise de la platte avec les cartons de bureau ** \

   </td>
   <td>Quel nombre de colis allez-vous transmettre à votre supérieur.e

*   72
*   64
*   68
*   54
*   80
   </td>
   <td>
   </td>
  </tr>
  <tr>
   <td>
2

   </td>
   <td>_Après avoir chargé les colis dans votre camion, vous commencer à rouler pour effectuer votre livraison._

_[Panneau de circulation avec :_

Vitesse ... à 30 km/h]

   </td>
   <td>_Quel est le mot effacé ?_

*   _Limité_
*   _Limitée_
*   _Limmitté_
*   _Limmittée_
   </td>
   <td>
S&O

   </td>
  </tr>
   <td colspan="3" >_Le joueur arrive dans le parc et effectue la première livraison_

   </td>
   <td>
   </td>
  <tr>
   <td>3

   </td>
   <td>_Vous allez livrer votre premier colis. Voici les instructions._

[Instructions sur le colis avec une partie mal imprimée : Déposer le colis au *** de poste]

   </td>
   <td>_Quel est le mot effacé ?_

*   _Bureau_
*   _Buro_
*   _Burreau_
*   _Burro_
   </td>
   <td>
S&O

   </td>
  </tr>
  <tr>
   <td>4

   </td>
   <td>_Vous arrivez bureau de poste, et il y a un mot sur la porte._

[Post-it sur la porte avec bout déchiré : Ne pas frapper à la porte, ou le chien va ....]

   </td>
   <td>_Quel est le mot manquant ?_

*   _Aboyer_
*   _Aboyé_
*   _Haboyer_
*   _Haboyé_
*   _Aboiyé_
*   _Aboiyer_
   </td>
   <td>
S&O

   </td>
  </tr>
  <tr>
   <td>5

   </td>
   <td>_Vous remettez le carton à la postière du parc._

[Sur un carton, étiquette rouge avec :

…, fragile]

   </td>
   <td>_Quel est le mot qui a disparu ?_

*   _Attention_
*   _Livré_
*   _Repère_
   </td>
   <td>
CO&COM

   </td>
  </tr>
  <tr>
   <td>6

   </td>
   <td>_La postière vous invite à rester prendre le café._

[Bulle : Vous voulez rester pour café ? On allait le boire en équipe]

_Vous répondez : Non, merci ***_

   </td>
   <td>_Vous répondez :_

*   _Monsieur_
*   _Madame_
*   _Vous_
   </td>
   <td>
CO&COM

   </td>
  </tr>
   <td colspan="3" >_Le joueur va vers sa seconde livraison_

   </td>
   <td>
   </td>
  <tr>
   <td>7

   </td>
   <td>_Alors que vous sortez de la poste du parc, un visiteur du parc qui s’est perdu vous interpelle :_

[Bulle avec : Excusez-moi ... vous déranger.]

   </td>
   <td>_Quel est le mot que vous n’avez pas bien entendu ?_

*   _de_
*   _par_
*   _le_
*   _à_
*   _pour_
   </td>
   <td>
S&O

   </td>
  </tr>
  <tr>
   <td>8

   </td>
   <td>_[Le même personnage, même image, dans la bulle : _... est le zoo, s’il vous plaît ? Je voudrais aller voir le repas des lions, il parait que c’est super !_]_

   </td>
   <td>_Quel est le mot que vous n’avez pas bien entendu ?_

*   _Où_
*   _Quand_
*   _Si_
*   _Quoi_
*   _Comment_
   </td>
   <td>
CO&COM

   </td>
  </tr>
  <tr>
   <td>9

   </td>
   <td>_Vous regardez l’adresse sur le prochain colis._

[Bureaux administratifs - Bureau 48

Consigne spéciale : Même si la livraison concerne le bureau 48, déposer le colis au bureau 49 à ***_]_

   </td>
   <td>_Quel est le mot manquant ?_

*   _Droite_
*   _Devant_
*   _Dehors_
   </td>
   <td>
CO&COM

   </td>
  </tr>
  <tr>
   <td>10

   </td>
   <td>_Vous reprenez la route vers les bureaux administratifs._

[ Vue depuis l’intérieur de la voiture, la voiture fait face à une barrière avec un panneau - mot caché par un pull laissé sur le panneau - : Entrée .... au public]

   </td>
   <td>_Quel est le mot caché ?_

*   _Indisponible_
*   _Interdite_
*   _Insoluble_
   </td>
   <td>
CO&COM

   </td>
  </tr>
  <tr>
   <td>11

   </td>
   <td>_Vous déposez le colis au bureau 49._

[Une personne avec une bulle :

Bonjour ! Merci beaucoup, le colis est pour ma collègue mais elle est ..., alors je vais le garder jusqu’à son ...”

   </td>
   <td>_Quels sont les mots qui manquent ?_

*   _malade ; retour_
*   _absente ; malade_
*   _malade ; vacances_
   </td>
   <td>
CO&COM

   </td>
  </tr>
  <tr>
   <td>AJOUT

   </td>
   <td>Vous recevez un appel de votre supérieur : « Combien vous reste-t-il de colis à livrer ? » \
Écrit sur un compteur quelque part sur l'écran : Nombre de colis au départ : 42. Nombre de colis déjà livrés : 13.

   </td>
   <td>Quel est le code d’entrée du zoo ?

*   29
*   17
*   45
*   53
*   66
   </td>
   <td>
   </td>
  </tr>
   <td colspan="3" >
_Le joueur arrive à la troisième livraison_

   </td>
   <td>
   </td>
  <tr>
   <td>12

   </td>
   <td>_Pour votre livraison au zoo, vous devez livrer plusieurs colis, ce qui pèse très lourd. Un employé vous propose son aide._

[Bonjour ! Vous avez besoin d’aide ? Je peux vous aider à ... les cartons.]

   </td>
   <td>_Quel est le mot que vous n’avez pas bien entendu ?_

*   _Porter_
*   _Porté_
*   _Portez_
*   _Portais_
*   _Portait_
   </td>
   <td>
S&O

   </td>
  </tr>
  <tr>
   <td>13

   </td>
   <td>_Avant d'entrer dans le zoo, vous arrivez face à un panneau._

[Panneau en question : Attention … la marche après la porte.]

   </td>
   <td>_Quel est le mot manquant sur ce panneau ?_

*   _à_
*   _de_
*   _le_
   </td>
   <td>
S&O

   </td>
  </tr>
  <tr>
   <td>AJOUT

   </td>
   <td>Vous recevez un appel de votre supérieur : 

“J’ai oublié de vous donner le code d’entrée du zoo. En fait je ne m’en souviens plus, mon assistant a noté 57*102.”  \

   </td>
   <td>Quel est le code de la porte ?

*   58140
*   572
*   5814
*   581
*   57210
   </td>
   <td>
numératie

   </td>
  </tr>
  <tr>
   <td>14

   </td>
   <td>_Vous lisez la consigne sur un des colis._

[ Consigne spéciale : Ces colis ***** de la viande pour les tigres, ne pas les déposer devant la cage.]

   </td>
   <td>_Quel est le mot effacé ?_

*   _Contiennent_
*   _Apprennent_
*   _Tiennent_
*   _Gère_
   </td>
   <td>
CO&COM

   </td>
  </tr>
  <tr>
   <td>15

   </td>
   <td>[Devant la cage des éléphants, à gauche une porte pour entrer dans la cage, à droite un chemin avec un message écrit au marqueur sur une feuille :

Pour contourner la cage, … par ici.]

   </td>
   <td>_Quel est le mot effacé ?_

*   _passez,_
*   _poussez,_
*   _palliez,_
*   _pacez._
   </td>
   <td>
CO&COM

   </td>
  </tr>
  <tr>
   <td>16

   </td>
   <td>_Vous remettez le colis à la personne au destinataire._

[Bulle : Merci ! Puisque vous êtes là, pouvez-vous déposer ce colis au Grand ****, s’il vous plaît ? Je n’ai pas une minute à moi aujourd’hui !”

   </td>
   <td>_Quel est le mot que vous n’avez pas entendu ?_

*   _chateau_
*   _chapeau_
*   _chapiteau_
*   _chapitot_
*   _chariot_
   </td>
   <td>
S&O

   </td>
  </tr>
  <tr>
   <td>AJOUT

   </td>
   <td>Mot sur une porte avec écrit : je suis absente. \

Vous venez voir Madame Lucette pour lui livrer un colis mais elle est absente. Laissez lui un mot pour lui expliquer que vous êtes passé et qu'elle devra aller chercher son colis au bureau de poste (en respectant les règles de politesse).

   </td>
   <td>
   </td>
   <td>Litératie 

   </td>
  </tr>
   <td colspan="3" >_Fin_

   </td>
   <td>
   </td>

**Comment by GaelleOttan** [comment]
Mes remarques/ proposition: 

Pour la question 2 (ajout l'appel du boss avec la palette) je trouve que c'est compliqué que le boss passe des appels pour demander de compter les cartons sur les palettes (qui ne sont pas devant ses yeux). On ne peut pas plutôt mettre cet ajout à la toute fin en disant "à la fin de votre matinée de livraison vous rentrez à l'entrepot et vous rencontrez votre boss qui vous demande.... 
+ 
ça permettrait d'enchainer sur le module de communication écrite où l'on pourrait récupérer ce que l'on a déjà avec la collègue qui se pète la gueule dans l'entrepot?

**Comment by telohtrab** [comment]
Bon je suis désolé mais je m'en sors pas entre les différentes issues, scénarios et modifications. J'attends donc une description finale pour livraison et lost phone avant d'attaquer le parcours "final". 

Comme j'intègre en même temps les dessins de Matthieu, je préfère avoir tout d'un coup :)

Je ferai mes remarques et retours sur le parcours quand je les aurai mappées sur les écran, en l'état j'avoue être un peu perdu.

**Comment by GaelleOttan** [comment]
@telohtrab là ce n'est pas lost phone mais livraison. Pour intégrer numératie et littératie, on l'a dilué dans Livraison (ce ticket) et Lost phone. 
Ici c'est donc à rajouter à la maquette existante (et déjà intégré dans l'admin de livraison)

**Comment by GaelleOttan** [comment]
Mais oui il faut d'abord attendre la validation @Alexis-Akinyemi et Laurene pour savoir si ils sont ok avec ma proposition avant que tu intègres ces écrans dans livraison

**Comment by GaelleOttan** [comment]
Pour les dessins de matthieu, je trouverais ça plus simple que tu intègre les nouveaux écrans pour savoir exactement ce dont on a besoin comme dessin (à mon avis seulement rajouter le boss à côté de la palette qui existe déjà) mais j'ai besoin de le voir pour bien saisir quoi dessiner exactement...

**Comment by telohtrab** [comment]
Oui oui je sais qu'on est sur Livraison ici et qu'il y a un bout dans Lost Phone :-) 
Mais ma remarque était plus générale à l'addendum qu'on fait aux deux situations, pour la première fois, je m'y retrouve vraiment pas dans les conversations ici. 

C'est pour ça que je demandais une version "validée" écrite pour chacune des deux situations pour avancer tranquillement sans craindre de modifs.

**Comment by telohtrab** [comment]
Pour les dessins, comme j'étais en attente du descriptif ici, j'ai profité de ce temps pour commencer à intégrer ce que Matthieu à livrer, c'est tout

**Comment by telohtrab** [comment]
J'ai avancé un peu ce matin dans l'intégration, je suis sur un autre projet cet après-m. 
Pour info je me remets là-dessus demain matin.

**Comment by GaelleOttan** [comment]
OK je comprends donc on attends les retours d'alexis et Laurene sur les deux sénarios finalisés et si besoin on fait un point ensemble demain matin

**Comment by Alexis-Akinyemi** [comment]
Ok pour nous, ça peut le faire on placerait donc tous les appels du patron à la fin, et on sépare les deux parties par une page de transition ? Je propose que l'on valide tout ça tous les trois pendant notre call et si besoin on refait la liste. Pour l'écran de transition on a déjà un dessin de Matthieu ?

**Comment by GaelleOttan** [comment]
Pour moi c'est suffisant de mettre à la fin seulement l'appel du patron (celui où il demande si la palette est complète, les autres pour moi ça fonctionne dans le scénario). Pour moi ça reste une seule et même partie, la journée de livraison (je cherche à garder l'histoire la plus cohérente possible sans rajouter de la charge de travail niveau design et intégratio). Du coup je ne pense  pas qu'on est besoin d'un dessin de Matthieu (peut-être un ajustement où on placerait le boss à côté du dessin de la palette existant). (modifi

**Comment by Alexis-Akinyemi** [comment]
Parce que c'était plus facile, voici le doc sur [gdrive](https://docs.google.com/document/d/1pitnfXChtoKL2gJrRQYpzyTn7uH8lkp_ukl8pyapw9c/edit ) :

**Comment by GaelleOttan** [comment]
@MatthieuMARTIN on aurait besoin de deux nouveaux petits dessins pour finaliser complètement le parcours de livraison. Est ce que tu peux nous faire: 
-> Un dessin d'un boss dans un bureau qui passe un appel avec une bulle de texte (il y aura trois version de texte différente). Peut être réutiliser le cadre que tu as déjà produit avec un perso derrière un bureau en changeant le perso?
-> reprendre le dessin de la palette seule que l'on a depuis longtemps (celui de la situation bureau où il y a un fond gris) et ajouter un boss à côté de la palette + un fond flou (sans détail) pour contextualiser un entrepot

**Comment by telohtrab** [comment]
@MatthieuMARTIN @GaelleOttan @Alexis-Akinyemi  J'ajoute une variante de dessin pour la question ajoutée après la 11 ici : https://docs.google.com/document/d/1pitnfXChtoKL2gJrRQYpzyTn7uH8lkp_ukl8pyapw9c/edit

En effet, le supérieur est au téléphone, mais il est indiqué qu'on est sensé voir sur l'écran des nombres de Colis. Vous voyez la petite incohérence ?

**Comment by telohtrab** [comment]
![Livraison0Consigne](https://user-images.githubusercontent.com/7781917/76306715-b9984700-62c7-11ea-9183-e867a6079968.png)
![Livraison1](https://user-images.githubusercontent.com/7781917/76306716-ba30dd80-62c7-11ea-8189-cde59d285637.png)
![Livraison2](https://user-images.githubusercontent.com/7781917/76306717-ba30dd80-62c7-11ea-9999-ba8e00d0d4de.png)
![Livraison3](https://user-images.githubusercontent.com/7781917/76306718-bac97400-62c7-11ea-87fb-9c9e68305510.png)
![Livraison4](https://user-images.githubusercontent.com/7781917/76306720-bac97400-62c7-11ea-94ee-c3df39de7aa9.png)
![Livraison5](https://user-images.githubusercontent.com/7781917/76306721-bac97400-62c7-11ea-9829-0b47bf0ef7cc.png)
![Livraison6](https://user-images.githubusercontent.com/7781917/76306723-bb620a80-62c7-11ea-941b-02235c6cbe71.png)
![Livraison7](https://user-images.githubusercontent.com/7781917/76306725-bbfaa100-62c7-11ea-9568-16c4cac441be.png)
![Livraison8](https://user-images.githubusercontent.com/7781917/76306726-bbfaa100-62c7-11ea-9e34-4bf739b68938.png)
![Livraison9](https://user-images.githubusercontent.com/7781917/76306727-bc933780-62c7-11ea-8ecd-7e0b53563492.png)
![Livraison10](https://user-images.githubusercontent.com/7781917/76306728-bc933780-62c7-11ea-8b0e-c296086c17de.png)
![Livraison11](https://user-images.githubusercontent.com/7781917/76306730-bc933780-62c7-11ea-821d-2d13246e3ec4.png)
![Livraison12](https://user-images.githubusercontent.com/7781917/76306731-bd2bce00-62c7-11ea-81db-922c030f429f.png)
![Livraison13](https://user-images.githubusercontent.com/7781917/76306733-bd2bce00-62c7-11ea-9256-574133aee2d1.png)
![Livraison14](https://user-images.githubusercontent.com/7781917/76306736-bdc46480-62c7-11ea-8e86-8a4f48d4d6b9.png)
![Livraison15](https://user-images.githubusercontent.com/7781917/76306738-bdc46480-62c7-11ea-99b7-a7ef99f353be.png)
![Livraison16](https://user-images.githubusercontent.com/7781917/76306739-be5cfb00-62c7-11ea-8b9d-738941c9e93b.png)
![Livraison17](https://user-images.githubusercontent.com/7781917/76306741-be5cfb00-62c7-11ea-8188-38d93ac6da57.png)
![Livraison18](https://user-images.githubusercontent.com/7781917/76306742-bef59180-62c7-11ea-96a0-3f0e5db2524d.png)
![Livraison19](https://user-images.githubusercontent.com/7781917/76306743-bef59180-62c7-11ea-86d5-4f297863e19e.png)
![Livraison20](https://user-images.githubusercontent.com/7781917/76306744-bf8e2800-62c7-11ea-9afe-de4d1da2ae5d.png)
![Livraison21](https://user-images.githubusercontent.com/7781917/76306745-bf8e2800-62c7-11ea-9104-587ac43a954d.png)


Voici les questions intégrées à Livraison, avec les écrans "UX" des nouvelles questions.

**Comment by MatthieuMARTIN** [comment]
Je vous propose ceci pour les images demandées.
Pour les bulles, c'est moi qui les fait ? Vous me donnez les textes ? 

![19-boss-bureau-telephone](https://user-images.githubusercontent.com/58987553/76434131-9350d500-63b5-11ea-96bd-d40258f3131b.jpg)
![20-palette-et-boss](https://user-images.githubusercontent.com/58987553/76434138-93e96b80-63b5-11ea-8dad-cf77b57eac14.jpg)

**Comment by GaelleOttan** [comment]
@telohtrab voilà les images de matthieu, est ce que c'est toi qui intègre les textes dedans en les rajoutant dans figma? (dans ce cas Il me faudra aussi les ajouts dans drive pour les charger dans livraison)

**Comment by telohtrab** [comment]
Comme vous voulez, c'est Matthieu qui l'a fait sur le reste mais s'il ne
peut pas je vais m'en charger !

Benjamin Bartholet

TRΔB design & inks

website : trab.design
tw : @trab_ink
ig : @trab_ink

Le jeu. 12 mars 2020 à 09:36, GaelleOttan <notifications@github.com> a
écrit :

**Comment by GaelleOttan** [comment]
yes, si tu as le temps de t'en occuper auj ça serait top comme ça je pourrais finaliser l'intégration des images dans la situation pour les tests début de semaine pro

**Comment by telohtrab** [comment]
Mince il me semblait avoir relevé ça quelque part, je m'en sors pas trop entre toutes les issues. 

L'image de la question 13 ci-dessus implique qu'on est sensé voir des "nombre de colis au départ et déjà livrés" dans l'image. Or, le dessin de Matthieu n'est pas vraiment utilisable en l'état pour cette question ci

**Comment by telohtrab** [comment]
@MatthieuMARTIN Tu peux mettre ta source et ton export sur Drive ? Merci !

**Comment by telohtrab** [comment]
Voici les images, comme vous le voyez il me manque donc les indications de colis sur la 13 (écrit en rouge ici) et une bulle sur l'image palette.

![Livraison1](https://user-images.githubusercontent.com/7781917/76511421-74a11b80-6453-11ea-8690-1714a882be77.png)
![Livraison13](https://user-images.githubusercontent.com/7781917/76511424-7539b200-6453-11ea-9b70-fb7d4cd5c475.png)
![Livraison16](https://user-images.githubusercontent.com/7781917/76511425-75d24880-6453-11ea-8f6f-6dd1ee41c654.png)
![Livraison20](https://user-images.githubusercontent.com/7781917/76511426-75d24880-6453-11ea-82e7-341ae77535e9.png)

**Comment by MatthieuMARTIN** [comment]
@telohtrab c'est dans le drive ! ici : 
![image](https://user-images.githubusercontent.com/58987553/76511314-50ddd580-6453-11ea-8bda-b19eaae92382.png)

Merci de t'occuper des textes, 

Pour la question 13, je ne sais pas de quelle image il s'agit, je suis un peu perdu, si tu m'expliques ce qu'il faut faire je veux bien modifier l'image aujourd’hui j'ai du temps ! 

A+

**Comment by telohtrab** [comment]
Les images sont ci-dessus, du coup ;)

**Comment by MatthieuMARTIN** [comment]
AAAAh ok, je fais le compteur dans la journée ! On a posté en même temps ^^

**Comment by MatthieuMARTIN** [comment]
@telohtrab @GaelleOttan 
On peut faire un truc comme ça pour l'info qu'il manque question 13 si vous voulez ? 
J'ai maj le psd sur le drive, 
( pour faire apparaître ou disparaître la main avec le papier c'est simplement le premier dossier dans les calque à afficher ou non. ) 
![19-boss-bureau-telephone-+-main](https://user-images.githubusercontent.com/58987553/76518741-f4cd7e00-645f-11ea-9b58-daa849949932.jpg)

**Comment by telohtrab** [comment]
C'est surtout avec @Alexis-Akinyemi et @laurenehoutin qu'il faut voir si c'est pas trop évident pour répondre à la question :)

**Comment by telohtrab** [comment]
Il me manque la bulle sur l'image avec la palette également :)

**Comment by laurenehoutin** [comment]
Hello, ça ne me parait pas forcément plus évident. Ce qui compte c'est qu'on donne les infos (colis au départ et colis livré). Après comme j'arrive en fin de conversation, je ne perçois peut être pas le bon problème, dites moi.

**Comment by telohtrab** [comment]
J'avais cru comprendre que les infos devaient être "disséminées" dans l'image sans forcément être au premier plan selon vos indications :)

Par ailleurs, plutôt narrativement, on est sensé être au téléphone avec le boss, donc c'est la main de qui ? Ahah

**Comment by MatthieuMARTIN** [comment]
sinon comment on fait sans la main ? on fait un encart à gauche de sa tête et on écrit les infos dessus ? 
Moi j'veux bien, faut me dire quoi faire :) 

@telohtrab 
Je te MAJ l'image de la palette sur le drive avec une bulle.

**Comment by MatthieuMARTIN** [comment]
sinon comment on fait sans la main ? on fait un encart à gauche de sa tête et on écrit les infos dessus ?
Moi j'veux bien, faut me dire quoi faire :)

@telohtrab
J'ai MAJ l'image de la palette sur le drive avec la bulle.

![20-palette-et-boss](https://user-images.githubusercontent.com/58987553/76619982-77bc0a80-652c-11ea-806c-834263d29940.jpg)

**Comment by Alexis-Akinyemi** [comment]
Hello, 
Effectivement on a pas gardé de trace écrite sur gdoc de la toute dernière réorga donc Laurène en était resté à l'étape on on pensait remettre tous les écrans du boss à la fin.
Là du coup on a un problème effectivement, initialement on pensait que l'écran serait coupé en deux avec en haut le dessin du  boss  dans son bureau et en bas le dessin de l'intérieur du camion de livraison. Les chiffres des colis déjà livrés et colis restants y seraient affichés sur le tableau de bord (sur un post-it comme ici ou d'une autre manière). Est-ce que c'est possible de faire comme cela ?

**Comment by GaelleOttan** [comment]
@MatthieuMARTIN est ce que tu peux faire les modifs proposées par alexis cet aprem et tout mettre dans le drive? Je vais intégrer les images ce weekend pour que ce soit opérationnel début de semaine prochaine ;)

**Comment by MatthieuMARTIN** [comment]
Images MAJ sur le drive ! 
![20-palette-et-boss](https://user-images.githubusercontent.com/58987553/76640874-f7f46700-6550-11ea-85bb-3f4815b90f06.jpg)
![21-palette-et-boss](https://user-images.githubusercontent.com/58987553/76640876-f9259400-6550-11ea-92bd-cd231b6c05f6.jpg)

**Comment by MatthieuMARTIN** [comment]
Images maj sur le drive ! 
![20-palette-et-boss](https://user-images.githubusercontent.com/58987553/76641034-3a1da880-6551-11ea-95cd-ffcd1ac588eb.jpg)
![21-palette-et-boss](https://user-images.githubusercontent.com/58987553/76641037-3be76c00-6551-11ea-969d-9952df5a996c.jpg)

**Comment by MatthieuMARTIN** [comment]
C'est fait, c'est sur le drive,
![20-palette-et-boss](https://user-images.githubusercontent.com/58987553/76641191-7c46ea00-6551-11ea-89c4-c1df1952034b.jpg)
![21-palette-et-boss](https://user-images.githubusercontent.com/58987553/76641193-7d781700-6551-11ea-935b-be90532b2da1.jpg)

**Comment by telohtrab** [comment]
Hello !

Bon j'ai exporté toutes les images avec les textes, et je signale par la même occasion que Figma est pas hyper pratique pour exporter 2 Calques "applatis" sans les applatir sur beaucoup d'écrans en même temps. Donc si on peut faire ça sur Photoshop la prochaine fois ça m'arrangera ^^ @MatthieuMARTIN 

Tout se trouve donc ici @GaelleOttan : 
![image](https://user-images.githubusercontent.com/7781917/76646266-f7f96480-655a-11ea-956a-295e4305b0c5.png)

**Comment by GaelleOttan** [comment]
@telohtrab il me manque juste cette image avec le texte pour l'ajout entre la question 13 et 14: 
Vous recevez un appel de votre supérieur : 
“J’ai oublié de vous donner le code d’entrée du zoo. En fait je ne m’en souviens plus, mon assistant a noté 57*102.”

**Comment by telohtrab** [comment]
Oups, avec les soucis d'export de Figma (qui est très pratique par ailleurs mais CE CAS précis d'image + texte au dessus plus petit que l'écran est chiant) c'est passé entre les gouttes. 

Elle est remplacée dans le dossier ! 

![Livraison16](https://user-images.githubusercontent.com/7781917/76744543-af1cf800-6774-11ea-9bca-f45251b62dbd.png)

**Comment by Alexis-Akinyemi** [comment]
Hello, à voir l'image j'ai l'impression que "mon assistant a noté 57 multiplié par 102" est plus clair que la version actuelle. Puisqu'en étant très pointilleux on pourrait dire que "*" relève plus des compétences numériques que de la numératie. Et le remplacer par un "x" pourrait générer de la confusion (à confirmer). Donc on préconise soit "x" soit "multiplié par"  :)
