### ISSUE TITLE
Favoriser la deconnexion des évalués en fin de parcours

### ISSUE THREAD

**Issue by etienneCharignon** [betagouv/eva#812]
En fin de parcours, après avoir choisi ou non de donner son avis, ajouter un bouton permettant de se déconnecter.

Intention : augmenter les chance que les évalués se déconnectes et ainsi ne laisse pas l'évaluer suivant voir leur résultat et la fin du parcours.

On veut aussi s'assurer que les évalués ne se déconnectent pas trop vite. Car on veut qu'ils aient la possibilité d'aller regarder les propositions de métiers et qu'ils lisent les compétences fortes. Il faut que ce bouton contienne une confirmation de déconnexion qui les prévienne qu'ils vont quitter l'écran et qu'il ne pourrons plus y revenir.

**Comment by etienneCharignon** [comment]
Je me me demande si on ne pourrais pas tout simplement revenir à la solution sans bouton mas avec une déconnexions automatique 5 minutes après l'affichage de cet écran. (on pourrait calibrer cette durées en fonction de ce qui se passe lors des tests (combien de temps s'écoule t'il entre deux évaluations).

**Comment by shanser** [comment]
je crois que cette issue fait suite à ton commentaire https://github.com/betagouv/eva/pull/811#issuecomment-596970510 qui remet en cause la proposition de Benjamin.
Ca m'importe qu'on se mette d'accord sur la solution qu'on veut implémenter avant de commencer à développer.

**Comment by etienneCharignon** [comment]
@telohtrab est-ce que tu peux nous aider sur la confirmation de la déconnexion ? Est-ce que ça répond bien au besoin ? Comment on pourrait l'afficher ?

**Comment by etienneCharignon** [comment]
Je répond à ma propre question : 
> Je me me demande si on ne pourrais pas tout simplement revenir à la solution sans bouton mais avec une déconnexions automatique 5 minutes après l'affichage de cet écran. (on pourrait calibrer cette durées en fonction de ce qui se passe lors des tests (combien de temps s'écoule t'il entre deux évaluations ?).

En fait, l'un n’empêche pas l'autre (on peut faire le bouton et le timeout). Par contre, on a bien besoins du bouton pour adresse le retour utilisateur qui disais que les gens ne se rendaient pas bien compte qu'ils avaient terminé.

**Comment by telohtrab** [comment]
Je ne comprends pas la question. C'est la présence même du bouton de déconnexion qui est en question ou le popup de confirmation ?

**Comment by etienneCharignon** [comment]
Pardon pour la confusion. Je propose que le bouton soit là comme tu l'a proposé, mais que ce bouton ouvre sur une confirmation. Qu'est-ce que tu pense d'ajouter cette confirmation ? Et comment on pourrait la faire ?

**Comment by telohtrab** [comment]
La confirmation me paraît être une bonne solution, avec un wording/audio qui demande à l'utilisateur s'il a bien pris connaissance de ses potentialités ? 

Voici ma proposition qui reprend de manière presque identique le module pour le bouton "je donne mon avis" hors changement de couleurs 

@GaelleOttan @laurenehoutin @Alexis-Akinyemi pour voir le wording à appliquer ici
![image](https://user-images.githubusercontent.com/7781917/76746081-34a1a780-6777-11ea-8a34-fb272c377028.png)

**Comment by telohtrab** [comment]
Voici une update de l'icône et du wording après discussion avec Etienne

![image](https://user-images.githubusercontent.com/7781917/76754367-52283e80-6782-11ea-8f47-96c080d50ec4.png)

**Comment by etienneCharignon** [comment]
@laurenehoutin est-ce que tu peux aussi nous donner ton avis sur cet écran ci ? En particulier, est-ce que ton pouce vers le haut de l'écran précédent était attaché au fait de parler des potentiels ?

**Comment by laurenehoutin** [comment]
Hello, oui je peux. Mon pouce signifiait pour moi c'était bien. L'idée de parler de potentiels (et pourquoi pas de métier associés en plus) me paraissait cohérent avec la démarche et clair pour les utilisateurs.
Là, pour moi, c'est moins clair : 
- "terminer une session" ne me parait pas français
- quitter l'application = quelle conséquence pour eux ?

**Comment by etienneCharignon** [comment]
Ok, merci Laurène pour ton retour. Ça me convainc de partir plutôt sur le premier écran (celui qui dit "avez vous bien pris connaissance de vos potentiels").
