### ISSUE TITLE
Objets Trouvés : Corriger des bug de texte dans les écrans

### ISSUE THREAD

**Issue by etienneCharignon** [betagouv/eva#845]
Application message: corriger l'ordre des écrans : 
voir l'ordre dans le document https://docs.google.com/document/d/1pitnfXChtoKL2gJrRQYpzyTn7uH8lkp_ukl8pyapw9c/edit page 11 et 12

Ecran 4.1 : Application message

un message de Dounia : "Je serai sur un banc près de l'entrée **du parc**, viens".

Ecran 4.3 : application message

SMS de Lindsay (hier à 11h20) : bonjour, tu devras t'occuper demain d'un groupe de 17 enfants, **puis** un autre de 26, et **enfin** un autre de 32.

Choix des derniers écrans de la fin : 

Pour lui dire que le planning a été modifié et qu'elle doit prendre votre poste cet après-midi
Pour lui demander son aide dans la conception du planning de l’équipe
Pour lui dire de vous accompagner à une activité dans le parc
Pour lui demander de bien vouloir vous proposer des dates pour une réunion

**Comment by etienneCharignon** [comment]
@telohtrab pour les deux corrections suivantes il faut reprendre les images. Est-ce que tu peux les corriger et les ré-exporter steuplai ?

(J'ai mis en gras le texte à changé pour le mettre en évidance, mais il ne faut pas qu'il soit en gras dans l'image final.)

> Ecran 4.1 : Application message
>
> un message de Dounia : "Je serai sur un banc près de l'entrée **du parc**, viens".
> 
> Ecran 4.3 : application message
> 
> SMS de Lindsay (hier à 11h20) : bonjour, tu devras t'occuper demain d'un groupe de 17 enfants, **puis** un autre de 26, et **enfin** un autre de 32.

**Comment by telohtrab** [comment]
Voici les images corrigées, toujours dans le même dossier Drive. J'attends des nouvelles de Matthieu pour mettre à jour les avatars manquants.

![ObjetsTrouvés11](https://user-images.githubusercontent.com/7781917/77782237-3d3b8d00-7057-11ea-86bd-0d8027ac3884.png)
![ObjetsTrouvés12](https://user-images.githubusercontent.com/7781917/77782239-3dd42380-7057-11ea-904e-4ed79220d08c.png)
