### ISSUE TITLE
Objets trouvés : Intégrer les nouvelles images

### ISSUE THREAD

**Issue by etienneCharignon** [betagouv/eva#854]
Pour info, @telohtrab  vient de recevoir, d'intégrer et d'exporter les éléments finaux de @Matthieu MA:
- Sur l'écran de l'app Photos : badge de Denis plus gros et normalement plus lisible
- Sur les 3 écrans des apps SMS, j'ai légèrement modifié la présentation des avatars pour que les personnages soit plus différenciables et ils sont désormais tous dessinés. 
Le tout a été exporté dans le même dossier des Fonds d'ObjetsTrouvés

**Comment by telohtrab** [comment]
Merci Etienne, je n'avais pas vérifié si vous aviez une issue associée déjà.
