### ISSUE TITLE
Objets trouvés : revoir le texte de transition qui dit aujourd'hui qu'on peut "continuer" alors qu'on a pas "commencé"

### ISSUE THREAD

**Issue by etienneCharignon** [betagouv/eva#862]

**Comment by etienneCharignon** [comment]
Je découvre qu'un partie du problème vient du fait qu'il manque l'écran de dévérouillage… 😥

**Comment by shanser** [comment]
L'écran de verrouillage étant développé, il reste désormais à avoir une discussion avec @telohtrab sur ce qu'on affiche.

**Comment by telohtrab** [comment]
Coucou ! Désolé c'était passé entre les gouttes. 

Voici ma proposition (mise à jour sur Figma) : 
![image](https://user-images.githubusercontent.com/7781917/79762062-87e0ba00-8322-11ea-8e59-200882e94df7.png)
