### ISSUE TITLE
Question : Est-ce qu'on termine l'écran de dévérouillage ?

### ISSUE THREAD

**Issue by etienneCharignon** [betagouv/eva#864]
J’ai compris qu’on veut mesurer la compétence en calcul. Qu’est-ce qui se passe si le calcul est faut ? Je ne pense pas qu’on va bloquer les évalué·es s’ils ou elles ne savent pas faire ce calcul, mais alors quel est le sens d’utiliser un écran de déverrouillage du téléphone. Dans la situation bureau, il y avait une option “je ne sais pas faire ce calcul” qui était très importante pour les évalués (si j’ai bien compris). Comment on va faire ici ?

De plus, cette écran ajoute un nouveau mode d’interraction ou l’utilisateur doit taper des chiffres au clavier. C’est chaud à faire. (je penses aussi au tablettes) et je ne sais même pas si les évalués savent trouver les chiffres sur le clavier. Ne pourrait-on pas rester sur un qcm (au moins dans un premier temps) ? (la question se pose aussi pour l’application répondeur).

**Comment by Alexis-Akinyemi** [comment]
J'essaie de répondre point par point en ce qui concerne l'aspect psycho :) 

__ Si le calcul est faux __
On considère que la réponse est fausse et on amène l'utilisateur à l'écran suivant 
(ça me fait simplement penser qu'il faut bien penser au cas de 100% de mauvaises réponses dans l'algo,  ce qui n'a pas encore été fait de notre côté, merci pour cela). 

__Le sens d'utiliser un écran de verrouillage du téléphone__ 
Le scénario, c'est difficile de poser ce genre de questions de la même manière que les autres parce que ça casse facilement l'enjeu de "répondre à des questions qui permettent de retrouver Sophie". On a eu ce problème à plusieurs reprise et cet écran de verrouillage s'est avéré pratique en termes de scénario.

__ L'option je ne sais pas faire le calcul __
L'option je ne sais pas n'est pas très pertinente lorsqu'on mesure une compétence car elle apporte trop peu d'information. On identifie un cas de figure dans lequel elle est utile : inciter les personnes à ne pas répondre au hasard pour faire plus facilement la distinction entre les personnes qui réussissent grâce au hasard et les personnes qui réussissent grâce à leurs compétence. Dans notre cas de figure elle nous paraît peu pertinente car 1) ce positionnement nécessite d'être expliqué ("attention, répondre au hasard diminue votre score") ce qui alourdirait les consignes et pourrait beaucoup rappeler l'école, 2) c'est un pari dangereux d'inclure ce type d'enjeu de motivation à distance et il est difficile de mesurer si ça marche, 3) on a un bon accès au profil "je répond au hasard", par le temps de réponse (qui seront considérés comme valeurs extrêmes). Information dont on ne dispose pas lorsqu'on insère ce type de règle dans les QCM. 

__ Nouveau mode d'interaction. Ne pourrait-on pas rester sur un QCM ___
En en discutant avec @telohtrab  on tendait à se dire que valait le coup, pour le gain en cohérence du scénario. On est bien-sûr ouverts à d'autres alternatives qui prennent en compte cette contrainte de cover-story (c.a.d utiliser le scénario pour limiter l'effet "regardez on mesure vos compétences en français et en maths") et on s'en remet à Benjamin pour la pertinence UX de ce choix ou les meilleurs alternatives.

**Comment by telohtrab** [comment]
J'avais cru comprendre après nos échanges qu'effectivement, quelque soit la réponse on passe à la suite, et que c'était un choix assumé.

Quant à la question d'utiliser les touches du clavier, je sais pas trop quoi dire à part : On veut que la personne tape une réponse avec 4 chiffres, donc qu'elle utilise son clavier pour le faire. Narrativement parlant ça me paraît plus cohérent et concernant l'utilisation du clavier, je sais qu'on est sur un public difficile, mais avant que ce ne soit un retour utilisateur, je n'interdirais pas l'accès au clavier pour de telles saisies.

On demande par ailleurs aux gens de taper leur nom, prénom, de faire un mémo écrit ou de d'utiliser les flèches...

Pour le tactile, on peut restreindre normalement sur tactile à l'ouverture d'un clavier uniquement numérique (comme sur certaines interfaces de banques, code postal..)

**Comment by etienneCharignon** [comment]
Merci pour vos réponses.
