### ISSUE TITLE
Question : Est-ce qu'on fait l'écran message vocaux ?

### ISSUE THREAD

**Issue by etienneCharignon** [betagouv/eva#865]
- Cet écran ajoute un nouveau mode d’interaction ou l’utilisateur doit taper des chiffres au clavier. C’est chaud à faire. (je penses aussi au tablettes) et je ne sais même pas si les évalués savent trouver les chiffres sur le clavier. Ne pourrait-on pas rester sur un qcm (au moins dans un premier temps) ? (à noter que ce problème est aussi présent dans l'écran de déverrouillage et probablement discuté dans l'issue #864)
- Cet écran représente beaucoup plus de travail que les autres car il suppose que l'utilisateur clique sur les message du répondeur dans l'image pour entendre un message 
- c'est une interaction nouvelle auquel il n'a pas été entrainé et le temps de réponse pourrait être variable en fonction des compétences numérique de l'évalué et sa capacité à deviner le fonctionnement de cet écran.

**Comment by Alexis-Akinyemi** [comment]
- Pour ce point je m'en remets au commentaire de @telohtrab sur la #864 

- Est-ce qu'une modification du parcours pourrait permettre de contourner cette difficulté ? Je pense que @telohtrab  est encore une fois le meilleur interlocuteur pour cette question. Côté psycho, cet écran est important car il est le seul qui manipule la compréhension écoute vers lecture. 

- Pour les temps de réponse ça n'est pas grave si c'est allongé tant que tous les utilisateurs sont confronté à la même situation. Tous les temps de réactions seront affectés de la même manière donc ça n'aura aucun impact sur le scoring. Pour l'aspect UX, je pense comme Benjamin que ça mérite d'être testé. 

Par contre en fonction de l'ampleur de la surcharge générée il est peut-être plus pertinent de revoir complètement cet écran. A toi de nous dire :)

**Comment by telohtrab** [comment]
J'ai déjà répondu au premier point dans la #864 

2ème point : Je peux essayer de réfléchir à quelque chose, mais honnêtement, d'un point de vue immersion, UX et narratif, je vois pas de meilleure manière de faire comprendre qu'on "doit" écouter un message vocal sur le téléphone... en le sélectionnant sur l'écran ! 

On peut tenter une alternative qui serait d'ajouter un bouton dans la white-card qui dit "écouter le message" mais j'ai pour le coup peur que ça prête plus à confusion qu'autre chose...

**Comment by etienneCharignon** [comment]
Ok, essayons comme ça et puis on verra bien les retours.
