### ISSUE TITLE
Question : qu'est-ce qu'on fait des questions de la fin si on ne s'intéresse plus à la compétence de mémorisation ?

### ISSUE THREAD

**Issue by etienneCharignon** [betagouv/eva#866]
Supprime ton tout les écrans qui concerne la mémorisation, on est-ce trop tôt pour prendre cette décision ?

**Comment by Alexis-Akinyemi** [comment]
La question se pose car dans le référentiel de l'anlci la mémorisation n'est pas une composante de l'illettrisme. Mais on attend d'avoir passé en revue toutes les réflexions au niveau européen pour se faire une idée définitive.  Ces questions peuvent aussi avoir une autre utilité dans l'algo (bonus/ rattrapage, etc), possibilité que l'on a pas encore explorée.

**Comment by etienneCharignon** [comment]
En résumé, la réponse est on garde comme c'est pour l'instant.
