### ISSUE TITLE
Faire une passe sur les erreurs rollbar

### ISSUE THREAD

**Issue by etienneCharignon** [betagouv/eva#867]

**Comment by shanser** [comment]
2 erreurs Ruby :
* j'ai créé betagouv/eva-serveur#389
* une erreur liée à une configuration manquante, la configuration est corrigée et je l'ai fermé. https://rollbar.com/eva-betagouv/eva/items/60/ 

J'ai également configuré l'environnement de preprod pour que Rollbar le différencie de la prod

**Comment by shanser** [comment]
pour les erreurs JS, je voudrais pouvoir configurer l'environnement pour différencier les erreurs en dev, preprod ou prod avant de poursuivre l'analyse.
