### ISSUE TITLE
Migration metabase sur scalingo

### ISSUE THREAD

**Issue by etienneCharignon** [betagouv/eva#876]
- Appli migré
- RAF : migré la base (ou recréé les indicateurs)

**Comment by shanser** [comment]
Pour le moment j'ai pointé vers la nouvelle base, ce qui nous permet au moins d'avoir les stats à jour.

**Comment by shanser** [comment]
C'est bon je m'en suis sorti, en théorie c'est très simple mais j'ai beaucoup galéré à réusssir à me connecter à un serveur Postgres distant pour migrer les données.
Puis j'ai vraiment eu du mal à importer parce que Scalingo a rencontré des soucis à ce moment là. Heureusement ils sont très réactifs.
L'important c'est d'y être arrivé 🎉

**Comment by etienneCharignon** [comment]
👏 J'espère que tu me racontera les détail technique de vive voix quand même (surtout sur le point qui t'a fait galérer.
