### ISSUE TITLE
Retours MES Object trouvé :

### ISSUE THREAD

**Issue by Laurenmichel21** [betagouv/eva#894]
Voici mes premiers retours, je laisse @Alexis-Akinyemi  et @laurenehoutin  compléter   :
**Apps Agenda** : Expliquer à l'utilisateur qu'il faut cliquer sur l'apps agenda :
Proposition wording  => Veuillez cliquer sur l'application agenda pour l'ouvrir.
Sur l'écran " Où Sophie doit elle travailler de 14H30 à 16h d'après son agenda" on ne comprend pas qu'il faut cliquer sur les haut parleur .
Proposition => Ajouter dans le consigne « écoutez chaque proposition en cliquant sur les hauts parleurs » 
**Apps Répondeur** :  Dans la consigne indiquer à l'utilisateur qu'il faut cliquer sur le bouton lecture audio , le risque c'est qu'il cherche à cocher 12H57.
**Apps Rappel** : Le smiley est facilement interprétable , est ce un chien ? un chat ? une loutre  ? 
Proposition => trouver un visuel plus simple et qui ne laisse aucun doute

**Comment by laurenehoutin** [comment]
<img width="563" alt="Capture d’écran 2020-04-21 à 12 59 46" src="https://user-images.githubusercontent.com/56107558/79858645-06dffc00-83d0-11ea-84e3-191a2c54d2d9.png">

**Comment by laurenehoutin** [comment]
<img width="835" alt="Capture d’écran 2020-04-21 à 13 02 08" src="https://user-images.githubusercontent.com/56107558/79858843-545c6900-83d0-11ea-9038-bcbca5c95ecb.png">

Pourquoi l'application s'appelle t elle note au lieu de Rappels ? D'autant plus qu'à droite il y a Rappels

**Comment by laurenehoutin** [comment]
<img width="353" alt="Capture d’écran 2020-04-21 à 13 01 15" src="https://user-images.githubusercontent.com/56107558/79858883-63dbb200-83d0-11ea-8791-b6a0b3def1ab.png">

Est-ce qu'on peut mieux faire ressortir la phrase d'indice ? Je trouve cela difficile à lire avec un peu de fatigue

**Comment by laurenehoutin** [comment]
<img width="376" alt="Capture d’écran 2020-04-21 à 13 05 18" src="https://user-images.githubusercontent.com/56107558/79859103-c46aef00-83d0-11ea-9104-a688688bd361.png">

Est ce qu'on ne pourrait pas se contenter de dire "Bravo, vous avez retrouvé Sophie ! Allons la rejoindre" pour alléger le texte (toujours dans l'objectif de rendre les choses les plus accessibles possible à ceux qui ne parle pas bien français)

**Comment by telohtrab** [comment]
> <img alt="Capture d’écran 2020-04-21 à 13 02 08" width="835" src="https://user-images.githubusercontent.com/56107558/79858843-545c6900-83d0-11ea-9038-bcbca5c95ecb.png">
> 
> Pourquoi l'application s'appelle t elle note au lieu de Rappels ? D'autant plus qu'à droite il y a Rappels

Rappels était le premier nom de l'appli, on l'a renommé Notes pour avoir un nom plus générique suite à une discussion avec Gaelle et @Alexis-Akinyemi  de mémoire. C'est un oubli de ma part de l'avoir répercuté sur la petite icône de droite.

**Comment by telohtrab** [comment]
> <img alt="Capture d’écran 2020-04-21 à 13 05 18" width="376" src="https://user-images.githubusercontent.com/56107558/79859103-c46aef00-83d0-11ea-9104-a688688bd361.png">
> 
> Est ce qu'on ne pourrait pas se contenter de dire "Bravo, vous avez retrouvé Sophie ! Allons la rejoindre" pour alléger le texte (toujours dans l'objectif de rendre les choses les plus accessibles possible à ceux qui ne parle pas bien français)

+1 Je mets à jour sur le Figma 

@mdomine @etienneCharignon @morissetcl

**Comment by laurenehoutin** [comment]
> > <img alt="Capture d’écran 2020-04-21 à 13 02 08" width="835" src="https://user-images.githubusercontent.com/56107558/79858843-545c6900-83d0-11ea-9038-bcbca5c95ecb.png">
> > Pourquoi l'application s'appelle t elle note au lieu de Rappels ? D'autant plus qu'à droite il y a Rappels
> 
> Rappels était le premier nom de l'appli, on l'a renommé Notes pour avoir un nom plus générique suite à une discussion avec Gaelle et @Alexis-Akinyemi de mémoire. C'est un oubli de ma part de l'avoir répercuté sur la petite icône de droite.

Ah d'accord ! Je trouve cela bizarre car l'interface ne ressemble pas du tout à un truc de notes mais bon comme voulez

**Comment by telohtrab** [comment]
> > > <img alt="Capture d’écran 2020-04-21 à 13 02 08" width="835" src="https://user-images.githubusercontent.com/56107558/79858843-545c6900-83d0-11ea-9038-bcbca5c95ecb.png">
> > > Pourquoi l'application s'appelle t elle note au lieu de Rappels ? D'autant plus qu'à droite il y a Rappels
> > 
> > 
> > Rappels était le premier nom de l'appli, on l'a renommé Notes pour avoir un nom plus générique suite à une discussion avec Gaelle et @Alexis-Akinyemi de mémoire. C'est un oubli de ma part de l'avoir répercuté sur la petite icône de droite.
> 
> Ah d'accord ! Je trouve cela bizarre car l'interface ne ressemble pas du tout à un truc de notes mais bon comme voulez

C'est d'ailleurs bizarre que Rappels soit resté car sur le Figma Notes est bien présent partout...

**Comment by telohtrab** [comment]
> <img alt="Capture d’écran 2020-04-21 à 13 01 15" width="353" src="https://user-images.githubusercontent.com/56107558/79858883-63dbb200-83d0-11ea-8791-b6a0b3def1ab.png">
> 
> Est-ce qu'on peut mieux faire ressortir la phrase d'indice ? Je trouve cela difficile à lire avec un peu de fatigue

Voici ma proposition (style "notification") : 
![image](https://user-images.githubusercontent.com/7781917/79860124-6b03bf80-83d2-11ea-9810-0b3a75929366.png)

**Comment by laurenehoutin** [comment]
> > <img alt="Capture d’écran 2020-04-21 à 13 01 15" width="353" src="https://user-images.githubusercontent.com/56107558/79858883-63dbb200-83d0-11ea-8791-b6a0b3def1ab.png">
> > Est-ce qu'on peut mieux faire ressortir la phrase d'indice ? Je trouve cela difficile à lire avec un peu de fatigue
> 
> Voici ma proposition (style "notification") :
> ![image](https://user-images.githubusercontent.com/7781917/79860124-6b03bf80-83d2-11ea-9810-0b3a75929366.png)

C'est mieux ! Mais je trouve toujours qu'on dirait qu'il y a un filtre devant l'écriture. On ne peut pas mettre un vrai noir qui ressort bien ?

**Comment by telohtrab** [comment]
> **Apps Agenda** : Expliquer à l'utilisateur qu'il faut cliquer sur l'apps agenda :
> Proposition wording => Veuillez cliquer sur l'application agenda pour l'ouvrir.

J'imagine que tu proposes ça plutôt pour l'entrainement ? Sur le figma c'est la consigne qui est présente.

> Sur l'écran " Où Sophie doit elle travailler de 14H30 à 16h d'après son agenda" on ne comprend pas qu'il faut cliquer sur les haut parleur .
> Proposition => Ajouter dans le consigne « écoutez chaque proposition en cliquant sur les hauts parleurs »

D'accord. Je comptais sur le fait que 99% de ce qui est bleu-violet sont les éléments d'intéraction (bouton play des messages vocaux, bouton valider, tous les boutons "continuer" des consignes..) ainsi que la présence des habituels boutons radios qui induisent un clic. 

> **Apps Répondeur** : Dans la consigne indiquer à l'utilisateur qu'il faut cliquer sur le bouton lecture audio , le risque c'est qu'il cherche à cocher 12H57.

Même remarque que ci-dessus mais ça ne coûte pas bien cher d'ajouter du texte. 
Proposition : Plutôt qu'uniquement le bouton play cliquable, toute la "carte" du message vocal est cliquable avec la petite main.

> **Apps Rappel** : Le smiley est facilement interprétable , est ce un chien ? un chat ? une loutre ?
> Proposition => trouver un visuel plus simple et qui ne laisse aucun doute

Je vais tâcher de trouver un emoji plus clair.

**Comment by telohtrab** [comment]
En ajoutant les consignes audio, ça se bouscule un peu dans les white-card, est-ce qu'il est possible de réduire le nombre de propositions ?

![image](https://user-images.githubusercontent.com/7781917/79861159-38f35d00-83d4-11ea-9178-43f5636f8da9.png)

**Comment by telohtrab** [comment]
> > > <img alt="Capture d’écran 2020-04-21 à 13 01 15" width="353" src="https://user-images.githubusercontent.com/56107558/79858883-63dbb200-83d0-11ea-8791-b6a0b3def1ab.png">
> > > Est-ce qu'on peut mieux faire ressortir la phrase d'indice ? Je trouve cela difficile à lire avec un peu de fatigue
> > 
> > 
> > Voici ma proposition (style "notification") :
> > ![image](https://user-images.githubusercontent.com/7781917/79860124-6b03bf80-83d2-11ea-9810-0b3a75929366.png)
> 
> C'est mieux ! Mais je trouve toujours qu'on dirait qu'il y a un filtre devant l'écriture. On ne peut pas mettre un vrai noir qui ressort bien ?

J'ai rendu la notification totalement opaque. Je ne suis pas pour mettre du noir full ici car j'utilise ce bleu très foncé partout ailleurs. J'espère que ce sera suffisamment clair cette fois :)

![image](https://user-images.githubusercontent.com/7781917/79861216-532d3b00-83d4-11ea-9fbe-58ac2fb5b80e.png)

**Comment by laurenehoutin** [comment]
> En ajoutant les consignes audio, ça se bouscule un peu dans les white-card, est-ce qu'il est possible de réduire le nombre de propositions ?
> 
> ![image](https://user-images.githubusercontent.com/7781917/79861159-38f35d00-83d4-11ea-9178-43f5636f8da9.png)

Oui oui on peut en retirer genre deux, notamment les plus éloignées en termes de sonorité

**Comment by laurenehoutin** [comment]
> > > > <img alt="Capture d’écran 2020-04-21 à 13 01 15" width="353" src="https://user-images.githubusercontent.com/56107558/79858883-63dbb200-83d0-11ea-8791-b6a0b3def1ab.png">
> > > > Est-ce qu'on peut mieux faire ressortir la phrase d'indice ? Je trouve cela difficile à lire avec un peu de fatigue
> > > 
> > > 
> > > Voici ma proposition (style "notification") :
> > > ![image](https://user-images.githubusercontent.com/7781917/79860124-6b03bf80-83d2-11ea-9810-0b3a75929366.png)
> > 
> > 
> > C'est mieux ! Mais je trouve toujours qu'on dirait qu'il y a un filtre devant l'écriture. On ne peut pas mettre un vrai noir qui ressort bien ?
> 
> J'ai rendu la notification totalement opaque. Je ne suis pas pour mettre du noir full ici car j'utilise ce bleu très foncé partout ailleurs. J'espère que ce sera suffisamment clair cette fois :)
> 
> ![image](https://user-images.githubusercontent.com/7781917/79861216-532d3b00-83d4-11ea-9fbe-58ac2fb5b80e.png)

So much better
(pour les astigmates comme moi)

**Comment by telohtrab** [comment]
> > En ajoutant les consignes audio, ça se bouscule un peu dans les white-card, est-ce qu'il est possible de réduire le nombre de propositions ?
> > ![image](https://user-images.githubusercontent.com/7781917/79861159-38f35d00-83d4-11ea-9178-43f5636f8da9.png)
> 
> Oui oui on peut en retirer genre deux, notamment les plus éloignées en termes de sonorité

On retire 13h15 et 12h35 ?

**Comment by telohtrab** [comment]
> > > > > <img alt="Capture d’écran 2020-04-21 à 13 01 15" width="353" src="https://user-images.githubusercontent.com/56107558/79858883-63dbb200-83d0-11ea-8791-b6a0b3def1ab.png">
> > > > > Est-ce qu'on peut mieux faire ressortir la phrase d'indice ? Je trouve cela difficile à lire avec un peu de fatigue
> > > > 
> > > > 
> > > > Voici ma proposition (style "notification") :
> > > > ![image](https://user-images.githubusercontent.com/7781917/79860124-6b03bf80-83d2-11ea-9810-0b3a75929366.png)
> > > 
> > > 
> > > C'est mieux ! Mais je trouve toujours qu'on dirait qu'il y a un filtre devant l'écriture. On ne peut pas mettre un vrai noir qui ressort bien ?
> > 
> > 
> > J'ai rendu la notification totalement opaque. Je ne suis pas pour mettre du noir full ici car j'utilise ce bleu très foncé partout ailleurs. J'espère que ce sera suffisamment clair cette fois :)
> > ![image](https://user-images.githubusercontent.com/7781917/79861216-532d3b00-83d4-11ea-9fbe-58ac2fb5b80e.png)
> 
> So much better
> (pour les astigmates comme moi)

ça marche, je suis astigmate d'un oeil je n'avais pas repéré de souci particulier !

**Comment by telohtrab** [comment]
@etienneCharignon @mdomine @morissetcl @shanser 

Je vous ai ajouté des rectangles rouges avec les modifications à apporter sur Objets Trouvés pour que vous vous y retrouviez plus facilement : 
![image](https://user-images.githubusercontent.com/7781917/79862344-3eea3d80-83d6-11ea-89c4-efb21cf0d35a.png)

**Comment by telohtrab** [comment]
Propositions d'emoji chien. (Obligé d'utiliser des emojis officiels d'OS pour lesquels on sera pas trop embêté pour la question des droits, plutôt que des icônes dédiées)

![image](https://user-images.githubusercontent.com/7781917/79862478-6f31dc00-83d6-11ea-8f85-407d861ee9d1.png)
![image](https://user-images.githubusercontent.com/7781917/79862706-c8017480-83d6-11ea-8401-56d7bc4403a5.png)

**Comment by etienneCharignon** [comment]
Permetez moi de vous faire une remarques amicale. Je ne m'y retrouve déjà plus dans tous ces retours. Pouvez-vous créer une issue différente par retour et y reporter chaque discussion ?

**Comment by telohtrab** [comment]
C'est pour ça que j'ai tout compilé sur le Figma :)
Benjamin Bartholet

*TRΔB design & inks*
website : trab.design
tw : @trab_ink
ig : @trab_ink <https://twitter.com/trab_ink>

**Comment by Alexis-Akinyemi** [comment]
Hello, j'ai un seul retour éventuel à ajouter aux retours précédents : 

Je me demande si à  "Bravo, vous avez retrouvé Sophie ! Allons la rejoindre" il pourrait être bon de dire où Sophie a été trouvée,  pour éviter à certaines personnes une rumination qui pourrait les handicapper pour les questions suivantes.
Par exemple "Bravo, vous avez retrouvé Sophie ! Allons la rejoindre dans le bureau de Mickaël !"

Je pense aussi au sujet de l'heure. Est-ce qu'on a statué du changement de l'horloge qui affiche l'heure actuelle de passation ?

**Comment by etienneCharignon** [comment]
Salut @Alexis-Akinyemi,

Est-ce que tu peux mettre ta première remarques sans l'issue #901 ?

Pour la deuxième remarques, peux-tu créer une nouvelle issue dans la colonne backlog dev ?

**Comment by Laurenmichel21** [comment]
@Alexis-Akinyemi à la demande d'Etienne j'ai redecoupoé cette cartes en sous carte. Est ce que tu peux mettre ton commentaire dans la carte en lien avec le sujet; Merci ;-)

**Comment by etienneCharignon** [comment]
Pour moi, tous les sujets discutés ici ont été reporté dans les sous cartes. Je clos donc cette issue.
