### ISSUE TITLE
Aide à l'utilisation de l'apps répondeur 

### ISSUE THREAD

**Issue by Laurenmichel21** [betagouv/eva#896]
- [x] Proposition de Benjamin et Laurène : retirer deux réponses, celles les plus éloignés de la solution en termes de sonorité pour gagner de la place. Un objectif supplémentaire c'est que dans les propositions, on ne trouve pas 12h57.
- [x] Dans la consigne indiquer à l'utilisateur qu'il faut cliquer sur le bouton lecture audio pour éviter le risque qu'il cherche à cocher 12H57.
- [x] Proposition de Benjamin : Plutôt qu'uniquement le bouton play cliquable, toute la "carte" du message vocal est cliquable avec la petite main.
- [x] prendre en compte la réponse à la question d'Étienne dans l'issue

<img width="991" alt="Capture d’écran 2020-04-21 à 11 33 58" src="https://user-images.githubusercontent.com/57912856/79874219-5e8a6180-83e8-11ea-86d9-87f755e1fefc.png">

**Comment by Laurenmichel21** [comment]
<img width="991" alt="Capture d’écran 2020-04-21 à 11 33 58" src="https://user-images.githubusercontent.com/57912856/79874219-5e8a6180-83e8-11ea-86d9-87f755e1fefc.png">
Expliquer à l'utilisateur qu'il faut cliquer sur l'apps agenda :
Proposition wording => Veuillez cliquer sur l'application agenda pour l'ouvrir.
Sur l'écran " Où Sophie doit elle travailler de 14H30 à 16h d'après son agenda" on ne comprend pas qu'il faut cliquer sur les haut parleur .
Proposition => Ajouter dans le consigne « écoutez chaque proposition en cliquant sur les hauts parleurs »

**Comment by etienneCharignon** [comment]
@laurenehoutin @telohtrab Dans le cadre de la simplification du texte, j’aurais bien envie sur cet écran d’écrire seulement : 

```
Vous savez que Sophie lance un tour de manège pour 7 enfants.

Que sophie devrait-elle répondre ?
```

- on enlève complètement cette idée qu'on devrait répondre à sa place
- on ne redit pas sur cet écran qu'il faut cliquer sur le bouton play

<img width="1011" alt="Capture d’écran 2020-04-24 à 15 14 45" src="https://user-images.githubusercontent.com/298214/80216802-e9fd3000-863e-11ea-9a15-9132b6ee7fc6.png">

**Comment by laurenehoutin** [comment]
Hello, nous avons eu beaucoup de discussions déjà à ce sujet, et cela avait été tranché comme cela. Si vous le souhaitez, vous pouvez changer, pas de sujet pour moi.

**Comment by telohtrab** [comment]
Très bonne simplification, j'y vois pas d'inconvénient particulier au
contraire :)

**Comment by etienneCharignon** [comment]
C'est cool, merci de vos réponses rapides, on part la dessus.
