### ISSUE TITLE
Apps Note

### ISSUE THREAD

**Issue by Laurenmichel21** [betagouv/eva#898]
Smiley peu compréhensible : Trouver un visuel d'un chien qui ne laisse aucun doute à l'interpretation

**Comment by Laurenmichel21** [comment]
<img width="809" alt="Capture d’écran 2020-04-21 à 11 39 15" src="https://user-images.githubusercontent.com/57912856/79875111-757d8380-83e9-11ea-8e87-bc9aa572c15e.png">

**Comment by etienneCharignon** [comment]
Cette issue est en double de l'issue #899. Je ferme celle ci
