### ISSUE TITLE
Nommage de l'app Note/Rappels et icone du chien

### ISSUE THREAD

**Issue by Laurenmichel21** [betagouv/eva#899]
Changement de wording => Remplacer le nom de l'apps par Notes et non Rappels
Propositions d'emoji chien. (Obligé d'utiliser des emojis officiels d'OS pour lesquels on sera pas trop embêté pour la question des droits, plutôt que des icônes dédiées)

Voici les emojis disponibles selon les appareils : https://emojipedia.org/dog-face/ ou encore
: https://emojipedia.org/dog/

- [x] renomage de l'app (#927)
- [ ] Changement de l'icone de chien (#934)

**Comment by Laurenmichel21** [comment]
<img width="949" alt="Capture d’écran 2020-04-21 à 11 39 53" src="https://user-images.githubusercontent.com/57912856/79875246-aeb5f380-83e9-11ea-9d81-5a75ad959d38.png">

**Comment by etienneCharignon** [comment]
Il me semble qu'il y a encore des questions en suspend dans la discussion de l'issue #894

**Comment by telohtrab** [comment]
Hello ! J'me permets de vous relancer sur la question suite à mes propositions de nouvel emoji chien (et d'autres disponibles dans le lien ci-dessus) 

![image](https://user-images.githubusercontent.com/7781917/80389798-dc98ad80-88ab-11ea-858f-f67adfa83764.png)

![image](https://user-images.githubusercontent.com/7781917/80389816-e15d6180-88ab-11ea-87ce-182964867441.png)

**Comment by telohtrab** [comment]
@Laurenmichel21 @laurenehoutin Est-ce que vous pourriez nous donner votre avis sur la question ?

Je serais partant pour utiliser la tête de chien en 2ème ci-dessus

**Comment by Laurenmichel21** [comment]
@telohtrab  ok avec toi pour partir sur le 2eme chien ! 🐶

**Comment by Laurenmichel21** [comment]
@etienneCharignon j'ai bien la MAJ du wording mais pas le nouvel icône du chien

**Comment by Laurenmichel21** [comment]
<img width="966" alt="Capture d’écran 2020-04-29 à 09 13 21" src="https://user-images.githubusercontent.com/57912856/80569715-cac52080-89f9-11ea-825e-358f7a3f68c2.png">

**Comment by etienneCharignon** [comment]
En effet, c'est un problème de déploiement sur la préprod. Je regarde

**Comment by etienneCharignon** [comment]
J'ai corrigé et relancé le déploiement. Ça devrait être bon maintenant.
