### ISSUE TITLE
Rendre plus lisible l'indice de l'écran déverrouillage

### ISSUE THREAD

**Issue by Laurenmichel21** [betagouv/eva#900]
Faire ressortir la phrase d'indice peu l'illisible en l'état.

Rendre plus lisible l'écriture de la consigne (sensation de filtre). voir la proposition de benjamin dans Figma

**Comment by Laurenmichel21** [comment]
<img width="460" alt="Capture d’écran 2020-04-21 à 16 06 49" src="https://user-images.githubusercontent.com/57912856/79875566-1e2be300-83ea-11ea-8737-eb1d0e049831.png">

**Comment by etienneCharignon** [comment]
Etant donnée qu'on fait déjà beaucoup de choses spécifique sur cet écran, on pourrait aussi reprendre en développement l'affichage de l'indice. Ce qui éviterait qu'il soit floue

**Comment by Laurenmichel21** [comment]
Je ne vois pas vraiment de changement sur la netteté de la phrase indice.

**Comment by etienneCharignon** [comment]
Peux-tu faire une copie d'écran ?

**Comment by Laurenmichel21** [comment]
@etienneCharignon  voici le capture d'écran 
<img width="960" alt="Capture d’écran 2020-04-26 à 16 42 02" src="https://user-images.githubusercontent.com/57912856/80310843-10f16880-87dd-11ea-9f57-9b2655b1751d.png">

**Comment by etienneCharignon** [comment]
En effet, il y eu un problème de déploiement sur la pré-prod. J'ai relancé le déploiement. Est-ce que tu peux refaire un essai ?

**Comment by telohtrab** [comment]
Je suis tenté de valider, j'ai simplement une question 

Voici la version Figma :
![image](https://user-images.githubusercontent.com/7781917/80365450-e7414b80-8887-11ea-83d9-ce358e142a0a.png)

La version en prod : 
![image](https://user-images.githubusercontent.com/7781917/80365475-f45e3a80-8887-11ea-9ecc-652b9532514a.png)

Je me demandais simplement pourquoi on avait cette différence de graisse dans la fonte ? ça dépend du rendu des browsers ?
