### ISSUE TITLE
Simplifier le message de l'écran de transition

### ISSUE THREAD

**Issue by Laurenmichel21** [betagouv/eva#901]
Remplacer le  wording existant par  "Bravo, vous avez retrouvé Sophie ! Allons la rejoindre" 
Explications : alléger le texte (toujours dans l'objectif de rendre les choses les plus accessibles possible à ceux qui ne parle pas bien français)

**Comment by Laurenmichel21** [comment]
<img width="401" alt="Capture d’écran 2020-04-21 à 16 11 06" src="https://user-images.githubusercontent.com/57912856/79875970-b6c26300-83ea-11ea-9c27-b430648cfc34.png">

**Comment by Alexis-Akinyemi** [comment]
Hello, Je me demande si à "Bravo, vous avez retrouvé Sophie ! Allons la rejoindre" il pourrait être bon de dire où Sophie a été trouvée, pour éviter à certaines personnes une rumination qui pourrait les handicapper pour les questions suivantes.
Par exemple "Bravo, vous avez retrouvé Sophie ! Allons la rejoindre dans le bureau de Mickaël !"

**Comment by etienneCharignon** [comment]
Tu veux dire que l'on donnerai dans cet écran la réponse à la question qui vient juste après ?
<img width="705" alt="Capture d’écran 2020-04-22 à 17 43 37" src="https://user-images.githubusercontent.com/298214/80003179-ed6aad00-84c0-11ea-8ca5-acc8c3aa85fb.png">

**Comment by Alexis-Akinyemi** [comment]
Effectivement je retire ce que j'ai dit. J'étais motivé par l'envie de donner la réponse à la fin mais on verra après les premiers tests si c'est vraiment nécessaire :).
