### ISSUE TITLE
Apps répondeur

### ISSUE THREAD

**Issue by Laurenmichel21** [betagouv/eva#902]
Rendre plus lisible l'écriture de la consigne (sensation de filtre)  , voir la proposition de benjamin dans Figma

**Comment by Laurenmichel21** [comment]
<img width="429" alt="Capture d’écran 2020-04-21 à 16 15 17" src="https://user-images.githubusercontent.com/57912856/79876697-a78fe500-83eb-11ea-9c63-12516d3d889e.png">

**Comment by etienneCharignon** [comment]
Cette issue ne concerne pas le répondeur et est en double de l'issue #900. Je ferme celle ci
