### ISSUE TITLE
Restitution

### ISSUE THREAD

**Issue by Laurenmichel21** [betagouv/eva#904]
Je m'aperçois qu'il y a deux fois la restitution Maintenance. Est ce un coquille ?

**Comment by Laurenmichel21** [comment]
<img width="1184" alt="Capture d’écran 2020-04-22 à 08 39 10" src="https://user-images.githubusercontent.com/57912856/79948990-1a916e00-8475-11ea-87e7-87b41b5014b0.png">

**Comment by shanser** [comment]
Pas si l’évalue a passé plusieurs fois la situation :)

**Comment by Laurenmichel21** [comment]
Je me suis aperçu de mon erreur , désolée. Je l'ai clôturé.
