### ISSUE TITLE
Mettre une heure fixe dans le téléphone

### ISSUE THREAD

**Issue by Alexis-Akinyemi** [betagouv/eva#905]
Puisque certaines horaires de passation pourrait rendre le scénario caduque, on propose que l'heure du téléphone soit fixée à 13h, heure à laquelle le joueur est supposé se rendre compte qu'il va devoir rejoindre l'entrée du parc pour rendre son téléphone à Sophie

**Comment by telohtrab** [comment]
Ok pour moi !
