### ISSUE TITLE
Coquille wording bouton bienvenue

### ISSUE THREAD

**Issue by Laurenmichel21** [betagouv/eva#920]
Changer le "i" dans le wording du bouton bienvenue

**Comment by Laurenmichel21** [comment]
<img width="1072" alt="Capture d’écran 2020-04-26 à 12 45 06" src="https://user-images.githubusercontent.com/57912856/80305279-2904c000-87bc-11ea-8655-080dc475bd24.png">

**Comment by etienneCharignon** [comment]
une vielle issue qui n'avait jamais été fermée. Je ferme
