### ISSUE TITLE
Consigne MES Bienvenue

### ISSUE THREAD

**Issue by Laurenmichel21** [betagouv/eva#921]
-  Ajouter au tout début "Avant de commencer les mises en situations nous vous demandons de bien vouloir répondre à ce questionnaire" et ensuite " qui nous servira à compléter les résultats obtenus grâce à Eva.
Par exemple, à la question "j'adore les séries télévisées", si vous adorez les séries télévisées, sélectionnez le chiffre 7.

- Doubler la consigne écrite à l'audio 

-  Mettre une image en fond 

@etienneCharignon  je te remets le texte que tu avais écris : Avant de commencer les mises en situation, nous vous demandons de bien vouloir répondre à ce questionnaire. Il nous servira à compléter les résultats obtenus grâce à Eva.
Nous vous demandons de nous dire sincèrement à quel point chaque phrase vous correspond. Vous devez répondre en utilisant une échelle allant de 1 “pas du tout” à 7 “tout à fait”.

Par exemple, à la question "j'adore les séries télévisées", si vous adorez les séries télévisées, sélectionnez le chiffre 7.

**Comment by laurenehoutin** [comment]
Hello, mes retours :
- peut-on ajouter au tout début "Avant de commencer les serious games, nous vous demandons de bien vouloir répondre à ce questionnaire" et ensuite " qui nous servira à compléter les résultats obtenus grâce à Eva.
- peut-on doubler la consigne écrite à l'audio ?
- peut-on mettre une image en fond ?
- je ne vois que deux questions mais j'imagine que c'est normal
Désolée si je fais des retours sur des trucs que vous allez faire, mais au moins je me dis que j'aurais tout dit ahah

**Comment by etienneCharignon** [comment]
Le plan qui a été discuté jusqu'à présent pour la consigne est le suivant : 
- Le paragraphe d'introduction du document https://docs.google.com/document/d/1ZaES4OZzABGpItHqPLzzNWFjnxuKS9wT5zuzBjF-d3s/edit est a intégrer comme consigne.

**Comment by laurenehoutin** [comment]
Ok mais il s'agit juste d'une proposition de ma part d'ajouter une petite partie pour une meilleure compréhension.
Ok je comprends pour le fait que le travail n'a pas encore été fait ! Bon courage :)

**Comment by etienneCharignon** [comment]
Oui, je voulais juste concentré dans ce ticket le travail de spécification de la consigne de cette MES Bienvenu. Comme on a encore rien fait, c'est le bon moment pour en parler.

**Comment by etienneCharignon** [comment]
> peut-on ajouter au tout début "Avant de commencer les serious games, nous vous demandons de bien vouloir répondre à ce questionnaire" et ensuite " qui nous servira à compléter les résultats obtenus grâce à Eva.

En terme de wording, on n'a jamais parlé de "serious games" jusqu'ici, j'aimerai mieux qu'on reste sur le mot "missions" qui est dans la consigne d'accueil ou sur "mise en situation" comme c'est le cas ensuite.

Ça donnerai : 

Avant de commencer les mises en situation, nous vous demandons de bien vouloir répondre à ce questionnaire. Il nous servira à compléter les résultats obtenus grâce à Eva. 
Nous vous demandons de nous dire sincèrement à quel point chaque phrase vous correspond. Vous devez répondre en utilisant une échelle allant de 1 “pas du tout” à 7 “tout à fait”.  

Par exemple, à la question "j'adore les séries télévisées", si vous adorez les séries télévisées, sélectionnez le chiffre 7.

**Comment by laurenehoutin** [comment]
Je suis d'accord sur le fait qu'il faut s'accorder sur le wording (j'ai utilisé serious game par méprise car on l'utilise avec les structures), donc je trouve que mise en situation est bien.
Sur la dernière phrase je mettrais plutôt "Par exemple, à la question "j'adore les séries télévisées", sélectionnez le chiffre 7 si vous adorez les séries télévisées".

**Comment by etienneCharignon** [comment]
J'ai mis à jour la description de l'issue avec le texte sur lequel on est en train de s'accorder. J'aimerai demander Gaëlle de faire l'enregistrement. Est-ce qu'on est suffisamment d'accord sur le contenu du texte ?

**Comment by laurenehoutin** [comment]
C'est bon pour moi

**Comment by etienneCharignon** [comment]
@telohtrab et @Laurenmichel21 est-ce que ça vous va la consigne telle que rédigé dans la description de cette issue (tout en haut)

**Comment by telohtrab** [comment]
"Par exemple, à la question "j'adore les séries télévisées", si vous adorez les séries télévisées, sélectionnez le chiffre 7."

ça sous-entend qu'on affiche l'échelle de 1 à 7 quelque part ?

**Comment by laurenehoutin** [comment]
Hello, oui !

**Comment by telohtrab** [comment]
Ok, la consigne me va dans ce cas.

Faudra déterminer si on met ça dans la whitecard ou si on veut que ça apparaisse plutôt dans l'image de fond... Je ne sais pas ce qui est intégrable ou pas dans la whitecard aujourd'hui

**Comment by etienneCharignon** [comment]
@Laurenmichel21 J'ai l'impression que tu as effacé le texte de la consigne que j'avais rédigé dans ton premier commentaire. Je voulais utiliser ce premier commentaire comme "description de l'issue", un endroit ou on aurait retrouvé le travail qu'il y a faire et sur lequel on se serait mis d'accord. Mais là je ne retrouve plus le texte que j'avais écrit et je ne comprend pas ce que tu dis à la place. Je ne sais pas quel message de consigne on veut.

**Comment by etienneCharignon** [comment]
>Faudra déterminer si on met ça dans la whitecard ou si on veut que ça apparaisse plutôt dans l'image de fond... Je ne sais pas ce qui est intégrable ou pas dans la whitecard aujourd'hui

@telohtrab : Cette issue parle de la consigne de la situation bienvenue. Au moment ou on affiche cette consigne, il n'y a pas de notion de whitecard. Je ne comprend pas ton commentaire. Il n'y a pas non plus ne notion d'image de fond. Ce qu'on affiche potentiellement derrière la consigne, c'est l'image de la première question.

**Comment by telohtrab** [comment]
My bad, j'y étais pas du tout *facepalm*

D'accord je comprends. Alors il va falloir qu'on détermine comment montrer cette échelle de 1 à 7 proprement sur l'écran consigne. Je ferai des essais sur Figma.

**Comment by etienneCharignon** [comment]
pour info, il y a déjà l'issue #908 qui parle de soigner l'ergonomie de cette histoire d'échelle.

**Comment by telohtrab** [comment]
Oui, mais je distingue l'ergonomie d'utilisation de l'échelle de sa présentation dans la consigne pour compréhension. Les deux ne sont pas nécessairement identiques puisque l'un est destiné à être lu, l'autre à être utilisé :)

**Comment by etienneCharignon** [comment]
@telohtrab dans le texte que Lauren viens de remettre dans le premier commentaire, est-ce que la phrase 

Vous devez répondre en utilisant une échelle allant de 1 « pas du tout » à 7 « tout à fait ».

ne suffit pas à décrire l'échelle (dans un premier temps) ?

**Comment by telohtrab** [comment]
Dans un premier temps oui 👍 
Mais à plus long terme, c'est pas idéal

**Comment by etienneCharignon** [comment]
La consigne développé et validée. Je propose de clore cette issue et de suivre le reste à faire (traitement d'un visuel différent pour l'ergonomie de la consigne concernant les echelles de valeurs et enregistrement audio) dans une autre issue : #943

**Comment by telohtrab** [comment]
ça me va également on peut clore :)
