### ISSUE TITLE
Bienvenue : Expliciter la signification de l'echelle 1 à 7 dans les questions

### ISSUE THREAD

**Issue by Laurenmichel21** [betagouv/eva#922]
Intégrer à chaque question la signification de l'echelle  :  1 signifiant  “pas du tout”  et  7 “tout à fait”

**Comment by etienneCharignon** [comment]
C'est à corriger dans l'admin, dans la définition des questions. Je l'ai fais sur la préprod, il faudra aussi le faire sur la prod.

**Comment by etienneCharignon** [comment]
<img width="1013" alt="Capture d’écran 2020-04-27 à 14 38 38" src="https://user-images.githubusercontent.com/298214/80373072-cd5a3580-8894-11ea-8af3-23265f27c987.png">
