### ISSUE TITLE
MES Agenda : taille des puces inégales dans le QCM

### ISSUE THREAD

**Issue by Laurenmichel21** [betagouv/eva#923]

**Comment by Laurenmichel21** [comment]
<img width="947" alt="Capture d’écran 2020-04-26 à 13 09 38" src="https://user-images.githubusercontent.com/57912856/80305814-8b12f480-87bf-11ea-8ff7-9688c40e3ef1.png">

**Comment by etienneCharignon** [comment]
Je reproduit bien le problème sur safari ! 🙄

**Comment by Laurenmichel21** [comment]
@etienneCharignon  j'ai toujours le même bug : 
<img width="1173" alt="Capture d’écran 2020-04-27 à 15 39 23" src="https://user-images.githubusercontent.com/57912856/80378752-6a20d100-889d-11ea-9a9d-5963a436a833.png">

**Comment by etienneCharignon** [comment]
J'ai peur que tu ai un problème de cache navigateur non rafraichit. Peux-tu recharger la page en faisant un cmd+R et me dire si tu reproduit le problème ?
