### ISSUE TITLE
Situation Bienvenue / Arrière-plan

### ISSUE THREAD

**Issue by telohtrab** [betagouv/eva#929]
Ref to #907

**Comment by telohtrab** [comment]
Voici ma proposition pour l'arrière plan des questions. C'est une version basse def pour le moment car basée sur une capture de Matthieu. Je ferai une version plus HD une fois les éléments finalisés. 

Ce background est exporté dans Assets Graphiques > 0_Bienvenue > exports_background

![image](https://user-images.githubusercontent.com/7781917/80509868-41223e00-897a-11ea-92e0-c33a25a3458e.png)

**Comment by etienneCharignon** [comment]
J'ai téléchargé cette image sur les questions de la préprod. On mettra l'image en hd sur la prod, mais en attendant ça permet de se faire une idée.

**Comment by telohtrab** [comment]
@MatthieuMARTIN Est-ce que tu penses que tu pourrais me faire cet assemblage en HD ? Comme je te disais, j'ai pas tous les éléments quand j'ouvre ton psd et j'ai envie de rien casser..  

T'embête pas pour la taille ou le crop, je m'en chargerai ;)

**Comment by MatthieuMARTIN** [comment]
@telohtrab @etienneCharignon c'est fait ! dans le drive ;
dans : 
![image](https://user-images.githubusercontent.com/58987553/80587228-754b3c80-8a16-11ea-93aa-42cf49ae3daa.png) puis dans dessin.

**Comment by etienneCharignon** [comment]
@MatthieuMARTIN @telohtrab je pensais qu'on voulait que le batiment s'appel Bienvenue non ?

**Comment by MatthieuMARTIN** [comment]
ah je n'ai pas su cela ! @telohtrab ? S'il faut changer aucun soucis pour moi, j'attend votre confirmation :)

**Comment by telohtrab** [comment]
On l'a certainement mentionné dans une issue ou sur slack, et j'ai nommé ce bâtiment "Bienvenue" dans mon SMS hier, désolé si c'était pas clair, my bad ! 

Je viens de te renvoyer un SMS dans ce sens.

**Comment by telohtrab** [comment]
Ah non c'est bien toi le poisson rouge ! 😅

 ![](https://i.imgur.com/mQ0RDbn.png)

**Comment by MatthieuMARTIN** [comment]
OUPS NAVRé !!!!!!!!!!!!

**Comment by MatthieuMARTIN** [comment]
c'est MAJ dans le drive, désolé pour la perte de temps ! a+

**Comment by telohtrab** [comment]
Merci @MatthieuMARTIN pas de problème, on est tous crevés avec le climat de m*** actuel 👍

**Comment by telohtrab** [comment]
> @MatthieuMARTIN Est-ce que tu penses que tu pourrais me faire cet assemblage en HD ? Comme je te disais, j'ai pas tous les éléments quand j'ouvre ton psd et j'ai envie de rien casser..
> 
> T'embête pas pour la taille ou le crop, je m'en chargerai ;)

Je me permets tout de même de voir si tu as lu ce message. Tu pourrais me faire en gros ce qu'on voit dans la fenêtre ci-dessus mais avec tes sources HD ? 

Merci !

**Comment by MatthieuMARTIN** [comment]
@telohtrab ah oui il te manquait le personnage en PNG c est ca ? je l'ai ajouté au dossier ! 
Du coup tu as maintenant dans le dossier : le fond, chaque bâtiment, et le perso. Donc il y a tout d exporté normalement, c'est bon pour toi ?

**Comment by telohtrab** [comment]
À vrai dire, je me demandais si tu pouvais faire l'assemblage de ton coté sur PS avec les assets HD, ce sera toujours plus propre que moi qui bidouille dans Figma ;-)

C'est pour ça que je te disais, t'embête pas pour la taille ou le crop (même si tu peux le faire de la taille habituelle de la gameview), pas besoin d'être précis, ça je peux le gérer facilement une fois intégré à Figma.

**Comment by MatthieuMARTIN** [comment]
Ah ok !! 
Je t'ai mis le jpg ci dessous dans le drive ! Avec les éléments séparés de la home ! 
C'est bon pour toi ? :) 


![Bienvenue-image-montage](https://user-images.githubusercontent.com/58987553/80612761-b5251a80-8a3c-11ea-937c-6c17f40d4445.png)

**Comment by telohtrab** [comment]
C'est parfait ! Merci beaucoup. 

Je me permets simplement de le déplacer dans 0_Bienvenue > dessins 

Merci encore

**Comment by telohtrab** [comment]
@etienneCharignon La version HD et croppée pour la Gameview se trouve donc ici :) 

![image](https://user-images.githubusercontent.com/7781917/80613941-25806b80-8a3e-11ea-9920-d7b210da9ed6.png)

**Comment by etienneCharignon** [comment]
Il me semble qu'on a terminé avec cette issue. @telohtrab  est-ce que tu peux la fermer et l'archiver ?

**Comment by telohtrab** [comment]
Effectivement, je close :)
