### ISSUE TITLE
Bienvenue : Intégration du bâtiment

### ISSUE THREAD

**Issue by etienneCharignon** [betagouv/eva#930]
Le bâtiment à intégrer doit s'appeler "Bienvenue". Il présente deux guichets avec des silhouettes. Quand il sera prêt il pourra être trouvé sur le drive dans `Assets_graphiques/00_Accueil_Parc/dessins`. C'est le bâtiment d'accès à la situation.

De plus, on ne veut plus afficher l'ancien bâtiment "Bienvenue" qui se trouve derrière la consigne de l'accueil.  La nouvelle MES ne vient pas remplacer l'ancien bâtiment. Il faut juste ne plus afficher de bâtiment en transparence derrière la consigne d'accueil.

- [ ] intégrer le nouveau bâtiment
- [x] ne plus afficher l'ancien bâtiment "Bienvenue"  (#933)

**Comment by shanser** [comment]
J'ai mis le tag bloqué en attendant le bâtiment qui va arriver prochainement

**Comment by etienneCharignon** [comment]
Le nouveau bâtiment est dans le drive voir #929. Je débloque

**Comment by etienneCharignon** [comment]
lol
