### ISSUE TITLE
MES LIVRAISON : QCM "Palette" 

### ISSUE THREAD

**Issue by Laurenmichel21** [betagouv/eva#931]
Il manque des réponses dans le QCM => cf photo ci-dessous

**Comment by Laurenmichel21** [comment]
<img width="1100" alt="Capture d’écran 2020-04-28 à 11 43 12" src="https://user-images.githubusercontent.com/57912856/80472959-c17a7c00-8945-11ea-98fb-400053e1c844.png">

**Comment by etienneCharignon** [comment]
La préprod ne contient pas les questions de la prod mais des contenus plus simple permettant de valider les principes. Est-ce qu'il te manque quelque chose pour valider que ça marche en préprod ? Si c'est le cas, n'hésite pas à mettre à jour les données dans l'interface d'admin de la préprod. Si ce que tu veux c'est avoir exactement les données de la prod alors il faut qu'on en parle plus en détail.

**Comment by Laurenmichel21** [comment]
Pas de besoin specifique,  juste besoin de le savoir et ton explication est très claire donc parfait, comme tu le sais j'embrasse la préprod depuis dimanche donc j'aurai certainement encore des questions dans les prochains jours pour bien comprendre ;-)  Merci Etienne pour ton éclairage. Du coup je te propose d'archiver cette carte
