### ISSUE TITLE
Intégrer nouvelle image sur le site vitrine

### ISSUE THREAD

**Issue by etienneCharignon** [betagouv/eva#938]
Voir #639 pour l'image

Intégrer l'image sur la home à la place de la dame en rouge

**Comment by etienneCharignon** [comment]
@telohtrab qu'est-ce qu'on fait pour cette page : 
https://eva.beta.gouv.fr/competences/

<img width="1031" alt="Capture d’écran 2020-05-04 à 10 52 20" src="https://user-images.githubusercontent.com/298214/80950099-840a6880-8df5-11ea-874f-5a920700c922.png">


On met aussi la nouvelle image à cet endroit ?

**Comment by etienneCharignon** [comment]
J'ai fais comme ça :
![Capture d’écran 2020-05-04 à 12 30 55](https://user-images.githubusercontent.com/298214/80957500-82e03800-8e03-11ea-9aa5-2c1b5aa48da7.png)

**Comment by telohtrab** [comment]
Et tu as très bien fait ! C'est ce que je comptais faire dans un premier temps puisqu'on a pas des dizaines de dessins dispos

**Comment by telohtrab** [comment]
Intégration de l'image, pas de problème.

Si possible rétablir le border-radius présent précédemment. Je viens de comprendre pourquoi ça a sauté, c'est l'image qui contenait le border-radius, au lieu d'être fait en code.
