### ISSUE TITLE
Mise à jour du contenu du site vitrine

### ISSUE THREAD

**Issue by etienneCharignon** [betagouv/eva#939]
Cette issue concerne la mise à jour du texte du site vitrine. Les mise à jours sont décrire dans le document suivant : 

https://docs.google.com/presentation/d/1obRpL47P8LCM0ihdaD3oXkH9WkhdaOilrNBmG-vvWyQ/edit#slide=id.g7272b0e344_1_13

Pour le commentaire sur le dernier slide (à propos de l'ouverture du logiciel de mail), j'ai créé une issue dédiée #940

**Comment by etienneCharignon** [comment]
@laurenehoutin a écrit :
> Pour la slide 9, l’idée est de retirer la page “compétences évaluées” (pour l’instant car ca ne correspond plus très bien au discours de déploiement) et donc également le lien qui y redirige depuis la home page. Est ce que c’est plus clair ?

Je propose de ne pas supprimer la page mais juste les liens vers cette page : 
- [ ] dans le menu
- [ ] à coté de l'illustration qui se trouve plus bas sur la home

**Comment by etienneCharignon** [comment]
La raison à ça c'est que nous devons garder les url vers les compétences qui sont utilisé dans l'application dans le dernier écran "compétences fortes".

par exemple, on veut garder l'url `https://eva.beta.gouv.fr/competences/rapidite/`

Sur le principe on pourrait supprimer l'url `https://eva.beta.gouv.fr/competences`sans supprimer les pages filles mais c'est pas très "web friendly" de faire un "trou" comme ça.

**Comment by shanser** [comment]
Sur chaque capture à gauche c'est Avant (en prod) et à droite c'est après (en préprod)

![Capture d’écran 2020-05-06 à 11 22 34](https://user-images.githubusercontent.com/28393/81162240-23ae2f00-8f8d-11ea-8887-2e07032cfdd6.png)
![Capture d’écran 2020-05-06 à 11 22 47](https://user-images.githubusercontent.com/28393/81162242-24df5c00-8f8d-11ea-9191-3b3aeed3cb4f.png)
![Capture d’écran 2020-05-06 à 11 25 04](https://user-images.githubusercontent.com/28393/81162244-24df5c00-8f8d-11ea-8095-8b0161a992cf.png)
![Capture d’écran 2020-05-06 à 11 25 13](https://user-images.githubusercontent.com/28393/81162246-2577f280-8f8d-11ea-8bac-b23e91ca12ed.png)
![Capture d’écran 2020-05-06 à 11 25 20](https://user-images.githubusercontent.com/28393/81162248-26108900-8f8d-11ea-93fd-d4056a4b8c77.png)

**Comment by etienneCharignon** [comment]
L'url de la préprod : https://preview.eva.beta.gouv.fr/
