### ISSUE TITLE
Site vitrine : ouverture du mail pour nous écrire

### ISSUE THREAD

**Issue by etienneCharignon** [betagouv/eva#940]
Cette issue concerne le problème décrit dans le dernier slide de ce document :

https://docs.google.com/presentation/d/1obRpL47P8LCM0ihdaD3oXkH9WkhdaOilrNBmG-vvWyQ/edit#slide=id.g7272b0e344_1_13

<img width="1287" alt="Capture d’écran 2020-05-04 à 11 13 43" src="https://user-images.githubusercontent.com/298214/80951534-638fdd80-8df8-11ea-8507-d0543c4b9041.png">

**Comment by etienneCharignon** [comment]
@laurenehoutin pourras-tu regardé si la configuration proposé dans ce lien permettrait de résoudre le problème sur ton ordinateur ? : https://support.pipedrive.com/hc/fr/articles/207882889-Comment-configurer-Gmail-comme-client-de-messagerie-par-d%C3%A9faut-de-mon-navigateur-

Cela nous permettra de mieux comprendre le problème. Si cette configuration corrige ton problème, on ne sera pas sortie d'affaire car il faudra trouver quelque chose pour les gens qui ne sont pas bien configurés.

**Comment by etienneCharignon** [comment]
C'est confirmé, il s'agit bien d'un problème de configuration du navigateur pour qu'il fonctionne avec le webmail gmail et la configuration est loin d'être triviale. Cela fait qu'on ne peut pas compter sur le fait que les clients potentiels n'auront pas le problème.

**Comment by laurenehoutin** [comment]
Crotte. Est ce qu'on ne peut pas faire un truc genre écrire l'adresse mail de contact tout simplement ? On faire un genre de pop-up... Je dis ça sans savoir aucunement ce que ca représente comme travail, donc c'est juste une idée

**Comment by etienneCharignon** [comment]
@telohtrab à cause de problème de configuration pour les utilisateurs et utilisatrices de webmail, le protocole "mailto:" n'est pas toujours opérationnel. Une amélioration proposés par @laurenehoutin ci-dessus passerait par un changement de design : écrire l'adresse email de contacte dans le footer. Par exemple : "Contacter l’équipe : contact@beta.gouv.fr". Qu'en penses-tu ?

**Comment by telohtrab** [comment]
Hello ! 

Pas d'objection particulière :) 

Une question cependant : il y a quelques années quand j'ai fait un peu de front, j'entendais toujours qu'il fallait jamais mettre en dur une adresse email pour éviter le crawling par des robots et donc se faire envahir de spams... C'est toujours d'actualité ? Ou la détection de spam est suffisamment efficace pour faire disparaître ce souci ?

**Comment by etienneCharignon** [comment]
En fait, l'adresse email est déjà mentionnée dans la page même si elle n'est pas visible pour les humain elle est parfaitement trouvée par les robots. C'est même fléché puisqu'ils n'ont qu'a chercher les liens "mailto:". Donc pour moi, pas plus de problème qu'avant si on écrit l'adresse email dans le nom du lien.
