### ISSUE TITLE
connaitre la répartition géographique des structures inscrites

### ISSUE THREAD

**Issue by etienneCharignon** [betagouv/eva#942]
Pour les besoins de compte rendu à la DGEFP, nous avons besoins de connaitre la répartition géographique des structures.

**Comment by etienneCharignon** [comment]
Dans l'issue 903, Lauren propose de créer un champ code postale dans la table des comptes. J'aimerai qu'on réfléchisse à introduire plutôt une table des structures ce qui devrait nous permettre aussi à plus long terme d'adresse l'issue de sécurité concernant le partage des mots de passe dans les structures.

Cette table Structure pourrait alors porter le champ "code postale" et être référencé dans la table compte.

**Comment by shanser** [comment]
Vidéo pour démontrer : https://www.loom.com/share/29e004b02673439fb38a3cdace6be1a1

**Comment by shanser** [comment]
Est-ce que ce commentaire https://github.com/betagouv/eva/issues/941#issuecomment-624780765 ne fait pas plutôt référence à ce sujet ?

> Merci Stéphane pour la video de démo c'est vraiment top.
J'ai une question : est ce qu'il n'était pas du tout possible d'intégrer le champ code postal au moment de la création du compte comme initialement demandé ? Car cela nous fait faire trois manipulation
>
> je crée la structure
> Je crée le compte
> je crée la campagne
> Et quand on n'en a une dizaine à créer c'est pas ce qu'il y a de plus simplifiant ;-)

Auquel cas j'avais répondu ça:

> Je suis d'accord avec toi, c'est fastidieux. Du coup j'ai créé une issue à part pour ta remarque
> 
> betagouv/eva-serveur#429

Quand j'ai écrit ce commentaire, c'était en pensant que cette carte était passée dans la colonne suivante.

Personnellement je recommande quand même traiter cette amélioration dans un ticket à part : c'est plus facile de gérer avec une granularité fine.

**Comment by Laurenmichel21** [comment]
Ok ca marche, ça me va , merci ;-)
