### ISSUE TITLE
Ajouter une question dans le questionnaire d'autopositionnement

### ISSUE THREAD

**Issue by laurenehoutin** [betagouv/eva#945]
Pouvez-vous ajouter la question suivante dans le questionnaire d'auto-positionnement svp :

“Êtes vous allé.e à l’école ?
- Oui, en France
- Oui, à l’étranger
- Non”

Ou si plus simple d’un point de vue dev :
“Êtes vous allé.e à l’école ?
- Oui
- Non”
et si oui “Où êtes vous allé.e à l’école ?
- En France
- A l’étranger”

**Comment by etienneCharignon** [comment]
@laurenehoutin Normalemet tu as toutes les billes pour ajouter la question toi même directement dans l'admin de la prod. N'hésite pas à me demande de l'aide sur slack si tu en as besoins.

**Comment by laurenehoutin** [comment]
Je suis désolée mais si je demande c'est justement que je n'ai pas toutes les billes.
1) Personne ne m'a jamais montré l'admin et encore moins comment on ajoute des questions,
2) en cherchant, j'ai bien cru comprendre comment je devais faire, mais par soucis de ne pas foutre le bordel dans ce que vous avez fait, j'ai préféré vous demander.
Sans certaines informations (comme par exemple que mettre dans Bon/Mauvais/Abstention?), cela me parait risqué.
3) tout comme vous, je manque de temps pour faire le boulot que j'ai à faire Je pensais juste que ca te prendrait 3 secondes et que donc ce serait mieux pour le projet.

**Comment by etienneCharignon** [comment]
Ca me semble bon. Je close l'issue et je la passe dans la colonne mis en production cette semaine
