### ISSUE TITLE
Page stats home page

### ISSUE THREAD

**Issue by Laurenmichel21** [betagouv/eva#946]
- [x] Retirer  le wording :  (sans les tests) dans le graphique en bas à gauche, ce genre d'info ne se mentionne pas dans des stats grand public 
- [x] La page est en carafe

**Comment by Laurenmichel21** [comment]
<img width="1312" alt="Capture d’écran 2020-05-04 à 16 48 50" src="https://user-images.githubusercontent.com/57912856/80979112-3dcdfd00-8e27-11ea-908a-ba7bdbf57d90.png">

**Comment by etienneCharignon** [comment]
J'ai vu que tu avais modifié le wording 🙌

Pour le problème de disponibilité du site, c'est en cours, je continue d'essayer de trouver une solution. Ça prend du temps car le problème survient en général au bout de 24H. Chaque jours, je change un paramettre, puis j'attends le lendemain pour constater l'effet de ce changement. 

N'hésite pas à me prévenir si tu as un besoins urgent de la page de state, je peux faire un redémarrage de l'application ce qui résout le problème temps de réponse ponctuellement. (ça prend moins d'une minutes)

**Comment by etienneCharignon** [comment]
Depuis le modifications décrire ci-dessous du Jeudi 5 mai, je n'ai pas eu a redémarrer metabase. Donc, je pense que le problème est résolu.

Je refais aujourd'hui un test pour diminuer la quantité de mémoire total qui ne devrait pas avoir besoin d'être aussi importante. Si tout est toujours OK demain matin, je fermerait cette issue.

Modification technique :
Avec l'ajout de la variable d'environnement MAX_METASPACE_SIZE=512m

**Comment by etienneCharignon** [comment]
Tout se passe bien. Finalement, je teste aussi en retirant un CPU. Je ne fermerais que demain du coup

**Comment by etienneCharignon** [comment]
Nous n'avons plus eu de crash depuis 1 semaine, même avec mes réduction de lundi et mardi. Je clos cette issue
