### ISSUE TITLE
Nouvelle restitution : combinaison des côtes z

### ISSUE THREAD

**Issue by Alexis-Akinyemi** [betagouv/eva#962]
Dans cette issue on décrit : 
1. comment rassembler les scores d'une même meta-compétence évaluées au sein de plusieurs MES.
2. comment rassembler les scores des meta-compétences pour obtenir la restitution globale littératie/numératie.

**Comment by Alexis-Akinyemi** [comment]
Préalables potentiels : 
- [Note explicative de la nouvelle restitution](https://docs.google.com/document/d/1S309w_PXbNLdm74X1TBVht-XWL2dWTEr-GxvLTXDW0A/edit),
- [Exemple de la nouvelle restitution validé par la DGEFP](https://docs.google.com/document/d/1lavMShia9UuPrTGxZHvgMZlrWS_CWwTLbjLlxOiluYQ/edit#heading=h.tu09qmb5xjuo),
- [Le document de travail qui couvre cette issue ](https://docs.google.com/document/d/1zhdUZo3zgcfqA4Ie8VbYekTvAq3M25rYlnA0VjJIuaA/edit#)

__Cas d'usage :__ 
En tant qu'évalué je veux connaître le score de compréhension du français au travers de l'ensemble des mises en situation qui permettaient de l'évaluer.  (s'applique à toutes les méta-compétences).

**Comment by etienneCharignon** [comment]
avec @Alexis-Akinyemi nous avons créé des issues Trello pour suivre ces sujets. Je ferme cette issue qui n'est plus à jours.
