### ISSUE TITLE
Nouvelle restitution : correspondance entre côte z et texte de restitution

### ISSUE THREAD

**Issue by Alexis-Akinyemi** [betagouv/eva#963]
Dans cette issue on décrit comme faire le lien entre les scores des métacompétences et les textes des nouvelles restitutions.
__Ce qu'on ne décrit pas :___ la manière dont les utilisateurs visualiseront lesdits textes.

**Comment by Alexis-Akinyemi** [comment]
Préalables potentiels : 
- [Note explicative de la nouvelle restitution](https://docs.google.com/document/d/1S309w_PXbNLdm74X1TBVht-XWL2dWTEr-GxvLTXDW0A/edit),
- [Exemple de la nouvelle restitution validé par la DGEFP](https://docs.google.com/document/d/1lavMShia9UuPrTGxZHvgMZlrWS_CWwTLbjLlxOiluYQ/edit#heading=h.tu09qmb5xjuo),
- [Le document de travail qui couvre cette issue ](https://docs.google.com/document/d/1zhdUZo3zgcfqA4Ie8VbYekTvAq3M25rYlnA0VjJIuaA/edit#)

__Cas d'usage :__ en tant qu'accompagné, je veux connaître précisément ce à quoi correspond mon score de littératie et numératie. 

__Méthode__
Nous allons faire correspondre un texte de restitution au score de chaque utilisateur. Pour cela nous allons utiliser des seuils de côtes z qui rassemble les utilisateurs dans des tranches de scores qui correspondent théoriquement (à vérifier au fil de l'eau) aux niveaux ciblés sur les référentiels de compétences que nous utilisons.

__La manière d'afficher ce texte à l'utilisateur sera traitée dans une prochaine issue, voici d'abord le tableau des correspondances :___ 

__Attention : la première ligne du tableau correspond à un cas particulier de restitution qui ne mobilise pas les côtes z, il est décrit dans l'issue [967](https://github.com/betagouv/eva/issues/967) : 

## Partie 1 textes correspondant au score global (combinaison des meta-compétences):

**Comment by Alexis-Akinyemi** [comment]
<tr>
   <td>Type d’évaluation

   </td>
   <td>Restitution

   </td>
   <td>Nb de bonnes réponses

   </td>
   <td>Cote z des temps de réponse

   </td>
   <td>Texte de Restitution

   </td>
  </tr>
  <tr>
   <td>Evaluation de l’illettrisme

   </td>
   <td>Potentiellement en situation d’illettrisme 

   </td>
   <td>&lt; 80 %

   </td>
   <td>Non utilisé

   </td>
   <td>Votre score indique que vous rencontrez d’importantes difficultés en français et en mathématiques qui pourraient vous desservir dans vos futurs emplois et formations.

**Nous vous conseillons de participer à une formation que votre conseiller sera à même de vous proposer pour améliorer et certifier ces compétences ! **La formation “ Socle de connaissances et de compétences professionnelles” Cléa serait par exemple très adaptée.

   </td>
  </tr>
  <tr>
   <td rowspan="7" >Evaluation de la littératie et la numératie 

   </td>
   <td>Littératie A1

   </td>
   <td>>80%

   </td>
   <td>z&lt; -1

   </td>
   <td>Votre score indique que vous rencontrez de légères difficultés en français. Cela pourrait diminuer vos chances d’accéder à certaines formations ou à certains emplois.

**Nous vous conseillons de participer à une formation que votre conseiller sera à même de vous proposer pour améliorer et certifier vos compétences en français !**

   </td>
  </tr>
   <td>Littératie A2

   </td>
   <td>>80%

   </td>
   <td>-1 =&lt; z &lt; 0

   </td>
   <td>Votre score indique que votre maîtrise du français est correcte mais pourrait être améliorée pour vous faciliter l’accès à des formations ou à un emploi. \
**Nous vous conseillons de participer à une formation que votre conseiller sera à même de vous proposer pour améliorer et certifier vos compétences en français !**

   </td>
   <td>Littératie B1

   </td>
   <td>>80%

   </td>
   <td>z>=0

   </td>
   <td>Votre score indique que vous maîtrisez tout à fait le français, bravo ! 

**La maîtrise du français est une compétence très utile pour se former et accéder à de nombreux emplois, profitez-en !**

   </td>
   <td>Numératie X1

   </td>
   <td>>80%

   </td>
   <td>z&lt; -1

   </td>
   <td>Votre score indique que vous rencontrez de légères difficultés en mathématiques. Cela pourrait diminuer vos chances d’accéder à certaines formation ou à certains emplois.

**Nous vous conseillons de participer à une formation que votre conseiller sera à même de vous proposer pour améliorer et certifier vos compétences en mathématiques !**

   </td>
   <td>Numératie X2

   </td>
   <td>>80%

   </td>
   <td>-1 =&lt; z &lt; 0

   </td>
   <td>Votre score indique que votre maîtrise des mathématiques est correcte mais pourrait être améliorée pour vous faciliter l’accès à des formations ou à un emploi. \
**Nous vous conseillons de participer à une formation que votre conseiller sera à même de vous proposer pour améliorer et certifier vos compétences en mathématiques !**

   </td>
   <td>Numératie Y1

   </td>
   <td>>80%

   </td>
   <td>z>=0

   </td>
   <td>Votre score indique que vous maîtrisez tout à fait les mathématiques de base, bravo ! 

**La maîtrise des mathématiques est une compétence importante pour se former et accéder à de nombreux emplois, profitez-en !**

   </td>
   <td>Socle Cléa Atteint, soit Littératie B1 ET Numératie Y1

   </td>
   <td>>80%

   </td>
   <td>z > 0 numératie et littératie

   </td>
   <td>Votre score indique que vous pouvez vous adapter à tout emploi ou toute formation qui demanderait une bonne maîtrise de la langue française et des mathématiques.

**Votre niveau correspond au minimum au socle de compétences de base du référentiel Cléa Certif’Pro, parlez en avec votre conseiller pour savoir si cette certification pourrait être utile à votre projet ! **

   </td>

**Comment by etienneCharignon** [comment]
avec @Alexis-Akinyemi nous avons créé des issues Trello pour suivre ces sujets. Je ferme cette issue qui n'est plus à jours.
