### ISSUE TITLE
Calcul des côtes z des méta-compétences de livraison et objets-trouvés

### ISSUE THREAD

**Issue by Alexis-Akinyemi** [betagouv/eva#966]
Dans cette issue on décrit comment sont calculés les scores des méta-compétences communication et compréhension du français, syntaxe, numératie et mémorisation.

Une seule issue de description car la règle est unique pour toutes ces méta-compétences : 

__Cote z de nombre de bonnes réponses méta-compétence / temps moyen de bonnes réponse méta-compétence__

Exemple pour communication et compréhension du français : 

__score__ = nombre de bonnes réponse / temps moyen de bonnes réponses

Puis calcul de la côte z pour la valeur obtenue (formule déjà utilisée mainte fois) : 
__côte z__ = (score - score moyen de l'échantillon)/ecart type de l'échantillon

**Comment by etienneCharignon** [comment]
avec @Alexis-Akinyemi nous avons créé des issues Trello pour suivre ces sujets. Je ferme cette issue qui n'est plus à jours.
