### ISSUE TITLE
Cas particulier de restitution : nombre de bonnes réponses  <80 % sur une sélection de questions

### ISSUE THREAD

**Issue by Alexis-Akinyemi** [betagouv/eva#967]
Dans cette issue on décrit la manière dont on pourra indiquer à l'utilisateur qu'il est potentiellement en situation d'illettrisme.

**Comment by Alexis-Akinyemi** [comment]
__Cas d'usage__ en tant qu'accompagnant je veux que l'identification d'une personne en situation d'illettrisme soit la même qu'elle provienne d'eva ou de l'anlci. 

__Méthode__ 
On crée un compteur de bonnes réponses pour les événements suivants : 

Situation Maintenance : toutes les réponses
Situation Livraison : toutes les réponses
Situation Objets trouvés : toutes les questions __à l'exclusion de celles mesurant la meta-compétence mémorisation__

Pour chaque personne, le pourcentage de bonnes réponse est ensuite calculé.
Si ce pourcentage >80% --> Rien ne se passe 
Si ce pourcentage < 80 % --> La restitution globale de la personne pour la littératie est la numératie est la première du [tableau regroupant les textes de la nouvelle restitution](https://docs.google.com/document/d/1sp0PxGwPuKb2BEv2SRv3XYIDVsHk1iWKMhNsMJOlyC8/edit?usp=sharing).

**Comment by etienneCharignon** [comment]
avec @Alexis-Akinyemi nous avons créé des issues Trello pour suivre ces sujets. Je ferme cette issue qui n'est plus à jours.

**Comment by etienneCharignon** [comment]
issue suivie dans trello : https://trello.com/c/lKAGCdmf
